package org.allaymc.codegen;

import com.squareup.javapoet.*;
import lombok.SneakyThrows;

import javax.lang.model.element.Modifier;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Comparator;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;

import static org.allaymc.codegen.ClassNames.*;

/**
 * @author daoge_cmd | IWareQ | Cool_Loong
 */
public class BiomeIdEnumGen {
    private static final Map<String, BiomeData> BIOME_DATA = new LinkedHashMap<>();
    private static final String PACKAGE_NAME = "org.allaymc.api.world.biome";
    private static final Path OUTPUT_PATH = Path.of("api/src/main/java/org/allaymc/api/world/biome/BiomeId.java");

    static {
        try {
            Map<String, BiomeData> unsorted = CodeGenConstants.GSON.fromJson(Files.newBufferedReader(Path.of(CodeGenConstants.DATA_PATH + "unpacked/biome_id_and_type.json")), new HashMap<String, BiomeData>() {
            }.getClass().getGenericSuperclass());
            unsorted.entrySet()
                    .stream()
                    .sorted(Map.Entry.comparingByValue(Comparator.comparingInt(o -> o.id)))
                    .forEachOrdered(entry -> BIOME_DATA.put(entry.getKey(), entry.getValue()));
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    public static void main(String[] args) {
        generate();
    }

    @SneakyThrows
    public static void generate() {
        TypeSpec.Builder codeBuilder = TypeSpec.enumBuilder("BiomeId")
                .addJavadoc("Automatically generated by {@code org.allaymc.codegen.BiomeIdEnumGen}")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(GETTER)
                .addAnnotation(MINECRAFT_VERSION_SENSITIVE)
                .addStaticBlock(
                        CodeBlock.builder()
                                .addStatement("MAP1 = $L", "new BiomeId[256]")
                                .addStatement("MAP2 = $L", "new HashMap<>()")
                                .beginControlFlow("for (var biome : values())")
                                .addStatement("MAP1[biome.id] = biome")
                                .addStatement("MAP2.put(biome.identifier, biome)")
                                .endControlFlow()
                                .build()
                )
                .addField(FieldSpec
                        .builder(ClassNames.BIOME_ARRAY, "VALUES", Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                        .initializer("values()")
                        .build())
                .addField(FieldSpec
                        .builder(ClassNames.BIOME_ARRAY, "MAP1", Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
                        .build())
                .addField(FieldSpec
                        .builder(ParameterizedTypeName.get(HASH_MAP, ClassNames.API_IDENTIFIER, ClassNames.BIOME_TYPE), "MAP2", Modifier.PRIVATE, Modifier.FINAL, Modifier.STATIC)
                        .build())
                .addField(FieldSpec
                        .builder(ClassNames.API_IDENTIFIER, "identifier", Modifier.PRIVATE, Modifier.FINAL)
                        .build())
                .addField(FieldSpec
                        .builder(int.class, "id", Modifier.PRIVATE, Modifier.FINAL)
                        .build())
                .addField(FieldSpec
                        .builder(ClassNames.STRING, "type", Modifier.PRIVATE, Modifier.FINAL)
                        .build())
                .addMethod(MethodSpec.constructorBuilder()
                        .addParameter(ClassNames.API_IDENTIFIER, "identifier")
                        .addParameter(int.class, "id")
                        .addParameter(ClassNames.STRING, "type")
                        .addStatement("this.identifier = identifier")
                        .addStatement("this.id = id")
                        .addStatement("this.type = type")
                        .build()
                );
        for (var entry : BIOME_DATA.entrySet()) {
            var identifier = """
                    new Identifier("minecraft:%s")""".formatted(entry.getKey());
            var id = entry.getValue().id;
            var type = entry.getValue().type;
            codeBuilder.addEnumConstant(entry.getKey().toUpperCase(), TypeSpec.anonymousClassBuilder("$L, $L, $S", identifier, id, type).build());
        }
        codeBuilder.addSuperinterface(ClassNames.BIOME_TYPE);

        codeBuilder.addMethod(MethodSpec
                .methodBuilder("fromId")
                .addParameter(int.class, "id")
                .addModifiers(Modifier.STATIC, Modifier.PUBLIC)
                .addCode("return MAP1[id];")
                .returns(ClassNames.BIOME_TYPE)
                .build());
        codeBuilder.addMethod(MethodSpec
                .methodBuilder("fromIdentifier")
                .addParameter(ClassNames.API_IDENTIFIER, "identifier")
                .addModifiers(Modifier.STATIC, Modifier.PUBLIC)
                .addCode("return MAP2.get(identifier);")
                .returns(ClassNames.BIOME_TYPE)
                .build());
        var builtCode = codeBuilder.build();
        var javaFile = JavaFile.builder(PACKAGE_NAME, builtCode)
                .indent(CodeGenConstants.INDENT)
                .skipJavaLangImports(true)
                .build();
        Files.writeString(OUTPUT_PATH, javaFile.toString());
    }

    private static class BiomeData {
        int id;
        String type;
    }
}
