package cn.allay.codegen;

import cn.allay.identifier.Identifier;
import com.squareup.javapoet.*;
import lombok.SneakyThrows;
import org.cloudburstmc.nbt.NBTInputStream;
import org.cloudburstmc.nbt.NbtMap;
import org.cloudburstmc.nbt.NbtType;

import javax.lang.model.element.Modifier;
import java.io.DataInputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.zip.GZIPInputStream;

import static cn.allay.codegen.CodeGen.BLOCK_PALETTE_NBT;

/**
 * Author: daoge_cmd <br>
 * Date: 2023/3/26 <br>
 * Allay Project <br>
 */
public class VanillaBlockIdEnumGen {

    private static final Path FILE_OUTPUT_PATH = Path.of("Allay-API/src/main/java/cn/allay/block/data/VanillaBlockId.java");

    @SneakyThrows
    public static void generate() {
        var identifierClass = ClassName.get("cn.allay.identifier", "Identifier");
        var stringClass = ClassName.get("java.lang", "String");
        var getterClass = ClassName.get("lombok", "Getter");
        TypeSpec.Builder codeBuilder = TypeSpec.enumBuilder("VanillaBlockId")
                .addJavadoc(
                        "Author: daoge_cmd <br>\n" +
                        "Automatically generated by {@link cn.allay.codegen.VanillaBlockIdEnumGen} <br>\n" +
                        "Allay Project <br>\n")
                .addModifiers(Modifier.PUBLIC)
                .addField(FieldSpec
                        .builder(Identifier.class, "namespaceId", Modifier.PRIVATE, Modifier.FINAL)
                        .addAnnotation(getterClass)
                        .build())
                .addMethod(MethodSpec.constructorBuilder()
                        .addParameter(stringClass, "namespaceId")
                        .addStatement("this.$N = new $T($N)", "namespaceId", identifierClass, "namespaceId")
                        .build()
                );
        var sortedNamespaceId = BLOCK_PALETTE_NBT.stream().map(block -> block.getString("name")).sorted(String::compareTo).map(Identifier::new).toList();
        for (var namespaceId : sortedNamespaceId) {
            codeBuilder
                    .addEnumConstant(namespaceId.getPath().toUpperCase(),
                            TypeSpec.anonymousClassBuilder("$S", namespaceId.toString()).build());
        }

        var javaFile = JavaFile.builder("cn.allay.block.data", codeBuilder.build()).build();
        Files.writeString(FILE_OUTPUT_PATH, javaFile.toString());
    }
}
