package org.allaymc.api.block.property.enums;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen}
 * <p>
 * Allay Project
 *
 * @author daoge_cmd
 */
public enum BambooLeafSize {
    NO_LEAVES,

    SMALL_LEAVES,

    LARGE_LEAVES
}
