package org.allaymc.api.block.property.enums;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <p>
 * @author daoge_cmd | CoolLoong
 */
public enum BambooLeafSize {
  SMALL_LEAVES,

  LARGE_LEAVES,

  NO_LEAVES
}
