package org.allaymc.api.block.property.enums;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen}
 * <p>
 * Allay Project
 *
 * @author daoge_cmd
 */
public enum BigDripleafTilt {
    NONE,

    UNSTABLE,

    PARTIAL_TILT,

    FULL_TILT
}
