package org.allaymc.api.block.property.enums;

import org.allaymc.api.annotation.MinecraftVersionSensitive;

/**
 * Automatically generated by {@code org.allaymc.codegen.BlockPropertyTypeGen}
 */
@MinecraftVersionSensitive
public enum ChemistryTableType {
    COMPOUND_CREATOR,

    MATERIAL_REDUCER,

    ELEMENT_CONSTRUCTOR,

    LAB_TABLE
}
