package org.allaymc.api.block.property.enums;

/**
 * Automatically generated by {@code org.allaymc.codegen.BlockPropertyTypeGen}
 * <p>
 * Allay Project
 *
 * @author daoge_cmd
 */
public enum ChiselType {
    DEFAULT,

    CHISELED,

    LINES,

    SMOOTH
}
