package org.allaymc.api.block.property.enums;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <p>
 * @author daoge_cmd | CoolLoong
 */
public enum DirtType {
  NORMAL,

  COARSE
}
