package org.allaymc.api.block.property.enums;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen}
 * <p>
 * Allay Project
 *
 * @author daoge_cmd
 */
public enum MonsterEggStoneType {
    STONE,

    COBBLESTONE,

    STONE_BRICK,

    MOSSY_STONE_BRICK,

    CRACKED_STONE_BRICK,

    CHISELED_STONE_BRICK
}
