package org.allaymc.api.block.property.enums;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <p>
 * @author daoge_cmd | CoolLoong
 */
public enum MonsterEggStoneType {
  MOSSY_STONE_BRICK,

  COBBLESTONE,

  CHISELED_STONE_BRICK,

  STONE_BRICK,

  STONE,

  CRACKED_STONE_BRICK
}
