package org.allaymc.api.block.property.enums;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <p>
 * @author daoge_cmd
 */
public enum Orientation {
  UP_EAST,

  UP_SOUTH,

  WEST_UP,

  UP_NORTH,

  NORTH_UP,

  DOWN_WEST,

  DOWN_EAST,

  SOUTH_UP,

  UP_WEST,

  DOWN_SOUTH,

  EAST_UP,

  DOWN_NORTH
}
