package org.allaymc.api.block.property.enums;

import org.allaymc.api.annotation.MinecraftVersionSensitive;

/**
 * Automatically generated by {@code org.allaymc.codegen.BlockPropertyTypeGen}
 */
@MinecraftVersionSensitive
public enum Orientation {
    DOWN_EAST,

    DOWN_NORTH,

    DOWN_SOUTH,

    DOWN_WEST,

    UP_EAST,

    UP_NORTH,

    UP_SOUTH,

    UP_WEST,

    WEST_UP,

    EAST_UP,

    NORTH_UP,

    SOUTH_UP
}
