package org.allaymc.api.block.property.enums;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen}
 * <p>
 * Allay Project
 *
 * @author daoge_cmd
 */
public enum StoneSlabType2 {
    RED_SANDSTONE,

    PURPUR,

    PRISMARINE_ROUGH,

    PRISMARINE_DARK,

    PRISMARINE_BRICK,

    MOSSY_COBBLESTONE,

    SMOOTH_SANDSTONE,

    RED_NETHER_BRICK
}
