package org.allaymc.api.block.property.enums;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen}
 * <p>
 * Allay Project
 *
 * @author daoge_cmd
 */
public enum StoneSlabType {
    BRICK,

    COBBLESTONE,

    NETHER_BRICK,

    QUARTZ,

    SANDSTONE,

    SMOOTH_STONE,

    STONE_BRICK,

    WOOD
}
