package org.allaymc.api.block.property.enums;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen}
 * <p>
 * Allay Project
 *
 * @author daoge_cmd
 */
public enum StoneSlabType3 {
    ANDESITE,

    DIORITE,

    END_STONE_BRICK,

    GRANITE,

    POLISHED_ANDESITE,

    POLISHED_DIORITE,

    POLISHED_GRANITE,

    SMOOTH_RED_SANDSTONE
}
