package org.allaymc.api.block.property.enums;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <p>
 * @author daoge_cmd
 */
public enum StoneSlabType2 {
  PRISMARINE_ROUGH,

  RED_SANDSTONE,

  PRISMARINE_DARK,

  SMOOTH_SANDSTONE,

  PURPUR,

  RED_NETHER_BRICK,

  PRISMARINE_BRICK,

  MOSSY_COBBLESTONE
}
