package org.allaymc.api.block.property.enums;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen}
 * <p>
 * Allay Project
 *
 * @author daoge_cmd
 */
public enum StoneSlabType2 {
    MOSSY_COBBLESTONE,

    PRISMARINE_BRICK,

    PRISMARINE_DARK,

    PRISMARINE_ROUGH,

    PURPUR,

    RED_NETHER_BRICK,

    RED_SANDSTONE,

    SMOOTH_SANDSTONE
}
