package org.allaymc.api.block.property.enums;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen}
 * <p>
 * Allay Project
 *
 * @author daoge_cmd
 */
public enum TorchFacingDirection {
    EAST,

    NORTH,

    SOUTH,

    TOP,

    UNKNOWN,

    WEST
}
