package org.allaymc.api.block.property.enums;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen}
 * <p>
 * Allay Project
 *
 * @author daoge_cmd
 */
public enum TurtleEggCount {
    ONE_EGG,

    TWO_EGG,

    THREE_EGG,

    FOUR_EGG
}
