package org.allaymc.api.block.property.enums;

import org.allaymc.api.annotation.MinecraftVersionSensitive;

/**
 * Automatically generated by {@code org.allaymc.codegen.BlockPropertyTypeGen}
 */
@MinecraftVersionSensitive
public enum TurtleEggCount {
    ONE_EGG,

    TWO_EGG,

    THREE_EGG,

    FOUR_EGG
}
