package org.allaymc.api.block.property.enums;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <p>
 * @author daoge_cmd
 */
public enum WallBlockType {
  PRISMARINE,

  RED_SANDSTONE,

  MOSSY_STONE_BRICK,

  MOSSY_COBBLESTONE,

  SANDSTONE,

  NETHER_BRICK,

  COBBLESTONE,

  GRANITE,

  RED_NETHER_BRICK,

  STONE_BRICK,

  END_BRICK,

  BRICK,

  ANDESITE,

  DIORITE
}
