package cn.allay.block.property.vanilla.enums;

/**
 * Author: daoge_cmd <br>
 * Automatically generated by {@link cn.allay.codegen.VanillaBlockPropertyGen} <br>
 * Allay Project <br>
 */
public enum BigDripleafTilt {
  NONE,

  UNSTABLE,

  PARTIAL_TILT,

  FULL_TILT
}
