package cn.allay.block.property.vanilla.enums;

/**
 * Author: daoge_cmd <br>
 * Automatically generated by {@link cn.allay.codegen.VanillaBlockPropertyGen} <br>
 * Allay Project <br>
 */
public enum ChemistryTableType {
  COMPOUND_CREATOR,

  MATERIAL_REDUCER,

  ELEMENT_CONSTRUCTOR,

  LAB_TABLE
}
