package cn.allay.block.property.vanilla.enums;

/**
 * Author: daoge_cmd <br>
 * Automatically generated by {@link cn.allay.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <br>
 */
public enum DoublePlantType {
  SUNFLOWER,

  SYRINGA,

  GRASS,

  FERN,

  ROSE,

  PAEONIA
}
