package cn.allay.block.property.vanilla.enums;

/**
 * Author: daoge_cmd <br>
 * Automatically generated by {@link cn.allay.codegen.VanillaBlockPropertyGen} <br>
 * Allay Project <br>
 */
public enum WallBlockType {
  COBBLESTONE,

  MOSSY_COBBLESTONE,

  GRANITE,

  DIORITE,

  ANDESITE,

  SANDSTONE,

  BRICK,

  STONE_BRICK,

  MOSSY_STONE_BRICK,

  NETHER_BRICK,

  END_BRICK,

  PRISMARINE,

  RED_SANDSTONE,

  RED_NETHER_BRICK
}
