package org.allaymc.api.data;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaBlockTagGen} <br>
 * Allay Project <p>
 * @author daoge_cmd
 */
public interface VanillaBlockTags {
  String CROP = "minecraft:crop";

  String LOG = "log";

  String STONE_PICK_DIGGABLE = "stone_pick_diggable";

  String GRASS = "grass";

  String OAK = "oak";

  String WOOD = "wood";

  String DARK_OAK = "dark_oak";

  String FERTILIZE_AREA = "fertilize_area";

  String SPRUCE = "spruce";

  String GOLD_PICK_DIGGABLE = "gold_pick_diggable";

  String TRAPDOORS = "trapdoors";

  String IRON_PICK_DIGGABLE = "iron_pick_diggable";

  String BIRCH = "birch";

  String RAIL = "rail";

  String DIRT = "dirt";

  String METAL = "metal";

  String TEXT_SIGN = "text_sign";

  String WATER = "water";

  String DIAMOND_PICK_DIGGABLE = "diamond_pick_diggable";

  String STONE = "stone";

  String GRAVEL = "gravel";

  String SAND = "sand";

  String SNOW = "snow";

  String PLANT = "plant";

  String WOOD_PICK_DIGGABLE = "wood_pick_diggable";

  String ACACIA = "acacia";

  String NOT_FEATURE_REPLACEABLE = "not_feature_replaceable";

  String JUNGLE = "jungle";

  String MOB_SPAWNER = "mob_spawner";

  String PUMPKIN = "pumpkin";
}
