package org.allaymc.api.data;

import lombok.Getter;
import org.allaymc.api.identifier.Identifier;
import org.allaymc.api.item.registry.ItemTypeRegistry;
import org.allaymc.api.item.type.ItemType;

/**
 * Automatically generated by {@code org.allaymc.codegen.VanillaItemIdEnumGen} <br>
 * Allay Project <p>
 * @author daoge_cmd | Cool_Loong
 */
public enum VanillaItemId {
  ACACIA_BOAT("minecraft:acacia_boat", 382),

  ACACIA_BUTTON("minecraft:acacia_button", -140),

  ACACIA_CHEST_BOAT("minecraft:acacia_chest_boat", 650),

  ACACIA_DOOR("minecraft:acacia_door", 564),

  ACACIA_FENCE("minecraft:acacia_fence", -575),

  ACACIA_FENCE_GATE("minecraft:acacia_fence_gate", 187),

  ACACIA_HANGING_SIGN("minecraft:acacia_hanging_sign", -504),

  ACACIA_LOG("minecraft:acacia_log", 162),

  ACACIA_PLANKS("minecraft:acacia_planks", -742),

  ACACIA_PRESSURE_PLATE("minecraft:acacia_pressure_plate", -150),

  ACACIA_SIGN("minecraft:acacia_sign", 587),

  ACACIA_STAIRS("minecraft:acacia_stairs", 163),

  ACACIA_STANDING_SIGN("minecraft:acacia_standing_sign", -190),

  ACACIA_TRAPDOOR("minecraft:acacia_trapdoor", -145),

  ACACIA_WALL_SIGN("minecraft:acacia_wall_sign", -191),

  ACTIVATOR_RAIL("minecraft:activator_rail", 126),

  AGENT_SPAWN_EGG("minecraft:agent_spawn_egg", 490),

  AIR("minecraft:air", -158),

  ALLAY_SPAWN_EGG("minecraft:allay_spawn_egg", 639),

  ALLOW("minecraft:allow", 210),

  AMETHYST_BLOCK("minecraft:amethyst_block", -327),

  AMETHYST_CLUSTER("minecraft:amethyst_cluster", -329),

  AMETHYST_SHARD("minecraft:amethyst_shard", 632),

  ANCIENT_DEBRIS("minecraft:ancient_debris", -271),

  ANDESITE("minecraft:andesite", -594),

  ANDESITE_STAIRS("minecraft:andesite_stairs", -171),

  ANGLER_POTTERY_SHERD("minecraft:angler_pottery_sherd", 664),

  ANVIL("minecraft:anvil", 145),

  APPLE("minecraft:apple", 257),

  ARCHER_POTTERY_SHERD("minecraft:archer_pottery_sherd", 665),

  ARMOR_STAND("minecraft:armor_stand", 560),

  ARMS_UP_POTTERY_SHERD("minecraft:arms_up_pottery_sherd", 666),

  ARROW("minecraft:arrow", 304),

  AXOLOTL_BUCKET("minecraft:axolotl_bucket", 372),

  AXOLOTL_SPAWN_EGG("minecraft:axolotl_spawn_egg", 504),

  AZALEA("minecraft:azalea", -337),

  AZALEA_LEAVES("minecraft:azalea_leaves", -324),

  AZALEA_LEAVES_FLOWERED("minecraft:azalea_leaves_flowered", -325),

  BAKED_POTATO("minecraft:baked_potato", 282),

  BALLOON("minecraft:balloon", 606),

  BAMBOO("minecraft:bamboo", -163),

  BAMBOO_BLOCK("minecraft:bamboo_block", -527),

  BAMBOO_BUTTON("minecraft:bamboo_button", -511),

  BAMBOO_CHEST_RAFT("minecraft:bamboo_chest_raft", 662),

  BAMBOO_DOOR("minecraft:bamboo_door", -517),

  BAMBOO_DOUBLE_SLAB("minecraft:bamboo_double_slab", -521),

  BAMBOO_FENCE("minecraft:bamboo_fence", -515),

  BAMBOO_FENCE_GATE("minecraft:bamboo_fence_gate", -516),

  BAMBOO_HANGING_SIGN("minecraft:bamboo_hanging_sign", -522),

  BAMBOO_MOSAIC("minecraft:bamboo_mosaic", -509),

  BAMBOO_MOSAIC_DOUBLE_SLAB("minecraft:bamboo_mosaic_double_slab", -525),

  BAMBOO_MOSAIC_SLAB("minecraft:bamboo_mosaic_slab", -524),

  BAMBOO_MOSAIC_STAIRS("minecraft:bamboo_mosaic_stairs", -523),

  BAMBOO_PLANKS("minecraft:bamboo_planks", -510),

  BAMBOO_PRESSURE_PLATE("minecraft:bamboo_pressure_plate", -514),

  BAMBOO_RAFT("minecraft:bamboo_raft", 661),

  BAMBOO_SAPLING("minecraft:bamboo_sapling", -164),

  BAMBOO_SIGN("minecraft:bamboo_sign", 660),

  BAMBOO_SLAB("minecraft:bamboo_slab", -513),

  BAMBOO_STAIRS("minecraft:bamboo_stairs", -512),

  BAMBOO_STANDING_SIGN("minecraft:bamboo_standing_sign", -518),

  BAMBOO_TRAPDOOR("minecraft:bamboo_trapdoor", -520),

  BAMBOO_WALL_SIGN("minecraft:bamboo_wall_sign", -519),

  BANNER("minecraft:banner", 575),

  BANNER_PATTERN("minecraft:banner_pattern", 718),

  BARREL("minecraft:barrel", -203),

  BARRIER("minecraft:barrier", -161),

  BASALT("minecraft:basalt", -234),

  BAT_SPAWN_EGG("minecraft:bat_spawn_egg", 456),

  BEACON("minecraft:beacon", 138),

  BED("minecraft:bed", 421),

  BEDROCK("minecraft:bedrock", 7),

  BEE_NEST("minecraft:bee_nest", -218),

  BEE_SPAWN_EGG("minecraft:bee_spawn_egg", 497),

  BEEF("minecraft:beef", 274),

  BEEHIVE("minecraft:beehive", -219),

  BEETROOT("minecraft:beetroot", 286),

  BEETROOT_SEEDS("minecraft:beetroot_seeds", 296),

  BEETROOT_SOUP("minecraft:beetroot_soup", 287),

  BELL("minecraft:bell", -206),

  BIG_DRIPLEAF("minecraft:big_dripleaf", -323),

  BIRCH_BOAT("minecraft:birch_boat", 379),

  BIRCH_BUTTON("minecraft:birch_button", -141),

  BIRCH_CHEST_BOAT("minecraft:birch_chest_boat", 647),

  BIRCH_DOOR("minecraft:birch_door", 562),

  BIRCH_FENCE("minecraft:birch_fence", -576),

  BIRCH_FENCE_GATE("minecraft:birch_fence_gate", 184),

  BIRCH_HANGING_SIGN("minecraft:birch_hanging_sign", -502),

  BIRCH_LOG("minecraft:birch_log", -570),

  BIRCH_PLANKS("minecraft:birch_planks", -740),

  BIRCH_PRESSURE_PLATE("minecraft:birch_pressure_plate", -151),

  BIRCH_SIGN("minecraft:birch_sign", 585),

  BIRCH_STAIRS("minecraft:birch_stairs", 135),

  BIRCH_STANDING_SIGN("minecraft:birch_standing_sign", -186),

  BIRCH_TRAPDOOR("minecraft:birch_trapdoor", -146),

  BIRCH_WALL_SIGN("minecraft:birch_wall_sign", -187),

  BLACK_CANDLE("minecraft:black_candle", -428),

  BLACK_CANDLE_CAKE("minecraft:black_candle_cake", -445),

  BLACK_CARPET("minecraft:black_carpet", -611),

  BLACK_CONCRETE("minecraft:black_concrete", -642),

  BLACK_CONCRETE_POWDER("minecraft:black_concrete_powder", -723),

  BLACK_DYE("minecraft:black_dye", 398),

  BLACK_GLAZED_TERRACOTTA("minecraft:black_glazed_terracotta", 235),

  BLACK_SHULKER_BOX("minecraft:black_shulker_box", -627),

  BLACK_STAINED_GLASS("minecraft:black_stained_glass", -687),

  BLACK_STAINED_GLASS_PANE("minecraft:black_stained_glass_pane", -657),

  BLACK_TERRACOTTA("minecraft:black_terracotta", -738),

  BLACK_WOOL("minecraft:black_wool", -554),

  BLACKSTONE("minecraft:blackstone", -273),

  BLACKSTONE_DOUBLE_SLAB("minecraft:blackstone_double_slab", -283),

  BLACKSTONE_SLAB("minecraft:blackstone_slab", -282),

  BLACKSTONE_STAIRS("minecraft:blackstone_stairs", -276),

  BLACKSTONE_WALL("minecraft:blackstone_wall", -277),

  BLADE_POTTERY_SHERD("minecraft:blade_pottery_sherd", 667),

  BLAST_FURNACE("minecraft:blast_furnace", -196),

  BLAZE_POWDER("minecraft:blaze_powder", 432),

  BLAZE_ROD("minecraft:blaze_rod", 426),

  BLAZE_SPAWN_EGG("minecraft:blaze_spawn_egg", 459),

  BLEACH("minecraft:bleach", 604),

  BLUE_CANDLE("minecraft:blue_candle", -424),

  BLUE_CANDLE_CAKE("minecraft:blue_candle_cake", -441),

  BLUE_CARPET("minecraft:blue_carpet", -607),

  BLUE_CONCRETE("minecraft:blue_concrete", -638),

  BLUE_CONCRETE_POWDER("minecraft:blue_concrete_powder", -719),

  BLUE_DYE("minecraft:blue_dye", 402),

  BLUE_GLAZED_TERRACOTTA("minecraft:blue_glazed_terracotta", 231),

  BLUE_ICE("minecraft:blue_ice", -11),

  BLUE_SHULKER_BOX("minecraft:blue_shulker_box", -623),

  BLUE_STAINED_GLASS("minecraft:blue_stained_glass", -683),

  BLUE_STAINED_GLASS_PANE("minecraft:blue_stained_glass_pane", -653),

  BLUE_TERRACOTTA("minecraft:blue_terracotta", -734),

  BLUE_WOOL("minecraft:blue_wool", -563),

  BOAT("minecraft:boat", 716),

  BONE("minecraft:bone", 418),

  BONE_BLOCK("minecraft:bone_block", 216),

  BONE_MEAL("minecraft:bone_meal", 414),

  BOOK("minecraft:book", 390),

  BOOKSHELF("minecraft:bookshelf", 47),

  BORDER_BLOCK("minecraft:border_block", 212),

  BORDURE_INDENTED_BANNER_PATTERN("minecraft:bordure_indented_banner_pattern", 594),

  BOW("minecraft:bow", 303),

  BOWL("minecraft:bowl", 324),

  BRAIN_CORAL("minecraft:brain_coral", -581),

  BREAD("minecraft:bread", 262),

  BREWER_POTTERY_SHERD("minecraft:brewer_pottery_sherd", 668),

  BREWING_STAND("minecraft:brewing_stand", 434),

  BRICK("minecraft:brick", 386),

  BRICK_BLOCK("minecraft:brick_block", 45),

  BRICK_STAIRS("minecraft:brick_stairs", 108),

  BROWN_CANDLE("minecraft:brown_candle", -425),

  BROWN_CANDLE_CAKE("minecraft:brown_candle_cake", -442),

  BROWN_CARPET("minecraft:brown_carpet", -608),

  BROWN_CONCRETE("minecraft:brown_concrete", -639),

  BROWN_CONCRETE_POWDER("minecraft:brown_concrete_powder", -720),

  BROWN_DYE("minecraft:brown_dye", 401),

  BROWN_GLAZED_TERRACOTTA("minecraft:brown_glazed_terracotta", 232),

  BROWN_MUSHROOM("minecraft:brown_mushroom", 39),

  BROWN_MUSHROOM_BLOCK("minecraft:brown_mushroom_block", 99),

  BROWN_SHULKER_BOX("minecraft:brown_shulker_box", -624),

  BROWN_STAINED_GLASS("minecraft:brown_stained_glass", -684),

  BROWN_STAINED_GLASS_PANE("minecraft:brown_stained_glass_pane", -654),

  BROWN_TERRACOTTA("minecraft:brown_terracotta", -735),

  BROWN_WOOL("minecraft:brown_wool", -555),

  BRUSH("minecraft:brush", 684),

  BUBBLE_COLUMN("minecraft:bubble_column", -160),

  BUBBLE_CORAL("minecraft:bubble_coral", -582),

  BUCKET("minecraft:bucket", 363),

  BUDDING_AMETHYST("minecraft:budding_amethyst", -328),

  BURN_POTTERY_SHERD("minecraft:burn_pottery_sherd", 669),

  CACTUS("minecraft:cactus", 81),

  CAKE("minecraft:cake", 420),

  CALCITE("minecraft:calcite", -326),

  CALIBRATED_SCULK_SENSOR("minecraft:calibrated_sculk_sensor", -580),

  CAMEL_SPAWN_EGG("minecraft:camel_spawn_egg", 663),

  CAMERA("minecraft:camera", 601),

  CAMPFIRE("minecraft:campfire", 597),

  CANDLE("minecraft:candle", -412),

  CANDLE_CAKE("minecraft:candle_cake", -429),

  CARPET("minecraft:carpet", 705),

  CARROT("minecraft:carrot", 280),

  CARROT_ON_A_STICK("minecraft:carrot_on_a_stick", 525),

  CARROTS("minecraft:carrots", 141),

  CARTOGRAPHY_TABLE("minecraft:cartography_table", -200),

  CARVED_PUMPKIN("minecraft:carved_pumpkin", -155),

  CAT_SPAWN_EGG("minecraft:cat_spawn_egg", 491),

  CAULDRON("minecraft:cauldron", 435),

  CAVE_SPIDER_SPAWN_EGG("minecraft:cave_spider_spawn_egg", 460),

  CAVE_VINES("minecraft:cave_vines", -322),

  CAVE_VINES_BODY_WITH_BERRIES("minecraft:cave_vines_body_with_berries", -375),

  CAVE_VINES_HEAD_WITH_BERRIES("minecraft:cave_vines_head_with_berries", -376),

  CHAIN("minecraft:chain", 627),

  CHAIN_COMMAND_BLOCK("minecraft:chain_command_block", 189),

  CHAINMAIL_BOOTS("minecraft:chainmail_boots", 345),

  CHAINMAIL_CHESTPLATE("minecraft:chainmail_chestplate", 343),

  CHAINMAIL_HELMET("minecraft:chainmail_helmet", 342),

  CHAINMAIL_LEGGINGS("minecraft:chainmail_leggings", 344),

  CHARCOAL("minecraft:charcoal", 306),

  CHEMICAL_HEAT("minecraft:chemical_heat", 192),

  CHEMISTRY_TABLE("minecraft:chemistry_table", 238),

  CHERRY_BOAT("minecraft:cherry_boat", 657),

  CHERRY_BUTTON("minecraft:cherry_button", -530),

  CHERRY_CHEST_BOAT("minecraft:cherry_chest_boat", 658),

  CHERRY_DOOR("minecraft:cherry_door", -531),

  CHERRY_DOUBLE_SLAB("minecraft:cherry_double_slab", -540),

  CHERRY_FENCE("minecraft:cherry_fence", -532),

  CHERRY_FENCE_GATE("minecraft:cherry_fence_gate", -533),

  CHERRY_HANGING_SIGN("minecraft:cherry_hanging_sign", -534),

  CHERRY_LEAVES("minecraft:cherry_leaves", -548),

  CHERRY_LOG("minecraft:cherry_log", -536),

  CHERRY_PLANKS("minecraft:cherry_planks", -537),

  CHERRY_PRESSURE_PLATE("minecraft:cherry_pressure_plate", -538),

  CHERRY_SAPLING("minecraft:cherry_sapling", -547),

  CHERRY_SIGN("minecraft:cherry_sign", 659),

  CHERRY_SLAB("minecraft:cherry_slab", -539),

  CHERRY_STAIRS("minecraft:cherry_stairs", -541),

  CHERRY_STANDING_SIGN("minecraft:cherry_standing_sign", -542),

  CHERRY_TRAPDOOR("minecraft:cherry_trapdoor", -543),

  CHERRY_WALL_SIGN("minecraft:cherry_wall_sign", -544),

  CHERRY_WOOD("minecraft:cherry_wood", -546),

  CHEST("minecraft:chest", 54),

  CHEST_BOAT("minecraft:chest_boat", 653),

  CHEST_MINECART("minecraft:chest_minecart", 392),

  CHICKEN("minecraft:chicken", 276),

  CHICKEN_SPAWN_EGG("minecraft:chicken_spawn_egg", 438),

  CHISELED_BOOKSHELF("minecraft:chiseled_bookshelf", -526),

  CHISELED_COPPER("minecraft:chiseled_copper", -760),

  CHISELED_DEEPSLATE("minecraft:chiseled_deepslate", -395),

  CHISELED_NETHER_BRICKS("minecraft:chiseled_nether_bricks", -302),

  CHISELED_POLISHED_BLACKSTONE("minecraft:chiseled_polished_blackstone", -279),

  CHISELED_TUFF("minecraft:chiseled_tuff", -753),

  CHISELED_TUFF_BRICKS("minecraft:chiseled_tuff_bricks", -759),

  CHORUS_FLOWER("minecraft:chorus_flower", 200),

  CHORUS_FRUIT("minecraft:chorus_fruit", 566),

  CHORUS_PLANT("minecraft:chorus_plant", 240),

  CLAY("minecraft:clay", 82),

  CLAY_BALL("minecraft:clay_ball", 387),

  CLIENT_REQUEST_PLACEHOLDER_BLOCK("minecraft:client_request_placeholder_block", -465),

  CLOCK("minecraft:clock", 396),

  COAL("minecraft:coal", 305),

  COAL_BLOCK("minecraft:coal_block", 173),

  COAL_ORE("minecraft:coal_ore", 16),

  COAST_ARMOR_TRIM_SMITHING_TEMPLATE("minecraft:coast_armor_trim_smithing_template", 688),

  COBBLED_DEEPSLATE("minecraft:cobbled_deepslate", -379),

  COBBLED_DEEPSLATE_DOUBLE_SLAB("minecraft:cobbled_deepslate_double_slab", -396),

  COBBLED_DEEPSLATE_SLAB("minecraft:cobbled_deepslate_slab", -380),

  COBBLED_DEEPSLATE_STAIRS("minecraft:cobbled_deepslate_stairs", -381),

  COBBLED_DEEPSLATE_WALL("minecraft:cobbled_deepslate_wall", -382),

  COBBLESTONE("minecraft:cobblestone", 4),

  COBBLESTONE_WALL("minecraft:cobblestone_wall", 139),

  COCOA("minecraft:cocoa", 127),

  COCOA_BEANS("minecraft:cocoa_beans", 415),

  COD("minecraft:cod", 265),

  COD_BUCKET("minecraft:cod_bucket", 367),

  COD_SPAWN_EGG("minecraft:cod_spawn_egg", 483),

  COLORED_TORCH_BP("minecraft:colored_torch_bp", 204),

  COLORED_TORCH_RG("minecraft:colored_torch_rg", 202),

  COMMAND_BLOCK("minecraft:command_block", 137),

  COMMAND_BLOCK_MINECART("minecraft:command_block_minecart", 571),

  COMPARATOR("minecraft:comparator", 530),

  COMPASS("minecraft:compass", 394),

  COMPOSTER("minecraft:composter", -213),

  COMPOUND("minecraft:compound", 602),

  CONCRETE("minecraft:concrete", 711),

  CONCRETE_POWDER("minecraft:concrete_powder", 712),

  CONDUIT("minecraft:conduit", -157),

  COOKED_BEEF("minecraft:cooked_beef", 275),

  COOKED_CHICKEN("minecraft:cooked_chicken", 277),

  COOKED_COD("minecraft:cooked_cod", 269),

  COOKED_MUTTON("minecraft:cooked_mutton", 559),

  COOKED_PORKCHOP("minecraft:cooked_porkchop", 264),

  COOKED_RABBIT("minecraft:cooked_rabbit", 290),

  COOKED_SALMON("minecraft:cooked_salmon", 270),

  COOKIE("minecraft:cookie", 272),

  COPPER_BLOCK("minecraft:copper_block", -340),

  COPPER_BULB("minecraft:copper_bulb", -776),

  COPPER_DOOR("minecraft:copper_door", -784),

  COPPER_GRATE("minecraft:copper_grate", -768),

  COPPER_INGOT("minecraft:copper_ingot", 512),

  COPPER_ORE("minecraft:copper_ore", -311),

  COPPER_TRAPDOOR("minecraft:copper_trapdoor", -792),

  CORAL("minecraft:coral", 709),

  CORAL_BLOCK("minecraft:coral_block", -132),

  CORAL_FAN("minecraft:coral_fan", -133),

  CORAL_FAN_DEAD("minecraft:coral_fan_dead", -134),

  CORAL_FAN_HANG("minecraft:coral_fan_hang", -135),

  CORAL_FAN_HANG2("minecraft:coral_fan_hang2", -136),

  CORAL_FAN_HANG3("minecraft:coral_fan_hang3", -137),

  COW_SPAWN_EGG("minecraft:cow_spawn_egg", 439),

  CRACKED_DEEPSLATE_BRICKS("minecraft:cracked_deepslate_bricks", -410),

  CRACKED_DEEPSLATE_TILES("minecraft:cracked_deepslate_tiles", -409),

  CRACKED_NETHER_BRICKS("minecraft:cracked_nether_bricks", -303),

  CRACKED_POLISHED_BLACKSTONE_BRICKS("minecraft:cracked_polished_blackstone_bricks", -280),

  CRAFTER("minecraft:crafter", -313),

  CRAFTING_TABLE("minecraft:crafting_table", 58),

  CREEPER_BANNER_PATTERN("minecraft:creeper_banner_pattern", 590),

  CREEPER_SPAWN_EGG("minecraft:creeper_spawn_egg", 444),

  CRIMSON_BUTTON("minecraft:crimson_button", -260),

  CRIMSON_DOOR("minecraft:crimson_door", 624),

  CRIMSON_DOUBLE_SLAB("minecraft:crimson_double_slab", -266),

  CRIMSON_FENCE("minecraft:crimson_fence", -256),

  CRIMSON_FENCE_GATE("minecraft:crimson_fence_gate", -258),

  CRIMSON_FUNGUS("minecraft:crimson_fungus", -228),

  CRIMSON_HANGING_SIGN("minecraft:crimson_hanging_sign", -506),

  CRIMSON_HYPHAE("minecraft:crimson_hyphae", -299),

  CRIMSON_NYLIUM("minecraft:crimson_nylium", -232),

  CRIMSON_PLANKS("minecraft:crimson_planks", -242),

  CRIMSON_PRESSURE_PLATE("minecraft:crimson_pressure_plate", -262),

  CRIMSON_ROOTS("minecraft:crimson_roots", -223),

  CRIMSON_SIGN("minecraft:crimson_sign", 622),

  CRIMSON_SLAB("minecraft:crimson_slab", -264),

  CRIMSON_STAIRS("minecraft:crimson_stairs", -254),

  CRIMSON_STANDING_SIGN("minecraft:crimson_standing_sign", -250),

  CRIMSON_STEM("minecraft:crimson_stem", -225),

  CRIMSON_TRAPDOOR("minecraft:crimson_trapdoor", -246),

  CRIMSON_WALL_SIGN("minecraft:crimson_wall_sign", -252),

  CROSSBOW("minecraft:crossbow", 583),

  CRYING_OBSIDIAN("minecraft:crying_obsidian", -289),

  CUT_COPPER("minecraft:cut_copper", -347),

  CUT_COPPER_SLAB("minecraft:cut_copper_slab", -361),

  CUT_COPPER_STAIRS("minecraft:cut_copper_stairs", -354),

  CYAN_CANDLE("minecraft:cyan_candle", -422),

  CYAN_CANDLE_CAKE("minecraft:cyan_candle_cake", -439),

  CYAN_CARPET("minecraft:cyan_carpet", -605),

  CYAN_CONCRETE("minecraft:cyan_concrete", -636),

  CYAN_CONCRETE_POWDER("minecraft:cyan_concrete_powder", -717),

  CYAN_DYE("minecraft:cyan_dye", 404),

  CYAN_GLAZED_TERRACOTTA("minecraft:cyan_glazed_terracotta", 229),

  CYAN_SHULKER_BOX("minecraft:cyan_shulker_box", -621),

  CYAN_STAINED_GLASS("minecraft:cyan_stained_glass", -681),

  CYAN_STAINED_GLASS_PANE("minecraft:cyan_stained_glass_pane", -651),

  CYAN_TERRACOTTA("minecraft:cyan_terracotta", -732),

  CYAN_WOOL("minecraft:cyan_wool", -561),

  DANGER_POTTERY_SHERD("minecraft:danger_pottery_sherd", 670),

  DARK_OAK_BOAT("minecraft:dark_oak_boat", 383),

  DARK_OAK_BUTTON("minecraft:dark_oak_button", -142),

  DARK_OAK_CHEST_BOAT("minecraft:dark_oak_chest_boat", 651),

  DARK_OAK_DOOR("minecraft:dark_oak_door", 565),

  DARK_OAK_FENCE("minecraft:dark_oak_fence", -577),

  DARK_OAK_FENCE_GATE("minecraft:dark_oak_fence_gate", 186),

  DARK_OAK_HANGING_SIGN("minecraft:dark_oak_hanging_sign", -505),

  DARK_OAK_LOG("minecraft:dark_oak_log", -572),

  DARK_OAK_PLANKS("minecraft:dark_oak_planks", -743),

  DARK_OAK_PRESSURE_PLATE("minecraft:dark_oak_pressure_plate", -152),

  DARK_OAK_SIGN("minecraft:dark_oak_sign", 588),

  DARK_OAK_STAIRS("minecraft:dark_oak_stairs", 164),

  DARK_OAK_TRAPDOOR("minecraft:dark_oak_trapdoor", -147),

  DARK_PRISMARINE_STAIRS("minecraft:dark_prismarine_stairs", -3),

  DARKOAK_STANDING_SIGN("minecraft:darkoak_standing_sign", -192),

  DARKOAK_WALL_SIGN("minecraft:darkoak_wall_sign", -193),

  DAYLIGHT_DETECTOR("minecraft:daylight_detector", 151),

  DAYLIGHT_DETECTOR_INVERTED("minecraft:daylight_detector_inverted", 178),

  DEAD_BRAIN_CORAL("minecraft:dead_brain_coral", -586),

  DEAD_BUBBLE_CORAL("minecraft:dead_bubble_coral", -587),

  DEAD_FIRE_CORAL("minecraft:dead_fire_coral", -588),

  DEAD_HORN_CORAL("minecraft:dead_horn_coral", -589),

  DEAD_TUBE_CORAL("minecraft:dead_tube_coral", -585),

  DEADBUSH("minecraft:deadbush", 32),

  DECORATED_POT("minecraft:decorated_pot", -551),

  DEEPSLATE("minecraft:deepslate", -378),

  DEEPSLATE_BRICK_DOUBLE_SLAB("minecraft:deepslate_brick_double_slab", -399),

  DEEPSLATE_BRICK_SLAB("minecraft:deepslate_brick_slab", -392),

  DEEPSLATE_BRICK_STAIRS("minecraft:deepslate_brick_stairs", -393),

  DEEPSLATE_BRICK_WALL("minecraft:deepslate_brick_wall", -394),

  DEEPSLATE_BRICKS("minecraft:deepslate_bricks", -391),

  DEEPSLATE_COAL_ORE("minecraft:deepslate_coal_ore", -406),

  DEEPSLATE_COPPER_ORE("minecraft:deepslate_copper_ore", -408),

  DEEPSLATE_DIAMOND_ORE("minecraft:deepslate_diamond_ore", -405),

  DEEPSLATE_EMERALD_ORE("minecraft:deepslate_emerald_ore", -407),

  DEEPSLATE_GOLD_ORE("minecraft:deepslate_gold_ore", -402),

  DEEPSLATE_IRON_ORE("minecraft:deepslate_iron_ore", -401),

  DEEPSLATE_LAPIS_ORE("minecraft:deepslate_lapis_ore", -400),

  DEEPSLATE_REDSTONE_ORE("minecraft:deepslate_redstone_ore", -403),

  DEEPSLATE_TILE_DOUBLE_SLAB("minecraft:deepslate_tile_double_slab", -398),

  DEEPSLATE_TILE_SLAB("minecraft:deepslate_tile_slab", -388),

  DEEPSLATE_TILE_STAIRS("minecraft:deepslate_tile_stairs", -389),

  DEEPSLATE_TILE_WALL("minecraft:deepslate_tile_wall", -390),

  DEEPSLATE_TILES("minecraft:deepslate_tiles", -387),

  DENY("minecraft:deny", 211),

  DETECTOR_RAIL("minecraft:detector_rail", 28),

  DIAMOND("minecraft:diamond", 307),

  DIAMOND_AXE("minecraft:diamond_axe", 322),

  DIAMOND_BLOCK("minecraft:diamond_block", 57),

  DIAMOND_BOOTS("minecraft:diamond_boots", 353),

  DIAMOND_CHESTPLATE("minecraft:diamond_chestplate", 351),

  DIAMOND_HELMET("minecraft:diamond_helmet", 350),

  DIAMOND_HOE("minecraft:diamond_hoe", 335),

  DIAMOND_HORSE_ARMOR("minecraft:diamond_horse_armor", 541),

  DIAMOND_LEGGINGS("minecraft:diamond_leggings", 352),

  DIAMOND_ORE("minecraft:diamond_ore", 56),

  DIAMOND_PICKAXE("minecraft:diamond_pickaxe", 321),

  DIAMOND_SHOVEL("minecraft:diamond_shovel", 320),

  DIAMOND_SWORD("minecraft:diamond_sword", 319),

  DIORITE("minecraft:diorite", -592),

  DIORITE_STAIRS("minecraft:diorite_stairs", -170),

  DIRT("minecraft:dirt", 3),

  DIRT_WITH_ROOTS("minecraft:dirt_with_roots", -318),

  DISC_FRAGMENT_5("minecraft:disc_fragment_5", 645),

  DISPENSER("minecraft:dispenser", 23),

  DOLPHIN_SPAWN_EGG("minecraft:dolphin_spawn_egg", 487),

  DONKEY_SPAWN_EGG("minecraft:donkey_spawn_egg", 468),

  DOUBLE_CUT_COPPER_SLAB("minecraft:double_cut_copper_slab", -368),

  DOUBLE_PLANT("minecraft:double_plant", 175),

  DOUBLE_STONE_BLOCK_SLAB("minecraft:double_stone_block_slab", 43),

  DOUBLE_STONE_BLOCK_SLAB2("minecraft:double_stone_block_slab2", 181),

  DOUBLE_STONE_BLOCK_SLAB3("minecraft:double_stone_block_slab3", -167),

  DOUBLE_STONE_BLOCK_SLAB4("minecraft:double_stone_block_slab4", -168),

  DOUBLE_WOODEN_SLAB("minecraft:double_wooden_slab", 157),

  DRAGON_BREATH("minecraft:dragon_breath", 568),

  DRAGON_EGG("minecraft:dragon_egg", 122),

  DRIED_KELP("minecraft:dried_kelp", 271),

  DRIED_KELP_BLOCK("minecraft:dried_kelp_block", -139),

  DRIPSTONE_BLOCK("minecraft:dripstone_block", -317),

  DROPPER("minecraft:dropper", 125),

  DROWNED_SPAWN_EGG("minecraft:drowned_spawn_egg", 486),

  DUNE_ARMOR_TRIM_SMITHING_TEMPLATE("minecraft:dune_armor_trim_smithing_template", 687),

  DYE("minecraft:dye", 717),

  ECHO_SHARD("minecraft:echo_shard", 655),

  EGG("minecraft:egg", 393),

  ELDER_GUARDIAN_SPAWN_EGG("minecraft:elder_guardian_spawn_egg", 474),

  ELEMENT_0("minecraft:element_0", 36),

  ELEMENT_1("minecraft:element_1", -12),

  ELEMENT_10("minecraft:element_10", -21),

  ELEMENT_100("minecraft:element_100", -111),

  ELEMENT_101("minecraft:element_101", -112),

  ELEMENT_102("minecraft:element_102", -113),

  ELEMENT_103("minecraft:element_103", -114),

  ELEMENT_104("minecraft:element_104", -115),

  ELEMENT_105("minecraft:element_105", -116),

  ELEMENT_106("minecraft:element_106", -117),

  ELEMENT_107("minecraft:element_107", -118),

  ELEMENT_108("minecraft:element_108", -119),

  ELEMENT_109("minecraft:element_109", -120),

  ELEMENT_11("minecraft:element_11", -22),

  ELEMENT_110("minecraft:element_110", -121),

  ELEMENT_111("minecraft:element_111", -122),

  ELEMENT_112("minecraft:element_112", -123),

  ELEMENT_113("minecraft:element_113", -124),

  ELEMENT_114("minecraft:element_114", -125),

  ELEMENT_115("minecraft:element_115", -126),

  ELEMENT_116("minecraft:element_116", -127),

  ELEMENT_117("minecraft:element_117", -128),

  ELEMENT_118("minecraft:element_118", -129),

  ELEMENT_12("minecraft:element_12", -23),

  ELEMENT_13("minecraft:element_13", -24),

  ELEMENT_14("minecraft:element_14", -25),

  ELEMENT_15("minecraft:element_15", -26),

  ELEMENT_16("minecraft:element_16", -27),

  ELEMENT_17("minecraft:element_17", -28),

  ELEMENT_18("minecraft:element_18", -29),

  ELEMENT_19("minecraft:element_19", -30),

  ELEMENT_2("minecraft:element_2", -13),

  ELEMENT_20("minecraft:element_20", -31),

  ELEMENT_21("minecraft:element_21", -32),

  ELEMENT_22("minecraft:element_22", -33),

  ELEMENT_23("minecraft:element_23", -34),

  ELEMENT_24("minecraft:element_24", -35),

  ELEMENT_25("minecraft:element_25", -36),

  ELEMENT_26("minecraft:element_26", -37),

  ELEMENT_27("minecraft:element_27", -38),

  ELEMENT_28("minecraft:element_28", -39),

  ELEMENT_29("minecraft:element_29", -40),

  ELEMENT_3("minecraft:element_3", -14),

  ELEMENT_30("minecraft:element_30", -41),

  ELEMENT_31("minecraft:element_31", -42),

  ELEMENT_32("minecraft:element_32", -43),

  ELEMENT_33("minecraft:element_33", -44),

  ELEMENT_34("minecraft:element_34", -45),

  ELEMENT_35("minecraft:element_35", -46),

  ELEMENT_36("minecraft:element_36", -47),

  ELEMENT_37("minecraft:element_37", -48),

  ELEMENT_38("minecraft:element_38", -49),

  ELEMENT_39("minecraft:element_39", -50),

  ELEMENT_4("minecraft:element_4", -15),

  ELEMENT_40("minecraft:element_40", -51),

  ELEMENT_41("minecraft:element_41", -52),

  ELEMENT_42("minecraft:element_42", -53),

  ELEMENT_43("minecraft:element_43", -54),

  ELEMENT_44("minecraft:element_44", -55),

  ELEMENT_45("minecraft:element_45", -56),

  ELEMENT_46("minecraft:element_46", -57),

  ELEMENT_47("minecraft:element_47", -58),

  ELEMENT_48("minecraft:element_48", -59),

  ELEMENT_49("minecraft:element_49", -60),

  ELEMENT_5("minecraft:element_5", -16),

  ELEMENT_50("minecraft:element_50", -61),

  ELEMENT_51("minecraft:element_51", -62),

  ELEMENT_52("minecraft:element_52", -63),

  ELEMENT_53("minecraft:element_53", -64),

  ELEMENT_54("minecraft:element_54", -65),

  ELEMENT_55("minecraft:element_55", -66),

  ELEMENT_56("minecraft:element_56", -67),

  ELEMENT_57("minecraft:element_57", -68),

  ELEMENT_58("minecraft:element_58", -69),

  ELEMENT_59("minecraft:element_59", -70),

  ELEMENT_6("minecraft:element_6", -17),

  ELEMENT_60("minecraft:element_60", -71),

  ELEMENT_61("minecraft:element_61", -72),

  ELEMENT_62("minecraft:element_62", -73),

  ELEMENT_63("minecraft:element_63", -74),

  ELEMENT_64("minecraft:element_64", -75),

  ELEMENT_65("minecraft:element_65", -76),

  ELEMENT_66("minecraft:element_66", -77),

  ELEMENT_67("minecraft:element_67", -78),

  ELEMENT_68("minecraft:element_68", -79),

  ELEMENT_69("minecraft:element_69", -80),

  ELEMENT_7("minecraft:element_7", -18),

  ELEMENT_70("minecraft:element_70", -81),

  ELEMENT_71("minecraft:element_71", -82),

  ELEMENT_72("minecraft:element_72", -83),

  ELEMENT_73("minecraft:element_73", -84),

  ELEMENT_74("minecraft:element_74", -85),

  ELEMENT_75("minecraft:element_75", -86),

  ELEMENT_76("minecraft:element_76", -87),

  ELEMENT_77("minecraft:element_77", -88),

  ELEMENT_78("minecraft:element_78", -89),

  ELEMENT_79("minecraft:element_79", -90),

  ELEMENT_8("minecraft:element_8", -19),

  ELEMENT_80("minecraft:element_80", -91),

  ELEMENT_81("minecraft:element_81", -92),

  ELEMENT_82("minecraft:element_82", -93),

  ELEMENT_83("minecraft:element_83", -94),

  ELEMENT_84("minecraft:element_84", -95),

  ELEMENT_85("minecraft:element_85", -96),

  ELEMENT_86("minecraft:element_86", -97),

  ELEMENT_87("minecraft:element_87", -98),

  ELEMENT_88("minecraft:element_88", -99),

  ELEMENT_89("minecraft:element_89", -100),

  ELEMENT_9("minecraft:element_9", -20),

  ELEMENT_90("minecraft:element_90", -101),

  ELEMENT_91("minecraft:element_91", -102),

  ELEMENT_92("minecraft:element_92", -103),

  ELEMENT_93("minecraft:element_93", -104),

  ELEMENT_94("minecraft:element_94", -105),

  ELEMENT_95("minecraft:element_95", -106),

  ELEMENT_96("minecraft:element_96", -107),

  ELEMENT_97("minecraft:element_97", -108),

  ELEMENT_98("minecraft:element_98", -109),

  ELEMENT_99("minecraft:element_99", -110),

  ELYTRA("minecraft:elytra", 572),

  EMERALD("minecraft:emerald", 520),

  EMERALD_BLOCK("minecraft:emerald_block", 133),

  EMERALD_ORE("minecraft:emerald_ore", 129),

  EMPTY_MAP("minecraft:empty_map", 523),

  ENCHANTED_BOOK("minecraft:enchanted_book", 529),

  ENCHANTED_GOLDEN_APPLE("minecraft:enchanted_golden_apple", 260),

  ENCHANTING_TABLE("minecraft:enchanting_table", 116),

  END_BRICK_STAIRS("minecraft:end_brick_stairs", -178),

  END_BRICKS("minecraft:end_bricks", 206),

  END_CRYSTAL("minecraft:end_crystal", 720),

  END_GATEWAY("minecraft:end_gateway", 209),

  END_PORTAL("minecraft:end_portal", 119),

  END_PORTAL_FRAME("minecraft:end_portal_frame", 120),

  END_ROD("minecraft:end_rod", 208),

  END_STONE("minecraft:end_stone", 121),

  ENDER_CHEST("minecraft:ender_chest", 130),

  ENDER_DRAGON_SPAWN_EGG("minecraft:ender_dragon_spawn_egg", 509),

  ENDER_EYE("minecraft:ender_eye", 436),

  ENDER_PEARL("minecraft:ender_pearl", 425),

  ENDERMAN_SPAWN_EGG("minecraft:enderman_spawn_egg", 445),

  ENDERMITE_SPAWN_EGG("minecraft:endermite_spawn_egg", 463),

  EVOKER_SPAWN_EGG("minecraft:evoker_spawn_egg", 478),

  EXPERIENCE_BOTTLE("minecraft:experience_bottle", 516),

  EXPLORER_POTTERY_SHERD("minecraft:explorer_pottery_sherd", 671),

  EXPOSED_CHISELED_COPPER("minecraft:exposed_chiseled_copper", -761),

  EXPOSED_COPPER("minecraft:exposed_copper", -341),

  EXPOSED_COPPER_BULB("minecraft:exposed_copper_bulb", -777),

  EXPOSED_COPPER_DOOR("minecraft:exposed_copper_door", -785),

  EXPOSED_COPPER_GRATE("minecraft:exposed_copper_grate", -769),

  EXPOSED_COPPER_TRAPDOOR("minecraft:exposed_copper_trapdoor", -793),

  EXPOSED_CUT_COPPER("minecraft:exposed_cut_copper", -348),

  EXPOSED_CUT_COPPER_SLAB("minecraft:exposed_cut_copper_slab", -362),

  EXPOSED_CUT_COPPER_STAIRS("minecraft:exposed_cut_copper_stairs", -355),

  EXPOSED_DOUBLE_CUT_COPPER_SLAB("minecraft:exposed_double_cut_copper_slab", -369),

  EYE_ARMOR_TRIM_SMITHING_TEMPLATE("minecraft:eye_armor_trim_smithing_template", 691),

  FARMLAND("minecraft:farmland", 60),

  FEATHER("minecraft:feather", 330),

  FENCE("minecraft:fence", 707),

  FENCE_GATE("minecraft:fence_gate", 107),

  FERMENTED_SPIDER_EYE("minecraft:fermented_spider_eye", 431),

  FIELD_MASONED_BANNER_PATTERN("minecraft:field_masoned_banner_pattern", 593),

  FILLED_MAP("minecraft:filled_map", 423),

  FIRE("minecraft:fire", 51),

  FIRE_CHARGE("minecraft:fire_charge", 517),

  FIRE_CORAL("minecraft:fire_coral", -583),

  FIREWORK_ROCKET("minecraft:firework_rocket", 527),

  FIREWORK_STAR("minecraft:firework_star", 528),

  FISHING_ROD("minecraft:fishing_rod", 395),

  FLETCHING_TABLE("minecraft:fletching_table", -201),

  FLINT("minecraft:flint", 359),

  FLINT_AND_STEEL("minecraft:flint_and_steel", 302),

  FLOWER_BANNER_PATTERN("minecraft:flower_banner_pattern", 589),

  FLOWER_POT("minecraft:flower_pot", 522),

  FLOWERING_AZALEA("minecraft:flowering_azalea", -338),

  FLOWING_LAVA("minecraft:flowing_lava", 10),

  FLOWING_WATER("minecraft:flowing_water", 8),

  FOX_SPAWN_EGG("minecraft:fox_spawn_egg", 493),

  FRAME("minecraft:frame", 521),

  FRIEND_POTTERY_SHERD("minecraft:friend_pottery_sherd", 672),

  FROG_SPAWN("minecraft:frog_spawn", -468),

  FROG_SPAWN_EGG("minecraft:frog_spawn_egg", 636),

  FROSTED_ICE("minecraft:frosted_ice", 207),

  FURNACE("minecraft:furnace", 61),

  GHAST_SPAWN_EGG("minecraft:ghast_spawn_egg", 457),

  GHAST_TEAR("minecraft:ghast_tear", 427),

  GILDED_BLACKSTONE("minecraft:gilded_blackstone", -281),

  GLASS("minecraft:glass", 20),

  GLASS_BOTTLE("minecraft:glass_bottle", 430),

  GLASS_PANE("minecraft:glass_pane", 102),

  GLISTERING_MELON_SLICE("minecraft:glistering_melon_slice", 437),

  GLOBE_BANNER_PATTERN("minecraft:globe_banner_pattern", 596),

  GLOW_BERRIES("minecraft:glow_berries", 721),

  GLOW_FRAME("minecraft:glow_frame", 631),

  GLOW_INK_SAC("minecraft:glow_ink_sac", 511),

  GLOW_LICHEN("minecraft:glow_lichen", -411),

  GLOW_SQUID_SPAWN_EGG("minecraft:glow_squid_spawn_egg", 506),

  GLOW_STICK("minecraft:glow_stick", 609),

  GLOWINGOBSIDIAN("minecraft:glowingobsidian", 246),

  GLOWSTONE("minecraft:glowstone", 89),

  GLOWSTONE_DUST("minecraft:glowstone_dust", 397),

  GOAT_HORN("minecraft:goat_horn", 635),

  GOAT_SPAWN_EGG("minecraft:goat_spawn_egg", 505),

  GOLD_BLOCK("minecraft:gold_block", 41),

  GOLD_INGOT("minecraft:gold_ingot", 309),

  GOLD_NUGGET("minecraft:gold_nugget", 428),

  GOLD_ORE("minecraft:gold_ore", 14),

  GOLDEN_APPLE("minecraft:golden_apple", 259),

  GOLDEN_AXE("minecraft:golden_axe", 328),

  GOLDEN_BOOTS("minecraft:golden_boots", 357),

  GOLDEN_CARROT("minecraft:golden_carrot", 284),

  GOLDEN_CHESTPLATE("minecraft:golden_chestplate", 355),

  GOLDEN_HELMET("minecraft:golden_helmet", 354),

  GOLDEN_HOE("minecraft:golden_hoe", 336),

  GOLDEN_HORSE_ARMOR("minecraft:golden_horse_armor", 540),

  GOLDEN_LEGGINGS("minecraft:golden_leggings", 356),

  GOLDEN_PICKAXE("minecraft:golden_pickaxe", 327),

  GOLDEN_RAIL("minecraft:golden_rail", 27),

  GOLDEN_SHOVEL("minecraft:golden_shovel", 326),

  GOLDEN_SWORD("minecraft:golden_sword", 325),

  GRANITE("minecraft:granite", -590),

  GRANITE_STAIRS("minecraft:granite_stairs", -169),

  GRASS("minecraft:grass", 2),

  GRASS_PATH("minecraft:grass_path", 198),

  GRAVEL("minecraft:gravel", 13),

  GRAY_CANDLE("minecraft:gray_candle", -420),

  GRAY_CANDLE_CAKE("minecraft:gray_candle_cake", -437),

  GRAY_CARPET("minecraft:gray_carpet", -603),

  GRAY_CONCRETE("minecraft:gray_concrete", -634),

  GRAY_CONCRETE_POWDER("minecraft:gray_concrete_powder", -715),

  GRAY_DYE("minecraft:gray_dye", 406),

  GRAY_GLAZED_TERRACOTTA("minecraft:gray_glazed_terracotta", 227),

  GRAY_SHULKER_BOX("minecraft:gray_shulker_box", -619),

  GRAY_STAINED_GLASS("minecraft:gray_stained_glass", -679),

  GRAY_STAINED_GLASS_PANE("minecraft:gray_stained_glass_pane", -649),

  GRAY_TERRACOTTA("minecraft:gray_terracotta", -730),

  GRAY_WOOL("minecraft:gray_wool", -553),

  GREEN_CANDLE("minecraft:green_candle", -426),

  GREEN_CANDLE_CAKE("minecraft:green_candle_cake", -443),

  GREEN_CARPET("minecraft:green_carpet", -609),

  GREEN_CONCRETE("minecraft:green_concrete", -640),

  GREEN_CONCRETE_POWDER("minecraft:green_concrete_powder", -721),

  GREEN_DYE("minecraft:green_dye", 400),

  GREEN_GLAZED_TERRACOTTA("minecraft:green_glazed_terracotta", 233),

  GREEN_SHULKER_BOX("minecraft:green_shulker_box", -625),

  GREEN_STAINED_GLASS("minecraft:green_stained_glass", -685),

  GREEN_STAINED_GLASS_PANE("minecraft:green_stained_glass_pane", -655),

  GREEN_TERRACOTTA("minecraft:green_terracotta", -736),

  GREEN_WOOL("minecraft:green_wool", -560),

  GRINDSTONE("minecraft:grindstone", -195),

  GUARDIAN_SPAWN_EGG("minecraft:guardian_spawn_egg", 464),

  GUNPOWDER("minecraft:gunpowder", 331),

  HANGING_ROOTS("minecraft:hanging_roots", -319),

  HARD_GLASS("minecraft:hard_glass", 253),

  HARD_GLASS_PANE("minecraft:hard_glass_pane", 190),

  HARD_STAINED_GLASS("minecraft:hard_stained_glass", 254),

  HARD_STAINED_GLASS_PANE("minecraft:hard_stained_glass_pane", 191),

  HARDENED_CLAY("minecraft:hardened_clay", 172),

  HAY_BLOCK("minecraft:hay_block", 170),

  HEART_OF_THE_SEA("minecraft:heart_of_the_sea", 579),

  HEART_POTTERY_SHERD("minecraft:heart_pottery_sherd", 673),

  HEARTBREAK_POTTERY_SHERD("minecraft:heartbreak_pottery_sherd", 674),

  HEAVY_WEIGHTED_PRESSURE_PLATE("minecraft:heavy_weighted_pressure_plate", 148),

  HOGLIN_SPAWN_EGG("minecraft:hoglin_spawn_egg", 499),

  HONEY_BLOCK("minecraft:honey_block", -220),

  HONEY_BOTTLE("minecraft:honey_bottle", 600),

  HONEYCOMB("minecraft:honeycomb", 599),

  HONEYCOMB_BLOCK("minecraft:honeycomb_block", -221),

  HOPPER("minecraft:hopper", 535),

  HOPPER_MINECART("minecraft:hopper_minecart", 534),

  HORN_CORAL("minecraft:horn_coral", -584),

  HORSE_SPAWN_EGG("minecraft:horse_spawn_egg", 461),

  HOST_ARMOR_TRIM_SMITHING_TEMPLATE("minecraft:host_armor_trim_smithing_template", 701),

  HOWL_POTTERY_SHERD("minecraft:howl_pottery_sherd", 675),

  HUSK_SPAWN_EGG("minecraft:husk_spawn_egg", 466),

  ICE("minecraft:ice", 79),

  ICE_BOMB("minecraft:ice_bomb", 603),

  INFESTED_DEEPSLATE("minecraft:infested_deepslate", -454),

  INFO_UPDATE("minecraft:info_update", 248),

  INFO_UPDATE2("minecraft:info_update2", 249),

  INK_SAC("minecraft:ink_sac", 416),

  INVISIBLE_BEDROCK("minecraft:invisible_bedrock", 95),

  IRON_AXE("minecraft:iron_axe", 301),

  IRON_BARS("minecraft:iron_bars", 101),

  IRON_BLOCK("minecraft:iron_block", 42),

  IRON_BOOTS("minecraft:iron_boots", 349),

  IRON_CHESTPLATE("minecraft:iron_chestplate", 347),

  IRON_DOOR("minecraft:iron_door", 375),

  IRON_GOLEM_SPAWN_EGG("minecraft:iron_golem_spawn_egg", 507),

  IRON_HELMET("minecraft:iron_helmet", 346),

  IRON_HOE("minecraft:iron_hoe", 334),

  IRON_HORSE_ARMOR("minecraft:iron_horse_armor", 539),

  IRON_INGOT("minecraft:iron_ingot", 308),

  IRON_LEGGINGS("minecraft:iron_leggings", 348),

  IRON_NUGGET("minecraft:iron_nugget", 577),

  IRON_ORE("minecraft:iron_ore", 15),

  IRON_PICKAXE("minecraft:iron_pickaxe", 300),

  IRON_SHOVEL("minecraft:iron_shovel", 299),

  IRON_SWORD("minecraft:iron_sword", 310),

  IRON_TRAPDOOR("minecraft:iron_trapdoor", 167),

  ITEM_ACACIA_DOOR("minecraft:item.acacia_door", 196),

  ITEM_BED("minecraft:item.bed", 26),

  ITEM_BEETROOT("minecraft:item.beetroot", 244),

  ITEM_BIRCH_DOOR("minecraft:item.birch_door", 194),

  ITEM_BREWING_STAND("minecraft:item.brewing_stand", 117),

  ITEM_CAKE("minecraft:item.cake", 92),

  ITEM_CAMERA("minecraft:item.camera", 242),

  ITEM_CAMPFIRE("minecraft:item.campfire", -209),

  ITEM_CAULDRON("minecraft:item.cauldron", 118),

  ITEM_CHAIN("minecraft:item.chain", -286),

  ITEM_CRIMSON_DOOR("minecraft:item.crimson_door", -244),

  ITEM_DARK_OAK_DOOR("minecraft:item.dark_oak_door", 197),

  ITEM_FLOWER_POT("minecraft:item.flower_pot", 140),

  ITEM_FRAME("minecraft:item.frame", 199),

  ITEM_GLOW_FRAME("minecraft:item.glow_frame", -339),

  ITEM_HOPPER("minecraft:item.hopper", 154),

  ITEM_IRON_DOOR("minecraft:item.iron_door", 71),

  ITEM_JUNGLE_DOOR("minecraft:item.jungle_door", 195),

  ITEM_KELP("minecraft:item.kelp", -138),

  ITEM_MANGROVE_DOOR("minecraft:item.mangrove_door", -493),

  ITEM_NETHER_SPROUTS("minecraft:item.nether_sprouts", -238),

  ITEM_NETHER_WART("minecraft:item.nether_wart", 115),

  ITEM_REEDS("minecraft:item.reeds", 83),

  ITEM_SKULL("minecraft:item.skull", 144),

  ITEM_SOUL_CAMPFIRE("minecraft:item.soul_campfire", -290),

  ITEM_SPRUCE_DOOR("minecraft:item.spruce_door", 193),

  ITEM_WARPED_DOOR("minecraft:item.warped_door", -245),

  ITEM_WHEAT("minecraft:item.wheat", 59),

  ITEM_WOODEN_DOOR("minecraft:item.wooden_door", 64),

  JIGSAW("minecraft:jigsaw", -211),

  JUKEBOX("minecraft:jukebox", 84),

  JUNGLE_BOAT("minecraft:jungle_boat", 380),

  JUNGLE_BUTTON("minecraft:jungle_button", -143),

  JUNGLE_CHEST_BOAT("minecraft:jungle_chest_boat", 648),

  JUNGLE_DOOR("minecraft:jungle_door", 563),

  JUNGLE_FENCE("minecraft:jungle_fence", -578),

  JUNGLE_FENCE_GATE("minecraft:jungle_fence_gate", 185),

  JUNGLE_HANGING_SIGN("minecraft:jungle_hanging_sign", -503),

  JUNGLE_LOG("minecraft:jungle_log", -571),

  JUNGLE_PLANKS("minecraft:jungle_planks", -741),

  JUNGLE_PRESSURE_PLATE("minecraft:jungle_pressure_plate", -153),

  JUNGLE_SIGN("minecraft:jungle_sign", 586),

  JUNGLE_STAIRS("minecraft:jungle_stairs", 136),

  JUNGLE_STANDING_SIGN("minecraft:jungle_standing_sign", -188),

  JUNGLE_TRAPDOOR("minecraft:jungle_trapdoor", -148),

  JUNGLE_WALL_SIGN("minecraft:jungle_wall_sign", -189),

  KELP("minecraft:kelp", 385),

  LADDER("minecraft:ladder", 65),

  LANTERN("minecraft:lantern", -208),

  LAPIS_BLOCK("minecraft:lapis_block", 22),

  LAPIS_LAZULI("minecraft:lapis_lazuli", 417),

  LAPIS_ORE("minecraft:lapis_ore", 21),

  LARGE_AMETHYST_BUD("minecraft:large_amethyst_bud", -330),

  LAVA("minecraft:lava", 11),

  LAVA_BUCKET("minecraft:lava_bucket", 366),

  LEAD("minecraft:lead", 555),

  LEATHER("minecraft:leather", 384),

  LEATHER_BOOTS("minecraft:leather_boots", 341),

  LEATHER_CHESTPLATE("minecraft:leather_chestplate", 339),

  LEATHER_HELMET("minecraft:leather_helmet", 338),

  LEATHER_HORSE_ARMOR("minecraft:leather_horse_armor", 538),

  LEATHER_LEGGINGS("minecraft:leather_leggings", 340),

  LEAVES("minecraft:leaves", 18),

  LEAVES2("minecraft:leaves2", 161),

  LECTERN("minecraft:lectern", -194),

  LEVER("minecraft:lever", 69),

  LIGHT_BLOCK("minecraft:light_block", -215),

  LIGHT_BLUE_CANDLE("minecraft:light_blue_candle", -416),

  LIGHT_BLUE_CANDLE_CAKE("minecraft:light_blue_candle_cake", -433),

  LIGHT_BLUE_CARPET("minecraft:light_blue_carpet", -599),

  LIGHT_BLUE_CONCRETE("minecraft:light_blue_concrete", -630),

  LIGHT_BLUE_CONCRETE_POWDER("minecraft:light_blue_concrete_powder", -711),

  LIGHT_BLUE_DYE("minecraft:light_blue_dye", 410),

  LIGHT_BLUE_GLAZED_TERRACOTTA("minecraft:light_blue_glazed_terracotta", 223),

  LIGHT_BLUE_SHULKER_BOX("minecraft:light_blue_shulker_box", -615),

  LIGHT_BLUE_STAINED_GLASS("minecraft:light_blue_stained_glass", -675),

  LIGHT_BLUE_STAINED_GLASS_PANE("minecraft:light_blue_stained_glass_pane", -645),

  LIGHT_BLUE_TERRACOTTA("minecraft:light_blue_terracotta", -726),

  LIGHT_BLUE_WOOL("minecraft:light_blue_wool", -562),

  LIGHT_GRAY_CANDLE("minecraft:light_gray_candle", -421),

  LIGHT_GRAY_CANDLE_CAKE("minecraft:light_gray_candle_cake", -438),

  LIGHT_GRAY_CARPET("minecraft:light_gray_carpet", -604),

  LIGHT_GRAY_CONCRETE("minecraft:light_gray_concrete", -635),

  LIGHT_GRAY_CONCRETE_POWDER("minecraft:light_gray_concrete_powder", -716),

  LIGHT_GRAY_DYE("minecraft:light_gray_dye", 405),

  LIGHT_GRAY_SHULKER_BOX("minecraft:light_gray_shulker_box", -620),

  LIGHT_GRAY_STAINED_GLASS("minecraft:light_gray_stained_glass", -680),

  LIGHT_GRAY_STAINED_GLASS_PANE("minecraft:light_gray_stained_glass_pane", -650),

  LIGHT_GRAY_TERRACOTTA("minecraft:light_gray_terracotta", -731),

  LIGHT_GRAY_WOOL("minecraft:light_gray_wool", -552),

  LIGHT_WEIGHTED_PRESSURE_PLATE("minecraft:light_weighted_pressure_plate", 147),

  LIGHTNING_ROD("minecraft:lightning_rod", -312),

  LIME_CANDLE("minecraft:lime_candle", -418),

  LIME_CANDLE_CAKE("minecraft:lime_candle_cake", -435),

  LIME_CARPET("minecraft:lime_carpet", -601),

  LIME_CONCRETE("minecraft:lime_concrete", -632),

  LIME_CONCRETE_POWDER("minecraft:lime_concrete_powder", -713),

  LIME_DYE("minecraft:lime_dye", 408),

  LIME_GLAZED_TERRACOTTA("minecraft:lime_glazed_terracotta", 225),

  LIME_SHULKER_BOX("minecraft:lime_shulker_box", -617),

  LIME_STAINED_GLASS("minecraft:lime_stained_glass", -677),

  LIME_STAINED_GLASS_PANE("minecraft:lime_stained_glass_pane", -647),

  LIME_TERRACOTTA("minecraft:lime_terracotta", -728),

  LIME_WOOL("minecraft:lime_wool", -559),

  LINGERING_POTION("minecraft:lingering_potion", 570),

  LIT_BLAST_FURNACE("minecraft:lit_blast_furnace", -214),

  LIT_DEEPSLATE_REDSTONE_ORE("minecraft:lit_deepslate_redstone_ore", -404),

  LIT_FURNACE("minecraft:lit_furnace", 62),

  LIT_PUMPKIN("minecraft:lit_pumpkin", 91),

  LIT_REDSTONE_LAMP("minecraft:lit_redstone_lamp", 124),

  LIT_REDSTONE_ORE("minecraft:lit_redstone_ore", 74),

  LIT_SMOKER("minecraft:lit_smoker", -199),

  LLAMA_SPAWN_EGG("minecraft:llama_spawn_egg", 476),

  LODESTONE("minecraft:lodestone", -222),

  LODESTONE_COMPASS("minecraft:lodestone_compass", 610),

  LOG("minecraft:log", 706),

  LOG2("minecraft:log2", 710),

  LOOM("minecraft:loom", -204),

  MAGENTA_CANDLE("minecraft:magenta_candle", -415),

  MAGENTA_CANDLE_CAKE("minecraft:magenta_candle_cake", -432),

  MAGENTA_CARPET("minecraft:magenta_carpet", -598),

  MAGENTA_CONCRETE("minecraft:magenta_concrete", -629),

  MAGENTA_CONCRETE_POWDER("minecraft:magenta_concrete_powder", -710),

  MAGENTA_DYE("minecraft:magenta_dye", 411),

  MAGENTA_GLAZED_TERRACOTTA("minecraft:magenta_glazed_terracotta", 222),

  MAGENTA_SHULKER_BOX("minecraft:magenta_shulker_box", -614),

  MAGENTA_STAINED_GLASS("minecraft:magenta_stained_glass", -674),

  MAGENTA_STAINED_GLASS_PANE("minecraft:magenta_stained_glass_pane", -644),

  MAGENTA_TERRACOTTA("minecraft:magenta_terracotta", -725),

  MAGENTA_WOOL("minecraft:magenta_wool", -565),

  MAGMA("minecraft:magma", 213),

  MAGMA_CREAM("minecraft:magma_cream", 433),

  MAGMA_CUBE_SPAWN_EGG("minecraft:magma_cube_spawn_egg", 458),

  MANGROVE_BOAT("minecraft:mangrove_boat", 643),

  MANGROVE_BUTTON("minecraft:mangrove_button", -487),

  MANGROVE_CHEST_BOAT("minecraft:mangrove_chest_boat", 652),

  MANGROVE_DOOR("minecraft:mangrove_door", 641),

  MANGROVE_DOUBLE_SLAB("minecraft:mangrove_double_slab", -499),

  MANGROVE_FENCE("minecraft:mangrove_fence", -491),

  MANGROVE_FENCE_GATE("minecraft:mangrove_fence_gate", -492),

  MANGROVE_HANGING_SIGN("minecraft:mangrove_hanging_sign", -508),

  MANGROVE_LEAVES("minecraft:mangrove_leaves", -472),

  MANGROVE_LOG("minecraft:mangrove_log", -484),

  MANGROVE_PLANKS("minecraft:mangrove_planks", -486),

  MANGROVE_PRESSURE_PLATE("minecraft:mangrove_pressure_plate", -490),

  MANGROVE_PROPAGULE("minecraft:mangrove_propagule", -474),

  MANGROVE_ROOTS("minecraft:mangrove_roots", -482),

  MANGROVE_SIGN("minecraft:mangrove_sign", 642),

  MANGROVE_SLAB("minecraft:mangrove_slab", -489),

  MANGROVE_STAIRS("minecraft:mangrove_stairs", -488),

  MANGROVE_STANDING_SIGN("minecraft:mangrove_standing_sign", -494),

  MANGROVE_TRAPDOOR("minecraft:mangrove_trapdoor", -496),

  MANGROVE_WALL_SIGN("minecraft:mangrove_wall_sign", -495),

  MANGROVE_WOOD("minecraft:mangrove_wood", -497),

  MEDICINE("minecraft:medicine", 607),

  MEDIUM_AMETHYST_BUD("minecraft:medium_amethyst_bud", -331),

  MELON_BLOCK("minecraft:melon_block", 103),

  MELON_SEEDS("minecraft:melon_seeds", 294),

  MELON_SLICE("minecraft:melon_slice", 273),

  MELON_STEM("minecraft:melon_stem", 105),

  MILK_BUCKET("minecraft:milk_bucket", 364),

  MINECART("minecraft:minecart", 373),

  MINER_POTTERY_SHERD("minecraft:miner_pottery_sherd", 676),

  MOB_SPAWNER("minecraft:mob_spawner", 52),

  MOJANG_BANNER_PATTERN("minecraft:mojang_banner_pattern", 592),

  MONSTER_EGG("minecraft:monster_egg", 97),

  MOOSHROOM_SPAWN_EGG("minecraft:mooshroom_spawn_egg", 443),

  MOSS_BLOCK("minecraft:moss_block", -320),

  MOSS_CARPET("minecraft:moss_carpet", -335),

  MOSSY_COBBLESTONE("minecraft:mossy_cobblestone", 48),

  MOSSY_COBBLESTONE_STAIRS("minecraft:mossy_cobblestone_stairs", -179),

  MOSSY_STONE_BRICK_STAIRS("minecraft:mossy_stone_brick_stairs", -175),

  MOURNER_POTTERY_SHERD("minecraft:mourner_pottery_sherd", 677),

  MOVING_BLOCK("minecraft:moving_block", 250),

  MUD("minecraft:mud", -473),

  MUD_BRICK_DOUBLE_SLAB("minecraft:mud_brick_double_slab", -479),

  MUD_BRICK_SLAB("minecraft:mud_brick_slab", -478),

  MUD_BRICK_STAIRS("minecraft:mud_brick_stairs", -480),

  MUD_BRICK_WALL("minecraft:mud_brick_wall", -481),

  MUD_BRICKS("minecraft:mud_bricks", -475),

  MUDDY_MANGROVE_ROOTS("minecraft:muddy_mangrove_roots", -483),

  MULE_SPAWN_EGG("minecraft:mule_spawn_egg", 469),

  MUSHROOM_STEW("minecraft:mushroom_stew", 261),

  MUSIC_DISC_11("minecraft:music_disc_11", 552),

  MUSIC_DISC_13("minecraft:music_disc_13", 542),

  MUSIC_DISC_5("minecraft:music_disc_5", 644),

  MUSIC_DISC_BLOCKS("minecraft:music_disc_blocks", 544),

  MUSIC_DISC_CAT("minecraft:music_disc_cat", 543),

  MUSIC_DISC_CHIRP("minecraft:music_disc_chirp", 545),

  MUSIC_DISC_FAR("minecraft:music_disc_far", 546),

  MUSIC_DISC_MALL("minecraft:music_disc_mall", 547),

  MUSIC_DISC_MELLOHI("minecraft:music_disc_mellohi", 548),

  MUSIC_DISC_OTHERSIDE("minecraft:music_disc_otherside", 634),

  MUSIC_DISC_PIGSTEP("minecraft:music_disc_pigstep", 628),

  MUSIC_DISC_RELIC("minecraft:music_disc_relic", 702),

  MUSIC_DISC_STAL("minecraft:music_disc_stal", 549),

  MUSIC_DISC_STRAD("minecraft:music_disc_strad", 550),

  MUSIC_DISC_WAIT("minecraft:music_disc_wait", 553),

  MUSIC_DISC_WARD("minecraft:music_disc_ward", 551),

  MUTTON("minecraft:mutton", 558),

  MYCELIUM("minecraft:mycelium", 110),

  NAME_TAG("minecraft:name_tag", 556),

  NAUTILUS_SHELL("minecraft:nautilus_shell", 578),

  NETHER_BRICK("minecraft:nether_brick", 112),

  NETHER_BRICK_FENCE("minecraft:nether_brick_fence", 113),

  NETHER_BRICK_STAIRS("minecraft:nether_brick_stairs", 114),

  NETHER_GOLD_ORE("minecraft:nether_gold_ore", -288),

  NETHER_SPROUTS("minecraft:nether_sprouts", 629),

  NETHER_STAR("minecraft:nether_star", 526),

  NETHER_WART("minecraft:nether_wart", 295),

  NETHER_WART_BLOCK("minecraft:nether_wart_block", 214),

  NETHERBRICK("minecraft:netherbrick", 531),

  NETHERITE_AXE("minecraft:netherite_axe", 614),

  NETHERITE_BLOCK("minecraft:netherite_block", -270),

  NETHERITE_BOOTS("minecraft:netherite_boots", 620),

  NETHERITE_CHESTPLATE("minecraft:netherite_chestplate", 618),

  NETHERITE_HELMET("minecraft:netherite_helmet", 617),

  NETHERITE_HOE("minecraft:netherite_hoe", 615),

  NETHERITE_INGOT("minecraft:netherite_ingot", 616),

  NETHERITE_LEGGINGS("minecraft:netherite_leggings", 619),

  NETHERITE_PICKAXE("minecraft:netherite_pickaxe", 613),

  NETHERITE_SCRAP("minecraft:netherite_scrap", 621),

  NETHERITE_SHOVEL("minecraft:netherite_shovel", 612),

  NETHERITE_SWORD("minecraft:netherite_sword", 611),

  NETHERITE_UPGRADE_SMITHING_TEMPLATE("minecraft:netherite_upgrade_smithing_template", 685),

  NETHERRACK("minecraft:netherrack", 87),

  NETHERREACTOR("minecraft:netherreactor", 247),

  NORMAL_STONE_STAIRS("minecraft:normal_stone_stairs", -180),

  NOTEBLOCK("minecraft:noteblock", 25),

  NPC_SPAWN_EGG("minecraft:npc_spawn_egg", 473),

  OAK_BOAT("minecraft:oak_boat", 378),

  OAK_CHEST_BOAT("minecraft:oak_chest_boat", 646),

  OAK_FENCE("minecraft:oak_fence", 85),

  OAK_HANGING_SIGN("minecraft:oak_hanging_sign", -500),

  OAK_LOG("minecraft:oak_log", 17),

  OAK_PLANKS("minecraft:oak_planks", 5),

  OAK_SIGN("minecraft:oak_sign", 361),

  OAK_STAIRS("minecraft:oak_stairs", 53),

  OBSERVER("minecraft:observer", 251),

  OBSIDIAN("minecraft:obsidian", 49),

  OCELOT_SPAWN_EGG("minecraft:ocelot_spawn_egg", 454),

  OCHRE_FROGLIGHT("minecraft:ochre_froglight", -471),

  ORANGE_CANDLE("minecraft:orange_candle", -414),

  ORANGE_CANDLE_CAKE("minecraft:orange_candle_cake", -431),

  ORANGE_CARPET("minecraft:orange_carpet", -597),

  ORANGE_CONCRETE("minecraft:orange_concrete", -628),

  ORANGE_CONCRETE_POWDER("minecraft:orange_concrete_powder", -709),

  ORANGE_DYE("minecraft:orange_dye", 412),

  ORANGE_GLAZED_TERRACOTTA("minecraft:orange_glazed_terracotta", 221),

  ORANGE_SHULKER_BOX("minecraft:orange_shulker_box", -613),

  ORANGE_STAINED_GLASS("minecraft:orange_stained_glass", -673),

  ORANGE_STAINED_GLASS_PANE("minecraft:orange_stained_glass_pane", -643),

  ORANGE_TERRACOTTA("minecraft:orange_terracotta", -724),

  ORANGE_WOOL("minecraft:orange_wool", -557),

  OXIDIZED_CHISELED_COPPER("minecraft:oxidized_chiseled_copper", -763),

  OXIDIZED_COPPER("minecraft:oxidized_copper", -343),

  OXIDIZED_COPPER_BULB("minecraft:oxidized_copper_bulb", -779),

  OXIDIZED_COPPER_DOOR("minecraft:oxidized_copper_door", -787),

  OXIDIZED_COPPER_GRATE("minecraft:oxidized_copper_grate", -771),

  OXIDIZED_COPPER_TRAPDOOR("minecraft:oxidized_copper_trapdoor", -795),

  OXIDIZED_CUT_COPPER("minecraft:oxidized_cut_copper", -350),

  OXIDIZED_CUT_COPPER_SLAB("minecraft:oxidized_cut_copper_slab", -364),

  OXIDIZED_CUT_COPPER_STAIRS("minecraft:oxidized_cut_copper_stairs", -357),

  OXIDIZED_DOUBLE_CUT_COPPER_SLAB("minecraft:oxidized_double_cut_copper_slab", -371),

  PACKED_ICE("minecraft:packed_ice", 174),

  PACKED_MUD("minecraft:packed_mud", -477),

  PAINTING("minecraft:painting", 360),

  PANDA_SPAWN_EGG("minecraft:panda_spawn_egg", 492),

  PAPER("minecraft:paper", 389),

  PARROT_SPAWN_EGG("minecraft:parrot_spawn_egg", 481),

  PEARLESCENT_FROGLIGHT("minecraft:pearlescent_froglight", -469),

  PHANTOM_MEMBRANE("minecraft:phantom_membrane", 582),

  PHANTOM_SPAWN_EGG("minecraft:phantom_spawn_egg", 489),

  PIG_SPAWN_EGG("minecraft:pig_spawn_egg", 440),

  PIGLIN_BANNER_PATTERN("minecraft:piglin_banner_pattern", 595),

  PIGLIN_BRUTE_SPAWN_EGG("minecraft:piglin_brute_spawn_egg", 502),

  PIGLIN_SPAWN_EGG("minecraft:piglin_spawn_egg", 500),

  PILLAGER_SPAWN_EGG("minecraft:pillager_spawn_egg", 494),

  PINK_CANDLE("minecraft:pink_candle", -419),

  PINK_CANDLE_CAKE("minecraft:pink_candle_cake", -436),

  PINK_CARPET("minecraft:pink_carpet", -602),

  PINK_CONCRETE("minecraft:pink_concrete", -633),

  PINK_CONCRETE_POWDER("minecraft:pink_concrete_powder", -714),

  PINK_DYE("minecraft:pink_dye", 407),

  PINK_GLAZED_TERRACOTTA("minecraft:pink_glazed_terracotta", 226),

  PINK_PETALS("minecraft:pink_petals", -549),

  PINK_SHULKER_BOX("minecraft:pink_shulker_box", -618),

  PINK_STAINED_GLASS("minecraft:pink_stained_glass", -678),

  PINK_STAINED_GLASS_PANE("minecraft:pink_stained_glass_pane", -648),

  PINK_TERRACOTTA("minecraft:pink_terracotta", -729),

  PINK_WOOL("minecraft:pink_wool", -566),

  PISTON("minecraft:piston", 33),

  PISTON_ARM_COLLISION("minecraft:piston_arm_collision", 34),

  PITCHER_CROP("minecraft:pitcher_crop", -574),

  PITCHER_PLANT("minecraft:pitcher_plant", -612),

  PITCHER_POD("minecraft:pitcher_pod", 298),

  PLANKS("minecraft:planks", 708),

  PLENTY_POTTERY_SHERD("minecraft:plenty_pottery_sherd", 678),

  PODZOL("minecraft:podzol", 243),

  POINTED_DRIPSTONE("minecraft:pointed_dripstone", -308),

  POISONOUS_POTATO("minecraft:poisonous_potato", 283),

  POLAR_BEAR_SPAWN_EGG("minecraft:polar_bear_spawn_egg", 475),

  POLISHED_ANDESITE("minecraft:polished_andesite", -595),

  POLISHED_ANDESITE_STAIRS("minecraft:polished_andesite_stairs", -174),

  POLISHED_BASALT("minecraft:polished_basalt", -235),

  POLISHED_BLACKSTONE("minecraft:polished_blackstone", -291),

  POLISHED_BLACKSTONE_BRICK_DOUBLE_SLAB("minecraft:polished_blackstone_brick_double_slab", -285),

  POLISHED_BLACKSTONE_BRICK_SLAB("minecraft:polished_blackstone_brick_slab", -284),

  POLISHED_BLACKSTONE_BRICK_STAIRS("minecraft:polished_blackstone_brick_stairs", -275),

  POLISHED_BLACKSTONE_BRICK_WALL("minecraft:polished_blackstone_brick_wall", -278),

  POLISHED_BLACKSTONE_BRICKS("minecraft:polished_blackstone_bricks", -274),

  POLISHED_BLACKSTONE_BUTTON("minecraft:polished_blackstone_button", -296),

  POLISHED_BLACKSTONE_DOUBLE_SLAB("minecraft:polished_blackstone_double_slab", -294),

  POLISHED_BLACKSTONE_PRESSURE_PLATE("minecraft:polished_blackstone_pressure_plate", -295),

  POLISHED_BLACKSTONE_SLAB("minecraft:polished_blackstone_slab", -293),

  POLISHED_BLACKSTONE_STAIRS("minecraft:polished_blackstone_stairs", -292),

  POLISHED_BLACKSTONE_WALL("minecraft:polished_blackstone_wall", -297),

  POLISHED_DEEPSLATE("minecraft:polished_deepslate", -383),

  POLISHED_DEEPSLATE_DOUBLE_SLAB("minecraft:polished_deepslate_double_slab", -397),

  POLISHED_DEEPSLATE_SLAB("minecraft:polished_deepslate_slab", -384),

  POLISHED_DEEPSLATE_STAIRS("minecraft:polished_deepslate_stairs", -385),

  POLISHED_DEEPSLATE_WALL("minecraft:polished_deepslate_wall", -386),

  POLISHED_DIORITE("minecraft:polished_diorite", -593),

  POLISHED_DIORITE_STAIRS("minecraft:polished_diorite_stairs", -173),

  POLISHED_GRANITE("minecraft:polished_granite", -591),

  POLISHED_GRANITE_STAIRS("minecraft:polished_granite_stairs", -172),

  POLISHED_TUFF("minecraft:polished_tuff", -748),

  POLISHED_TUFF_DOUBLE_SLAB("minecraft:polished_tuff_double_slab", -750),

  POLISHED_TUFF_SLAB("minecraft:polished_tuff_slab", -749),

  POLISHED_TUFF_STAIRS("minecraft:polished_tuff_stairs", -751),

  POLISHED_TUFF_WALL("minecraft:polished_tuff_wall", -752),

  POPPED_CHORUS_FRUIT("minecraft:popped_chorus_fruit", 567),

  PORKCHOP("minecraft:porkchop", 263),

  PORTAL("minecraft:portal", 90),

  POTATO("minecraft:potato", 281),

  POTATOES("minecraft:potatoes", 142),

  POTION("minecraft:potion", 429),

  POWDER_SNOW("minecraft:powder_snow", -306),

  POWDER_SNOW_BUCKET("minecraft:powder_snow_bucket", 371),

  POWERED_COMPARATOR("minecraft:powered_comparator", 150),

  POWERED_REPEATER("minecraft:powered_repeater", 94),

  PRISMARINE("minecraft:prismarine", 168),

  PRISMARINE_BRICKS_STAIRS("minecraft:prismarine_bricks_stairs", -4),

  PRISMARINE_CRYSTALS("minecraft:prismarine_crystals", 557),

  PRISMARINE_SHARD("minecraft:prismarine_shard", 573),

  PRISMARINE_STAIRS("minecraft:prismarine_stairs", -2),

  PRIZE_POTTERY_SHERD("minecraft:prize_pottery_sherd", 679),

  PUFFERFISH("minecraft:pufferfish", 268),

  PUFFERFISH_BUCKET("minecraft:pufferfish_bucket", 370),

  PUFFERFISH_SPAWN_EGG("minecraft:pufferfish_spawn_egg", 484),

  PUMPKIN("minecraft:pumpkin", 86),

  PUMPKIN_PIE("minecraft:pumpkin_pie", 285),

  PUMPKIN_SEEDS("minecraft:pumpkin_seeds", 293),

  PUMPKIN_STEM("minecraft:pumpkin_stem", 104),

  PURPLE_CANDLE("minecraft:purple_candle", -423),

  PURPLE_CANDLE_CAKE("minecraft:purple_candle_cake", -440),

  PURPLE_CARPET("minecraft:purple_carpet", -606),

  PURPLE_CONCRETE("minecraft:purple_concrete", -637),

  PURPLE_CONCRETE_POWDER("minecraft:purple_concrete_powder", -718),

  PURPLE_DYE("minecraft:purple_dye", 403),

  PURPLE_GLAZED_TERRACOTTA("minecraft:purple_glazed_terracotta", 219),

  PURPLE_SHULKER_BOX("minecraft:purple_shulker_box", -622),

  PURPLE_STAINED_GLASS("minecraft:purple_stained_glass", -682),

  PURPLE_STAINED_GLASS_PANE("minecraft:purple_stained_glass_pane", -652),

  PURPLE_TERRACOTTA("minecraft:purple_terracotta", -733),

  PURPLE_WOOL("minecraft:purple_wool", -564),

  PURPUR_BLOCK("minecraft:purpur_block", 201),

  PURPUR_STAIRS("minecraft:purpur_stairs", 203),

  QUARTZ("minecraft:quartz", 532),

  QUARTZ_BLOCK("minecraft:quartz_block", 155),

  QUARTZ_BRICKS("minecraft:quartz_bricks", -304),

  QUARTZ_ORE("minecraft:quartz_ore", 153),

  QUARTZ_STAIRS("minecraft:quartz_stairs", 156),

  RABBIT("minecraft:rabbit", 289),

  RABBIT_FOOT("minecraft:rabbit_foot", 536),

  RABBIT_HIDE("minecraft:rabbit_hide", 537),

  RABBIT_SPAWN_EGG("minecraft:rabbit_spawn_egg", 462),

  RABBIT_STEW("minecraft:rabbit_stew", 291),

  RAIL("minecraft:rail", 66),

  RAISER_ARMOR_TRIM_SMITHING_TEMPLATE("minecraft:raiser_armor_trim_smithing_template", 699),

  RAPID_FERTILIZER("minecraft:rapid_fertilizer", 605),

  RAVAGER_SPAWN_EGG("minecraft:ravager_spawn_egg", 496),

  RAW_COPPER("minecraft:raw_copper", 515),

  RAW_COPPER_BLOCK("minecraft:raw_copper_block", -452),

  RAW_GOLD("minecraft:raw_gold", 514),

  RAW_GOLD_BLOCK("minecraft:raw_gold_block", -453),

  RAW_IRON("minecraft:raw_iron", 513),

  RAW_IRON_BLOCK("minecraft:raw_iron_block", -451),

  RECOVERY_COMPASS("minecraft:recovery_compass", 654),

  RED_CANDLE("minecraft:red_candle", -427),

  RED_CANDLE_CAKE("minecraft:red_candle_cake", -444),

  RED_CARPET("minecraft:red_carpet", -610),

  RED_CONCRETE("minecraft:red_concrete", -641),

  RED_CONCRETE_POWDER("minecraft:red_concrete_powder", -722),

  RED_DYE("minecraft:red_dye", 399),

  RED_FLOWER("minecraft:red_flower", 38),

  RED_GLAZED_TERRACOTTA("minecraft:red_glazed_terracotta", 234),

  RED_MUSHROOM("minecraft:red_mushroom", 40),

  RED_MUSHROOM_BLOCK("minecraft:red_mushroom_block", 100),

  RED_NETHER_BRICK("minecraft:red_nether_brick", 215),

  RED_NETHER_BRICK_STAIRS("minecraft:red_nether_brick_stairs", -184),

  RED_SANDSTONE("minecraft:red_sandstone", 179),

  RED_SANDSTONE_STAIRS("minecraft:red_sandstone_stairs", 180),

  RED_SHULKER_BOX("minecraft:red_shulker_box", -626),

  RED_STAINED_GLASS("minecraft:red_stained_glass", -686),

  RED_STAINED_GLASS_PANE("minecraft:red_stained_glass_pane", -656),

  RED_TERRACOTTA("minecraft:red_terracotta", -737),

  RED_WOOL("minecraft:red_wool", -556),

  REDSTONE("minecraft:redstone", 376),

  REDSTONE_BLOCK("minecraft:redstone_block", 152),

  REDSTONE_LAMP("minecraft:redstone_lamp", 123),

  REDSTONE_ORE("minecraft:redstone_ore", 73),

  REDSTONE_TORCH("minecraft:redstone_torch", 76),

  REDSTONE_WIRE("minecraft:redstone_wire", 55),

  REINFORCED_DEEPSLATE("minecraft:reinforced_deepslate", -466),

  REPEATER("minecraft:repeater", 422),

  REPEATING_COMMAND_BLOCK("minecraft:repeating_command_block", 188),

  RESERVED6("minecraft:reserved6", 255),

  RESPAWN_ANCHOR("minecraft:respawn_anchor", -272),

  RIB_ARMOR_TRIM_SMITHING_TEMPLATE("minecraft:rib_armor_trim_smithing_template", 695),

  ROTTEN_FLESH("minecraft:rotten_flesh", 278),

  SADDLE("minecraft:saddle", 374),

  SALMON("minecraft:salmon", 266),

  SALMON_BUCKET("minecraft:salmon_bucket", 368),

  SALMON_SPAWN_EGG("minecraft:salmon_spawn_egg", 485),

  SAND("minecraft:sand", 12),

  SANDSTONE("minecraft:sandstone", 24),

  SANDSTONE_STAIRS("minecraft:sandstone_stairs", 128),

  SAPLING("minecraft:sapling", 6),

  SCAFFOLDING("minecraft:scaffolding", -165),

  SCULK("minecraft:sculk", -458),

  SCULK_CATALYST("minecraft:sculk_catalyst", -460),

  SCULK_SENSOR("minecraft:sculk_sensor", -307),

  SCULK_SHRIEKER("minecraft:sculk_shrieker", -461),

  SCULK_VEIN("minecraft:sculk_vein", -459),

  SCUTE("minecraft:scute", 580),

  SEA_LANTERN("minecraft:sea_lantern", 169),

  SEA_PICKLE("minecraft:sea_pickle", -156),

  SEAGRASS("minecraft:seagrass", -130),

  SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE("minecraft:sentry_armor_trim_smithing_template", 686),

  SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE("minecraft:shaper_armor_trim_smithing_template", 700),

  SHEAF_POTTERY_SHERD("minecraft:sheaf_pottery_sherd", 680),

  SHEARS("minecraft:shears", 424),

  SHEEP_SPAWN_EGG("minecraft:sheep_spawn_egg", 441),

  SHELTER_POTTERY_SHERD("minecraft:shelter_pottery_sherd", 681),

  SHIELD("minecraft:shield", 358),

  SHROOMLIGHT("minecraft:shroomlight", -230),

  SHULKER_BOX("minecraft:shulker_box", 715),

  SHULKER_SHELL("minecraft:shulker_shell", 574),

  SHULKER_SPAWN_EGG("minecraft:shulker_spawn_egg", 472),

  SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE("minecraft:silence_armor_trim_smithing_template", 697),

  SILVER_GLAZED_TERRACOTTA("minecraft:silver_glazed_terracotta", 228),

  SILVERFISH_SPAWN_EGG("minecraft:silverfish_spawn_egg", 446),

  SKELETON_HORSE_SPAWN_EGG("minecraft:skeleton_horse_spawn_egg", 470),

  SKELETON_SPAWN_EGG("minecraft:skeleton_spawn_egg", 447),

  SKULL("minecraft:skull", 524),

  SKULL_BANNER_PATTERN("minecraft:skull_banner_pattern", 591),

  SKULL_POTTERY_SHERD("minecraft:skull_pottery_sherd", 682),

  SLIME("minecraft:slime", 165),

  SLIME_BALL("minecraft:slime_ball", 391),

  SLIME_SPAWN_EGG("minecraft:slime_spawn_egg", 448),

  SMALL_AMETHYST_BUD("minecraft:small_amethyst_bud", -332),

  SMALL_DRIPLEAF_BLOCK("minecraft:small_dripleaf_block", -336),

  SMITHING_TABLE("minecraft:smithing_table", -202),

  SMOKER("minecraft:smoker", -198),

  SMOOTH_BASALT("minecraft:smooth_basalt", -377),

  SMOOTH_QUARTZ_STAIRS("minecraft:smooth_quartz_stairs", -185),

  SMOOTH_RED_SANDSTONE_STAIRS("minecraft:smooth_red_sandstone_stairs", -176),

  SMOOTH_SANDSTONE_STAIRS("minecraft:smooth_sandstone_stairs", -177),

  SMOOTH_STONE("minecraft:smooth_stone", -183),

  SNIFFER_EGG("minecraft:sniffer_egg", -596),

  SNIFFER_SPAWN_EGG("minecraft:sniffer_spawn_egg", 503),

  SNORT_POTTERY_SHERD("minecraft:snort_pottery_sherd", 683),

  SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE("minecraft:snout_armor_trim_smithing_template", 694),

  SNOW("minecraft:snow", 80),

  SNOW_GOLEM_SPAWN_EGG("minecraft:snow_golem_spawn_egg", 508),

  SNOW_LAYER("minecraft:snow_layer", 78),

  SNOWBALL("minecraft:snowball", 377),

  SOUL_CAMPFIRE("minecraft:soul_campfire", 630),

  SOUL_FIRE("minecraft:soul_fire", -237),

  SOUL_LANTERN("minecraft:soul_lantern", -269),

  SOUL_SAND("minecraft:soul_sand", 88),

  SOUL_SOIL("minecraft:soul_soil", -236),

  SOUL_TORCH("minecraft:soul_torch", -268),

  SPARKLER("minecraft:sparkler", 608),

  SPAWN_EGG("minecraft:spawn_egg", 719),

  SPIDER_EYE("minecraft:spider_eye", 279),

  SPIDER_SPAWN_EGG("minecraft:spider_spawn_egg", 449),

  SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE("minecraft:spire_armor_trim_smithing_template", 696),

  SPLASH_POTION("minecraft:splash_potion", 569),

  SPONGE("minecraft:sponge", 19),

  SPORE_BLOSSOM("minecraft:spore_blossom", -321),

  SPRUCE_BOAT("minecraft:spruce_boat", 381),

  SPRUCE_BUTTON("minecraft:spruce_button", -144),

  SPRUCE_CHEST_BOAT("minecraft:spruce_chest_boat", 649),

  SPRUCE_DOOR("minecraft:spruce_door", 561),

  SPRUCE_FENCE("minecraft:spruce_fence", -579),

  SPRUCE_FENCE_GATE("minecraft:spruce_fence_gate", 183),

  SPRUCE_HANGING_SIGN("minecraft:spruce_hanging_sign", -501),

  SPRUCE_LOG("minecraft:spruce_log", -569),

  SPRUCE_PLANKS("minecraft:spruce_planks", -739),

  SPRUCE_PRESSURE_PLATE("minecraft:spruce_pressure_plate", -154),

  SPRUCE_SIGN("minecraft:spruce_sign", 584),

  SPRUCE_STAIRS("minecraft:spruce_stairs", 134),

  SPRUCE_STANDING_SIGN("minecraft:spruce_standing_sign", -181),

  SPRUCE_TRAPDOOR("minecraft:spruce_trapdoor", -149),

  SPRUCE_WALL_SIGN("minecraft:spruce_wall_sign", -182),

  SPYGLASS("minecraft:spyglass", 633),

  SQUID_SPAWN_EGG("minecraft:squid_spawn_egg", 453),

  STAINED_GLASS("minecraft:stained_glass", 713),

  STAINED_GLASS_PANE("minecraft:stained_glass_pane", 714),

  STAINED_HARDENED_CLAY("minecraft:stained_hardened_clay", 703),

  STANDING_BANNER("minecraft:standing_banner", 176),

  STANDING_SIGN("minecraft:standing_sign", 63),

  STICK("minecraft:stick", 323),

  STICKY_PISTON("minecraft:sticky_piston", 29),

  STICKY_PISTON_ARM_COLLISION("minecraft:sticky_piston_arm_collision", -217),

  STONE("minecraft:stone", 1),

  STONE_AXE("minecraft:stone_axe", 318),

  STONE_BLOCK_SLAB("minecraft:stone_block_slab", 44),

  STONE_BLOCK_SLAB2("minecraft:stone_block_slab2", 182),

  STONE_BLOCK_SLAB3("minecraft:stone_block_slab3", -162),

  STONE_BLOCK_SLAB4("minecraft:stone_block_slab4", -166),

  STONE_BRICK_STAIRS("minecraft:stone_brick_stairs", 109),

  STONE_BUTTON("minecraft:stone_button", 77),

  STONE_HOE("minecraft:stone_hoe", 333),

  STONE_PICKAXE("minecraft:stone_pickaxe", 317),

  STONE_PRESSURE_PLATE("minecraft:stone_pressure_plate", 70),

  STONE_SHOVEL("minecraft:stone_shovel", 316),

  STONE_STAIRS("minecraft:stone_stairs", 67),

  STONE_SWORD("minecraft:stone_sword", 315),

  STONEBRICK("minecraft:stonebrick", 98),

  STONECUTTER("minecraft:stonecutter", 245),

  STONECUTTER_BLOCK("minecraft:stonecutter_block", -197),

  STRAY_SPAWN_EGG("minecraft:stray_spawn_egg", 465),

  STRIDER_SPAWN_EGG("minecraft:strider_spawn_egg", 498),

  STRING("minecraft:string", 329),

  STRIPPED_ACACIA_LOG("minecraft:stripped_acacia_log", -8),

  STRIPPED_BAMBOO_BLOCK("minecraft:stripped_bamboo_block", -528),

  STRIPPED_BIRCH_LOG("minecraft:stripped_birch_log", -6),

  STRIPPED_CHERRY_LOG("minecraft:stripped_cherry_log", -535),

  STRIPPED_CHERRY_WOOD("minecraft:stripped_cherry_wood", -545),

  STRIPPED_CRIMSON_HYPHAE("minecraft:stripped_crimson_hyphae", -300),

  STRIPPED_CRIMSON_STEM("minecraft:stripped_crimson_stem", -240),

  STRIPPED_DARK_OAK_LOG("minecraft:stripped_dark_oak_log", -9),

  STRIPPED_JUNGLE_LOG("minecraft:stripped_jungle_log", -7),

  STRIPPED_MANGROVE_LOG("minecraft:stripped_mangrove_log", -485),

  STRIPPED_MANGROVE_WOOD("minecraft:stripped_mangrove_wood", -498),

  STRIPPED_OAK_LOG("minecraft:stripped_oak_log", -10),

  STRIPPED_SPRUCE_LOG("minecraft:stripped_spruce_log", -5),

  STRIPPED_WARPED_HYPHAE("minecraft:stripped_warped_hyphae", -301),

  STRIPPED_WARPED_STEM("minecraft:stripped_warped_stem", -241),

  STRUCTURE_BLOCK("minecraft:structure_block", 252),

  STRUCTURE_VOID("minecraft:structure_void", 217),

  SUGAR("minecraft:sugar", 419),

  SUGAR_CANE("minecraft:sugar_cane", 388),

  SUSPICIOUS_GRAVEL("minecraft:suspicious_gravel", -573),

  SUSPICIOUS_SAND("minecraft:suspicious_sand", -529),

  SUSPICIOUS_STEW("minecraft:suspicious_stew", 598),

  SWEET_BERRIES("minecraft:sweet_berries", 288),

  SWEET_BERRY_BUSH("minecraft:sweet_berry_bush", -207),

  TADPOLE_BUCKET("minecraft:tadpole_bucket", 638),

  TADPOLE_SPAWN_EGG("minecraft:tadpole_spawn_egg", 637),

  TALLGRASS("minecraft:tallgrass", 31),

  TARGET("minecraft:target", -239),

  TIDE_ARMOR_TRIM_SMITHING_TEMPLATE("minecraft:tide_armor_trim_smithing_template", 693),

  TINTED_GLASS("minecraft:tinted_glass", -334),

  TNT("minecraft:tnt", 46),

  TNT_MINECART("minecraft:tnt_minecart", 533),

  TORCH("minecraft:torch", 50),

  TORCHFLOWER("minecraft:torchflower", -568),

  TORCHFLOWER_CROP("minecraft:torchflower_crop", -567),

  TORCHFLOWER_SEEDS("minecraft:torchflower_seeds", 297),

  TOTEM_OF_UNDYING("minecraft:totem_of_undying", 576),

  TRADER_LLAMA_SPAWN_EGG("minecraft:trader_llama_spawn_egg", 656),

  TRAPDOOR("minecraft:trapdoor", 96),

  TRAPPED_CHEST("minecraft:trapped_chest", 146),

  TRIDENT("minecraft:trident", 554),

  TRIP_WIRE("minecraft:trip_wire", 132),

  TRIPWIRE_HOOK("minecraft:tripwire_hook", 131),

  TROPICAL_FISH("minecraft:tropical_fish", 267),

  TROPICAL_FISH_BUCKET("minecraft:tropical_fish_bucket", 369),

  TROPICAL_FISH_SPAWN_EGG("minecraft:tropical_fish_spawn_egg", 482),

  TUBE_CORAL("minecraft:tube_coral", -131),

  TUFF("minecraft:tuff", -333),

  TUFF_BRICK_DOUBLE_SLAB("minecraft:tuff_brick_double_slab", -756),

  TUFF_BRICK_SLAB("minecraft:tuff_brick_slab", -755),

  TUFF_BRICK_STAIRS("minecraft:tuff_brick_stairs", -757),

  TUFF_BRICK_WALL("minecraft:tuff_brick_wall", -758),

  TUFF_BRICKS("minecraft:tuff_bricks", -754),

  TUFF_DOUBLE_SLAB("minecraft:tuff_double_slab", -745),

  TUFF_SLAB("minecraft:tuff_slab", -744),

  TUFF_STAIRS("minecraft:tuff_stairs", -746),

  TUFF_WALL("minecraft:tuff_wall", -747),

  TURTLE_EGG("minecraft:turtle_egg", -159),

  TURTLE_HELMET("minecraft:turtle_helmet", 581),

  TURTLE_SPAWN_EGG("minecraft:turtle_spawn_egg", 488),

  TWISTING_VINES("minecraft:twisting_vines", -287),

  UNDERWATER_TORCH("minecraft:underwater_torch", 239),

  UNDYED_SHULKER_BOX("minecraft:undyed_shulker_box", 205),

  UNKNOWN("minecraft:unknown", -305),

  UNLIT_REDSTONE_TORCH("minecraft:unlit_redstone_torch", 75),

  UNPOWERED_COMPARATOR("minecraft:unpowered_comparator", 149),

  UNPOWERED_REPEATER("minecraft:unpowered_repeater", 93),

  VERDANT_FROGLIGHT("minecraft:verdant_froglight", -470),

  VEX_ARMOR_TRIM_SMITHING_TEMPLATE("minecraft:vex_armor_trim_smithing_template", 692),

  VEX_SPAWN_EGG("minecraft:vex_spawn_egg", 479),

  VILLAGER_SPAWN_EGG("minecraft:villager_spawn_egg", 452),

  VINDICATOR_SPAWN_EGG("minecraft:vindicator_spawn_egg", 477),

  VINE("minecraft:vine", 106),

  WALL_BANNER("minecraft:wall_banner", 177),

  WALL_SIGN("minecraft:wall_sign", 68),

  WANDERING_TRADER_SPAWN_EGG("minecraft:wandering_trader_spawn_egg", 495),

  WARD_ARMOR_TRIM_SMITHING_TEMPLATE("minecraft:ward_armor_trim_smithing_template", 690),

  WARDEN_SPAWN_EGG("minecraft:warden_spawn_egg", 640),

  WARPED_BUTTON("minecraft:warped_button", -261),

  WARPED_DOOR("minecraft:warped_door", 625),

  WARPED_DOUBLE_SLAB("minecraft:warped_double_slab", -267),

  WARPED_FENCE("minecraft:warped_fence", -257),

  WARPED_FENCE_GATE("minecraft:warped_fence_gate", -259),

  WARPED_FUNGUS("minecraft:warped_fungus", -229),

  WARPED_FUNGUS_ON_A_STICK("minecraft:warped_fungus_on_a_stick", 626),

  WARPED_HANGING_SIGN("minecraft:warped_hanging_sign", -507),

  WARPED_HYPHAE("minecraft:warped_hyphae", -298),

  WARPED_NYLIUM("minecraft:warped_nylium", -233),

  WARPED_PLANKS("minecraft:warped_planks", -243),

  WARPED_PRESSURE_PLATE("minecraft:warped_pressure_plate", -263),

  WARPED_ROOTS("minecraft:warped_roots", -224),

  WARPED_SIGN("minecraft:warped_sign", 623),

  WARPED_SLAB("minecraft:warped_slab", -265),

  WARPED_STAIRS("minecraft:warped_stairs", -255),

  WARPED_STANDING_SIGN("minecraft:warped_standing_sign", -251),

  WARPED_STEM("minecraft:warped_stem", -226),

  WARPED_TRAPDOOR("minecraft:warped_trapdoor", -247),

  WARPED_WALL_SIGN("minecraft:warped_wall_sign", -253),

  WARPED_WART_BLOCK("minecraft:warped_wart_block", -227),

  WATER("minecraft:water", 9),

  WATER_BUCKET("minecraft:water_bucket", 365),

  WATERLILY("minecraft:waterlily", 111),

  WAXED_CHISELED_COPPER("minecraft:waxed_chiseled_copper", -764),

  WAXED_COPPER("minecraft:waxed_copper", -344),

  WAXED_COPPER_BULB("minecraft:waxed_copper_bulb", -780),

  WAXED_COPPER_DOOR("minecraft:waxed_copper_door", -788),

  WAXED_COPPER_GRATE("minecraft:waxed_copper_grate", -772),

  WAXED_COPPER_TRAPDOOR("minecraft:waxed_copper_trapdoor", -796),

  WAXED_CUT_COPPER("minecraft:waxed_cut_copper", -351),

  WAXED_CUT_COPPER_SLAB("minecraft:waxed_cut_copper_slab", -365),

  WAXED_CUT_COPPER_STAIRS("minecraft:waxed_cut_copper_stairs", -358),

  WAXED_DOUBLE_CUT_COPPER_SLAB("minecraft:waxed_double_cut_copper_slab", -372),

  WAXED_EXPOSED_CHISELED_COPPER("minecraft:waxed_exposed_chiseled_copper", -765),

  WAXED_EXPOSED_COPPER("minecraft:waxed_exposed_copper", -345),

  WAXED_EXPOSED_COPPER_BULB("minecraft:waxed_exposed_copper_bulb", -781),

  WAXED_EXPOSED_COPPER_DOOR("minecraft:waxed_exposed_copper_door", -789),

  WAXED_EXPOSED_COPPER_GRATE("minecraft:waxed_exposed_copper_grate", -773),

  WAXED_EXPOSED_COPPER_TRAPDOOR("minecraft:waxed_exposed_copper_trapdoor", -797),

  WAXED_EXPOSED_CUT_COPPER("minecraft:waxed_exposed_cut_copper", -352),

  WAXED_EXPOSED_CUT_COPPER_SLAB("minecraft:waxed_exposed_cut_copper_slab", -366),

  WAXED_EXPOSED_CUT_COPPER_STAIRS("minecraft:waxed_exposed_cut_copper_stairs", -359),

  WAXED_EXPOSED_DOUBLE_CUT_COPPER_SLAB("minecraft:waxed_exposed_double_cut_copper_slab", -373),

  WAXED_OXIDIZED_CHISELED_COPPER("minecraft:waxed_oxidized_chiseled_copper", -766),

  WAXED_OXIDIZED_COPPER("minecraft:waxed_oxidized_copper", -446),

  WAXED_OXIDIZED_COPPER_BULB("minecraft:waxed_oxidized_copper_bulb", -783),

  WAXED_OXIDIZED_COPPER_DOOR("minecraft:waxed_oxidized_copper_door", -791),

  WAXED_OXIDIZED_COPPER_GRATE("minecraft:waxed_oxidized_copper_grate", -775),

  WAXED_OXIDIZED_COPPER_TRAPDOOR("minecraft:waxed_oxidized_copper_trapdoor", -799),

  WAXED_OXIDIZED_CUT_COPPER("minecraft:waxed_oxidized_cut_copper", -447),

  WAXED_OXIDIZED_CUT_COPPER_SLAB("minecraft:waxed_oxidized_cut_copper_slab", -449),

  WAXED_OXIDIZED_CUT_COPPER_STAIRS("minecraft:waxed_oxidized_cut_copper_stairs", -448),

  WAXED_OXIDIZED_DOUBLE_CUT_COPPER_SLAB("minecraft:waxed_oxidized_double_cut_copper_slab", -450),

  WAXED_WEATHERED_CHISELED_COPPER("minecraft:waxed_weathered_chiseled_copper", -767),

  WAXED_WEATHERED_COPPER("minecraft:waxed_weathered_copper", -346),

  WAXED_WEATHERED_COPPER_BULB("minecraft:waxed_weathered_copper_bulb", -782),

  WAXED_WEATHERED_COPPER_DOOR("minecraft:waxed_weathered_copper_door", -790),

  WAXED_WEATHERED_COPPER_GRATE("minecraft:waxed_weathered_copper_grate", -774),

  WAXED_WEATHERED_COPPER_TRAPDOOR("minecraft:waxed_weathered_copper_trapdoor", -798),

  WAXED_WEATHERED_CUT_COPPER("minecraft:waxed_weathered_cut_copper", -353),

  WAXED_WEATHERED_CUT_COPPER_SLAB("minecraft:waxed_weathered_cut_copper_slab", -367),

  WAXED_WEATHERED_CUT_COPPER_STAIRS("minecraft:waxed_weathered_cut_copper_stairs", -360),

  WAXED_WEATHERED_DOUBLE_CUT_COPPER_SLAB("minecraft:waxed_weathered_double_cut_copper_slab", -374),

  WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE("minecraft:wayfinder_armor_trim_smithing_template", 698),

  WEATHERED_CHISELED_COPPER("minecraft:weathered_chiseled_copper", -762),

  WEATHERED_COPPER("minecraft:weathered_copper", -342),

  WEATHERED_COPPER_BULB("minecraft:weathered_copper_bulb", -778),

  WEATHERED_COPPER_DOOR("minecraft:weathered_copper_door", -786),

  WEATHERED_COPPER_GRATE("minecraft:weathered_copper_grate", -770),

  WEATHERED_COPPER_TRAPDOOR("minecraft:weathered_copper_trapdoor", -794),

  WEATHERED_CUT_COPPER("minecraft:weathered_cut_copper", -349),

  WEATHERED_CUT_COPPER_SLAB("minecraft:weathered_cut_copper_slab", -363),

  WEATHERED_CUT_COPPER_STAIRS("minecraft:weathered_cut_copper_stairs", -356),

  WEATHERED_DOUBLE_CUT_COPPER_SLAB("minecraft:weathered_double_cut_copper_slab", -370),

  WEB("minecraft:web", 30),

  WEEPING_VINES("minecraft:weeping_vines", -231),

  WHEAT("minecraft:wheat", 337),

  WHEAT_SEEDS("minecraft:wheat_seeds", 292),

  WHITE_CANDLE("minecraft:white_candle", -413),

  WHITE_CANDLE_CAKE("minecraft:white_candle_cake", -430),

  WHITE_CARPET("minecraft:white_carpet", 171),

  WHITE_CONCRETE("minecraft:white_concrete", 236),

  WHITE_CONCRETE_POWDER("minecraft:white_concrete_powder", 237),

  WHITE_DYE("minecraft:white_dye", 413),

  WHITE_GLAZED_TERRACOTTA("minecraft:white_glazed_terracotta", 220),

  WHITE_SHULKER_BOX("minecraft:white_shulker_box", 218),

  WHITE_STAINED_GLASS("minecraft:white_stained_glass", 241),

  WHITE_STAINED_GLASS_PANE("minecraft:white_stained_glass_pane", 160),

  WHITE_TERRACOTTA("minecraft:white_terracotta", 159),

  WHITE_WOOL("minecraft:white_wool", 35),

  WILD_ARMOR_TRIM_SMITHING_TEMPLATE("minecraft:wild_armor_trim_smithing_template", 689),

  WITCH_SPAWN_EGG("minecraft:witch_spawn_egg", 455),

  WITHER_ROSE("minecraft:wither_rose", -216),

  WITHER_SKELETON_SPAWN_EGG("minecraft:wither_skeleton_spawn_egg", 467),

  WITHER_SPAWN_EGG("minecraft:wither_spawn_egg", 510),

  WOLF_SPAWN_EGG("minecraft:wolf_spawn_egg", 442),

  WOOD("minecraft:wood", -212),

  WOODEN_AXE("minecraft:wooden_axe", 314),

  WOODEN_BUTTON("minecraft:wooden_button", 143),

  WOODEN_DOOR("minecraft:wooden_door", 362),

  WOODEN_HOE("minecraft:wooden_hoe", 332),

  WOODEN_PICKAXE("minecraft:wooden_pickaxe", 313),

  WOODEN_PRESSURE_PLATE("minecraft:wooden_pressure_plate", 72),

  WOODEN_SHOVEL("minecraft:wooden_shovel", 312),

  WOODEN_SLAB("minecraft:wooden_slab", 158),

  WOODEN_SWORD("minecraft:wooden_sword", 311),

  WOOL("minecraft:wool", 704),

  WRITABLE_BOOK("minecraft:writable_book", 518),

  WRITTEN_BOOK("minecraft:written_book", 519),

  YELLOW_CANDLE("minecraft:yellow_candle", -417),

  YELLOW_CANDLE_CAKE("minecraft:yellow_candle_cake", -434),

  YELLOW_CARPET("minecraft:yellow_carpet", -600),

  YELLOW_CONCRETE("minecraft:yellow_concrete", -631),

  YELLOW_CONCRETE_POWDER("minecraft:yellow_concrete_powder", -712),

  YELLOW_DYE("minecraft:yellow_dye", 409),

  YELLOW_FLOWER("minecraft:yellow_flower", 37),

  YELLOW_GLAZED_TERRACOTTA("minecraft:yellow_glazed_terracotta", 224),

  YELLOW_SHULKER_BOX("minecraft:yellow_shulker_box", -616),

  YELLOW_STAINED_GLASS("minecraft:yellow_stained_glass", -676),

  YELLOW_STAINED_GLASS_PANE("minecraft:yellow_stained_glass_pane", -646),

  YELLOW_TERRACOTTA("minecraft:yellow_terracotta", -727),

  YELLOW_WOOL("minecraft:yellow_wool", -558),

  ZOGLIN_SPAWN_EGG("minecraft:zoglin_spawn_egg", 501),

  ZOMBIE_HORSE_SPAWN_EGG("minecraft:zombie_horse_spawn_egg", 471),

  ZOMBIE_PIGMAN_SPAWN_EGG("minecraft:zombie_pigman_spawn_egg", 451),

  ZOMBIE_SPAWN_EGG("minecraft:zombie_spawn_egg", 450),

  ZOMBIE_VILLAGER_SPAWN_EGG("minecraft:zombie_villager_spawn_egg", 480);

  @Getter
  private final Identifier identifier;

  @Getter
  private final int runtimeId;

  VanillaItemId(String identifier, int runtimeId) {
    this.identifier = new Identifier(identifier);
    this.runtimeId = runtimeId;
  }

  public ItemType<?> getItemType() {
    return ItemTypeRegistry.getRegistry().get(this.getIdentifier());
  }


  public static org.allaymc.api.data.VanillaItemId fromIdentifier(
      org.allaymc.api.identifier.Identifier identifier) {
    try{
        return valueOf(identifier.path().toUpperCase(java.util.Locale.ENGLISH));
    }catch(IllegalArgumentException ignore){
        return null;
    }
  }
}
