package org.allaymc.dependence;

import lombok.Getter;

/**
 * Automatically generated by {@code org.allaymc.codegen.EntityIdEnumGen}
 */
public enum EntityId {
    AGENT("minecraft:agent", 56),

    ALLAY("minecraft:allay", 134),

    AREA_EFFECT_CLOUD("minecraft:area_effect_cloud", 95),

    ARMADILLO("minecraft:armadillo", 142),

    ARMOR_STAND("minecraft:armor_stand", 61),

    ARROW("minecraft:arrow", 80),

    AXOLOTL("minecraft:axolotl", 130),

    BALLOON("minecraft:balloon", 107),

    BAT("minecraft:bat", 19),

    BEE("minecraft:bee", 122),

    BLAZE("minecraft:blaze", 43),

    BOAT("minecraft:boat", 90),

    BOGGED("minecraft:bogged", 144),

    BREEZE("minecraft:breeze", 140),

    BREEZE_WIND_CHARGE_PROJECTILE("minecraft:breeze_wind_charge_projectile", 141),

    CAMEL("minecraft:camel", 138),

    CAT("minecraft:cat", 75),

    CAVE_SPIDER("minecraft:cave_spider", 40),

    CHEST_BOAT("minecraft:chest_boat", 218),

    CHEST_MINECART("minecraft:chest_minecart", 98),

    CHICKEN("minecraft:chicken", 10),

    COD("minecraft:cod", 112),

    COMMAND_BLOCK_MINECART("minecraft:command_block_minecart", 100),

    COPPER_GOLEM("minecraft:copper_golem", 148),

    COW("minecraft:cow", 11),

    CREAKING("minecraft:creaking", 146),

    CREEPER("minecraft:creeper", 33),

    DOLPHIN("minecraft:dolphin", 31),

    DONKEY("minecraft:donkey", 24),

    DRAGON_FIREBALL("minecraft:dragon_fireball", 79),

    DROWNED("minecraft:drowned", 110),

    EGG("minecraft:egg", 82),

    ELDER_GUARDIAN("minecraft:elder_guardian", 50),

    ELDER_GUARDIAN_GHOST("minecraft:elder_guardian_ghost", 120),

    ENDER_CRYSTAL("minecraft:ender_crystal", 71),

    ENDER_DRAGON("minecraft:ender_dragon", 53),

    ENDER_PEARL("minecraft:ender_pearl", 87),

    ENDERMAN("minecraft:enderman", 38),

    ENDERMITE("minecraft:endermite", 55),

    EVOCATION_FANG("minecraft:evocation_fang", 103),

    EVOCATION_ILLAGER("minecraft:evocation_illager", 104),

    EYE_OF_ENDER_SIGNAL("minecraft:eye_of_ender_signal", 70),

    FALLING_BLOCK("minecraft:falling_block", 66),

    FIREBALL("minecraft:fireball", 85),

    FIREWORKS_ROCKET("minecraft:fireworks_rocket", 72),

    FISHING_HOOK("minecraft:fishing_hook", 77),

    FOX("minecraft:fox", 121),

    FROG("minecraft:frog", 132),

    GHAST("minecraft:ghast", 41),

    GLOW_SQUID("minecraft:glow_squid", 129),

    GOAT("minecraft:goat", 128),

    GUARDIAN("minecraft:guardian", 49),

    HAPPY_GHAST("minecraft:happy_ghast", 147),

    HOGLIN("minecraft:hoglin", 124),

    HOPPER_MINECART("minecraft:hopper_minecart", 96),

    HORSE("minecraft:horse", 23),

    HUSK("minecraft:husk", 47),

    ICE_BOMB("minecraft:ice_bomb", 106),

    IRON_GOLEM("minecraft:iron_golem", 20),

    ITEM("minecraft:item", 64),

    LEASH_KNOT("minecraft:leash_knot", 88),

    LIGHTNING_BOLT("minecraft:lightning_bolt", 93),

    LINGERING_POTION("minecraft:lingering_potion", 101),

    LLAMA("minecraft:llama", 29),

    LLAMA_SPIT("minecraft:llama_spit", 102),

    MAGMA_CUBE("minecraft:magma_cube", 42),

    MINECART("minecraft:minecart", 84),

    MOOSHROOM("minecraft:mooshroom", 16),

    MULE("minecraft:mule", 25),

    NPC("minecraft:npc", 51),

    OCELOT("minecraft:ocelot", 22),

    OMINOUS_ITEM_SPAWNER("minecraft:ominous_item_spawner", 145),

    PAINTING("minecraft:painting", 83),

    PANDA("minecraft:panda", 113),

    PARROT("minecraft:parrot", 30),

    PHANTOM("minecraft:phantom", 58),

    PIG("minecraft:pig", 12),

    PIGLIN("minecraft:piglin", 123),

    PIGLIN_BRUTE("minecraft:piglin_brute", 127),

    PILLAGER("minecraft:pillager", 114),

    PLAYER("minecraft:player", 257),

    POLAR_BEAR("minecraft:polar_bear", 28),

    PUFFERFISH("minecraft:pufferfish", 108),

    RABBIT("minecraft:rabbit", 18),

    RAVAGER("minecraft:ravager", 59),

    SALMON("minecraft:salmon", 109),

    SHEEP("minecraft:sheep", 13),

    SHULKER("minecraft:shulker", 54),

    SHULKER_BULLET("minecraft:shulker_bullet", 76),

    SILVERFISH("minecraft:silverfish", 39),

    SKELETON("minecraft:skeleton", 34),

    SKELETON_HORSE("minecraft:skeleton_horse", 26),

    SLIME("minecraft:slime", 37),

    SMALL_FIREBALL("minecraft:small_fireball", 94),

    SNIFFER("minecraft:sniffer", 139),

    SNOW_GOLEM("minecraft:snow_golem", 21),

    SNOWBALL("minecraft:snowball", 81),

    SPIDER("minecraft:spider", 35),

    SPLASH_POTION("minecraft:splash_potion", 86),

    SQUID("minecraft:squid", 17),

    STRAY("minecraft:stray", 46),

    STRIDER("minecraft:strider", 125),

    TADPOLE("minecraft:tadpole", 133),

    THROWN_TRIDENT("minecraft:thrown_trident", 73),

    TNT("minecraft:tnt", 65),

    TNT_MINECART("minecraft:tnt_minecart", 97),

    TRADER_LLAMA("minecraft:trader_llama", 157),

    TRIPOD_CAMERA("minecraft:tripod_camera", 62),

    TROPICALFISH("minecraft:tropicalfish", 111),

    TURTLE("minecraft:turtle", 74),

    VEX("minecraft:vex", 105),

    VILLAGER("minecraft:villager", 15),

    VILLAGER_V2("minecraft:villager_v2", 115),

    VINDICATOR("minecraft:vindicator", 57),

    WANDERING_TRADER("minecraft:wandering_trader", 118),

    WARDEN("minecraft:warden", 131),

    WIND_CHARGE_PROJECTILE("minecraft:wind_charge_projectile", 143),

    WITCH("minecraft:witch", 45),

    WITHER("minecraft:wither", 52),

    WITHER_SKELETON("minecraft:wither_skeleton", 48),

    WITHER_SKULL("minecraft:wither_skull", 89),

    WITHER_SKULL_DANGEROUS("minecraft:wither_skull_dangerous", 91),

    WOLF("minecraft:wolf", 14),

    XP_BOTTLE("minecraft:xp_bottle", 68),

    XP_ORB("minecraft:xp_orb", 69),

    ZOGLIN("minecraft:zoglin", 126),

    ZOMBIE("minecraft:zombie", 32),

    ZOMBIE_HORSE("minecraft:zombie_horse", 27),

    ZOMBIE_PIGMAN("minecraft:zombie_pigman", 36),

    ZOMBIE_VILLAGER("minecraft:zombie_villager", 44),

    ZOMBIE_VILLAGER_V2("minecraft:zombie_villager_v2", 116);

    @Getter
    private final Identifier identifier;

    @Getter
    private final int networkId;

    EntityId(String identifier, int networkId) {
        this.identifier = new Identifier(identifier);
        this.networkId = networkId;
    }
}
