package org.allaymc.api.block.tag;

import org.allaymc.api.annotation.MinecraftVersionSensitive;

import java.util.HashMap;
import java.util.Map;

/**
 * Automatically generated by {@code org.allaymc.codegen.TagGen}
 */
@MinecraftVersionSensitive
public interface BlockCustomTags {
    Map<String, BlockTag> NAME_TO_TAG = new HashMap<>();

    BlockTag SOUL_FIRE_CONVERTER = create("allay:soul_fire_converter");

    BlockTag BEACON_BASE = create("allay:beacon_base");

    BlockTag REPLACEABLE = create("allay:replaceable");

    BlockTag WOOL = create("allay:wool");

    BlockTag LEAVES = create("allay:leaves");

    BlockTag POTTABLE_PLANT = create("allay:pottable_plant");

    BlockTag WATER = create("allay:water");

    BlockTag LEAVES_SUPPORTER = create("allay:leaves_supporter");

    BlockTag LAVA = create("allay:lava");

    BlockTag INFINITE_FIRE_SUPPORTER = create("allay:infinite_fire_supporter");

    static BlockTag create(String name) {
        var tag = new BlockTag(name);
        NAME_TO_TAG.put(name, tag);
        return tag;
    }

    static BlockTag getTagByName(String name) {
        return NAME_TO_TAG.get(name);
    }
}
