package org.allaymc.api.block.property.enums;

import org.allaymc.api.annotation.MinecraftVersionSensitive;

/**
 * Automatically generated by {@code org.allaymc.codegen.BlockPropertyTypeGen}
 */
@MinecraftVersionSensitive
public enum BambooLeafSize {
    NO_LEAVES,

    SMALL_LEAVES,

    LARGE_LEAVES
}
