package cn.allay.api.block.property.enums;

/**
 * Automatically generated by {@code cn.allay.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <p>
 *
 * @author daoge_cmd
 */
public enum ChemistryTableType {
  COMPOUND_CREATOR,

  ELEMENT_CONSTRUCTOR,

  LAB_TABLE,

  MATERIAL_REDUCER
}
