package cn.allay.api.block.property.enums;

/**
 * Automatically generated by {@code cn.allay.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <p>
 * @author daoge_cmd
 */
public enum FlowerType {
    ALLIUM,

    CORNFLOWER,

    HOUSTONIA,

    LILY_OF_THE_VALLEY,

    ORCHID,

    OXEYE,

    POPPY,

    TULIP_ORANGE,

    TULIP_PINK,

    TULIP_RED,

    TULIP_WHITE
}
