package cn.allay.api.block.property.enums;

/**
 * @author: daoge_cmd <br>
 * Automatically generated by {@code cn.allay.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <br>
 */
public enum StoneSlabType3 {
  ANDESITE,

  DIORITE,

  END_STONE_BRICK,

  GRANITE,

  POLISHED_ANDESITE,

  POLISHED_DIORITE,

  POLISHED_GRANITE,

  SMOOTH_RED_SANDSTONE
}
