package cn.allay.api.block.property.enums;

/**
 * Author: daoge_cmd <br>
 * Automatically generated by {@code cn.allay.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <br>
 */
public enum StoneType {
    STONE,

    GRANITE,

    GRANITE_SMOOTH,

    DIORITE,

    DIORITE_SMOOTH,

    ANDESITE,

    ANDESITE_SMOOTH
}
