package cn.allay.api.block.property.enums;

/**
 * Author: daoge_cmd <br>
 * Automatically generated by {@code cn.allay.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <br>
 */
public enum StoneSlabType4 {
    CUT_RED_SANDSTONE,

    CUT_SANDSTONE,

    MOSSY_STONE_BRICK,

    SMOOTH_QUARTZ,

    STONE
}
