package cn.allay.api.block.property.enums;

/**
 * Author: daoge_cmd <br>
 * Automatically generated by {@code cn.allay.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <br>
 */
public enum TurtleEggCount {
    FOUR_EGG,

    ONE_EGG,

    THREE_EGG,

    TWO_EGG
}
