package cn.allay.api.block.property.enums;

/**
 * @author: daoge_cmd <br>
 * Automatically generated by {@code cn.allay.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <br>
 */
public enum WallConnectionTypeSouth {
  NONE,

  SHORT,

  TALL
}
