package cn.allay.api.block.property.enums;

/**
 * Author: daoge_cmd <br>
 * Automatically generated by {@code cn.allay.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <br>
 */
public enum WallBlockType {
  ANDESITE,

  BRICK,

  COBBLESTONE,

  DIORITE,

  END_BRICK,

  GRANITE,

  MOSSY_COBBLESTONE,

  MOSSY_STONE_BRICK,

  NETHER_BRICK,

  PRISMARINE,

  RED_NETHER_BRICK,

  RED_SANDSTONE,

  SANDSTONE,

  STONE_BRICK
}
