package cn.allay.api.block.property.enums;

/**
 * Automatically generated by {@code cn.allay.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <p>
 *
 * @author daoge_cmd
 */
public enum WoodType {
    ACACIA,

    BIRCH,

    DARK_OAK,

    JUNGLE,

    OAK,

    SPRUCE
}
