package cn.allay.api.block.property.enums;

/**
 * Author: daoge_cmd <br>
 * Automatically generated by {@code cn.allay.codegen.VanillaBlockPropertyTypeGen} <br>
 * Allay Project <br>
 */
public enum WoodType {
  ACACIA,

  BIRCH,

  DARK_OAK,

  JUNGLE,

  OAK,

  SPRUCE
}
