package org.allaymc.api.item.tag;

import java.util.HashMap;
import java.util.Map;

/**
 * Automatically generated by {@code org.allaymc.codegen.TagGen}
 */
public interface ItemCustomTags {
    Map<String, ItemTag> NAME_TO_TAG = new HashMap<>();

    static ItemTag create(String name) {
        var tag = new ItemTag(name);
        NAME_TO_TAG.put(name, tag);
        return tag;
    }

    static ItemTag getTagByName(String name) {
        return NAME_TO_TAG.get(name);
    }
}
