package cn.allay.api.world;

import cn.allay.api.world.gamerule.GameRules;
import lombok.Builder;
import org.cloudburstmc.protocol.bedrock.data.Ability;

import java.util.List;
import java.util.Map;

@Builder
public record WorldData(
        GameRules gameRules,
        long lightningTime,
        int Platform,
        int Difficulty,
        boolean hasLockedResourcePack,
        int GameType,
        boolean isFromWorldTemplate,
        boolean hasBeenLoadedInCreative,
        float lightningLevel,
        int XBLBroadcastIntent,
        boolean startWithMapEnabled,
        float rainLevel,
        int PlatformBroadcastIntent,
        List<Integer> lastOpenedWithVersion,
        int serverChunkTickRange,
        int WorldVersion,
        boolean educationFeaturesEnabled,
        boolean isExportedFromEditor,
        boolean isCreatedInEditor,
        int Generator,
        long RandomSeed,
        int NetworkVersion,
        Map<String, Boolean> experiments,
        boolean commandsEnabled,
        boolean spawnMobs,
        String InventoryVersion,
        boolean CenterMapsToOrigin,
        boolean LANBroadcastIntent,
        long currentTick,
        boolean isFromLockedTemplate,
        int rainTime,
        boolean LANBroadcast,
        Map<String, String> worldPolicies,
        boolean hasLockedBehaviorPack,
        boolean cheatsEnabled,
        int StorageVersion,
        List<Integer> MinimumCompatibleClientVersion,
        boolean ConfirmedPlatformLockedContent,
        boolean texturePacksRequired,
        boolean bonusChestEnabled,
        Map<Ability, Object> abilities,
        int daylightCycle,
        String baseGameVersion,
        boolean bonusChestSpawned,
        boolean MultiplayerGame,
        boolean isSingleUseWorld,
        int permissionsLevel,
        int spawnY,
        int spawnZ,
        int spawnX,
        String prid,
        int eduOffer,
        long worldStartCount,
        boolean forceGameType,
        boolean MultiplayerGameIntent,
        String LevelName,
        boolean isWorldTemplateOptionLocked,
        long Time,
        int limitedWorldDepth,
        int LimitedWorldOriginY,
        boolean requiresCopiedPackRemovalCheck,
        int LimitedWorldOriginX,
        int LimitedWorldOriginZ,
        int limitedWorldWidth,
        String BiomeOverride,
        boolean SpawnV1Villagers,
        long LastPlayed,
        int NetherScale,
        boolean useMsaGamertagsOnly,
        String FlatWorldLayers,
        boolean immutableWorld,
        int playerPermissionsLevel
) {
}

