package cn.allay.codegen;

import cn.allay.api.identifier.Identifier;
import cn.allay.api.utils.StringUtils;
import com.squareup.javapoet.*;
import lombok.SneakyThrows;

import javax.lang.model.element.Modifier;
import java.nio.file.Files;
import java.nio.file.Path;

import static cn.allay.codegen.CodeGen.MAPPED_ITEM_DATA;

/**
 * Author: daoge_cmd <br>
 * Date: 2023/5/13 <br>
 * Allay Project <br>
 */
public class VanillaItemIdEnumCodeGen {

    private static final Path FILE_OUTPUT_PATH = Path.of("Allay-API/src/main/java/cn/allay/api/data/VanillaItemId.java");

    @SneakyThrows
    public static void generate() {
        var identifierClass = ClassName.get("cn.allay.api.identifier", "Identifier");
        var stringClass = ClassName.get("java.lang", "String");
        var getterClass = ClassName.get("lombok", "Getter");
        TypeSpec.Builder codeBuilder = TypeSpec.enumBuilder("VanillaItemId")
                .addJavadoc(
                        "Author: daoge_cmd <br>\n" +
                                "Automatically generated by {@code cn.allay.codegen.VanillaItemIdEnumCodeGen} <br>\n" +
                                "Allay Project <br>\n")
                .addModifiers(Modifier.PUBLIC)
                .addField(FieldSpec
                        .builder(Identifier.class, "namespaceId", Modifier.PRIVATE, Modifier.FINAL)
                        .addAnnotation(getterClass)
                        .build())
                .addMethod(MethodSpec.constructorBuilder()
                        .addParameter(stringClass, "namespaceId")
                        .addStatement("this.$N = new $T($N)", "namespaceId", identifierClass, "namespaceId")
                        .build()
                );
        for (var entry : MAPPED_ITEM_DATA.entrySet()) {
            var split = StringUtils.fastTwoPartSplit(
                    StringUtils.fastTwoPartSplit(entry.getKey(), ":", "")[1],
                    ".", "");
            var valueName = split[0].isBlank() ? split[1].toUpperCase() : split[0].toUpperCase() + "_" + split[1].toUpperCase();
            codeBuilder.addEnumConstant(valueName, TypeSpec.anonymousClassBuilder("$S", entry.getKey()).build());
        }

        var javaFile = JavaFile.builder("cn.allay.api.data", codeBuilder.build()).build();
        Files.writeString(FILE_OUTPUT_PATH, javaFile.toString());
    }
}
