package cn.allay.item.data;

import cn.allay.identifier.Identifier;
import java.lang.String;
import lombok.Getter;

/**
 * Author: daoge_cmd <br>
 * Automatically generated by {@link cn.allay.codegen.VanillaItemIdEnumGen} <br>
 * Allay Project <br>
 */
public enum VanillaItemId {
  ACACIA_BOAT("minecraft:acacia_boat"),

  ACACIA_BUTTON("minecraft:acacia_button"),

  ACACIA_CHEST_BOAT("minecraft:acacia_chest_boat"),

  ACACIA_DOOR("minecraft:acacia_door"),

  ACACIA_FENCE("minecraft:acacia_fence"),

  ACACIA_FENCE_GATE("minecraft:acacia_fence_gate"),

  ACACIA_HANGING_SIGN("minecraft:acacia_hanging_sign"),

  ACACIA_LOG("minecraft:acacia_log"),

  ACACIA_PRESSURE_PLATE("minecraft:acacia_pressure_plate"),

  ACACIA_SIGN("minecraft:acacia_sign"),

  ACACIA_STAIRS("minecraft:acacia_stairs"),

  ACACIA_STANDING_SIGN("minecraft:acacia_standing_sign"),

  ACACIA_TRAPDOOR("minecraft:acacia_trapdoor"),

  ACACIA_WALL_SIGN("minecraft:acacia_wall_sign"),

  ACTIVATOR_RAIL("minecraft:activator_rail"),

  AGENT_SPAWN_EGG("minecraft:agent_spawn_egg"),

  AIR("minecraft:air"),

  ALLAY_SPAWN_EGG("minecraft:allay_spawn_egg"),

  ALLOW("minecraft:allow"),

  AMETHYST_BLOCK("minecraft:amethyst_block"),

  AMETHYST_CLUSTER("minecraft:amethyst_cluster"),

  AMETHYST_SHARD("minecraft:amethyst_shard"),

  ANCIENT_DEBRIS("minecraft:ancient_debris"),

  ANDESITE_STAIRS("minecraft:andesite_stairs"),

  ANGLER_POTTERY_SHARD("minecraft:angler_pottery_shard"),

  ANVIL("minecraft:anvil"),

  APPLE("minecraft:apple"),

  ARCHER_POTTERY_SHARD("minecraft:archer_pottery_shard"),

  ARMOR_STAND("minecraft:armor_stand"),

  ARMS_UP_POTTERY_SHARD("minecraft:arms_up_pottery_shard"),

  ARROW("minecraft:arrow"),

  AXOLOTL_BUCKET("minecraft:axolotl_bucket"),

  AXOLOTL_SPAWN_EGG("minecraft:axolotl_spawn_egg"),

  AZALEA("minecraft:azalea"),

  AZALEA_LEAVES("minecraft:azalea_leaves"),

  AZALEA_LEAVES_FLOWERED("minecraft:azalea_leaves_flowered"),

  BAKED_POTATO("minecraft:baked_potato"),

  BALLOON("minecraft:balloon"),

  BAMBOO("minecraft:bamboo"),

  BAMBOO_BLOCK("minecraft:bamboo_block"),

  BAMBOO_BUTTON("minecraft:bamboo_button"),

  BAMBOO_CHEST_RAFT("minecraft:bamboo_chest_raft"),

  BAMBOO_DOOR("minecraft:bamboo_door"),

  BAMBOO_DOUBLE_SLAB("minecraft:bamboo_double_slab"),

  BAMBOO_FENCE("minecraft:bamboo_fence"),

  BAMBOO_FENCE_GATE("minecraft:bamboo_fence_gate"),

  BAMBOO_HANGING_SIGN("minecraft:bamboo_hanging_sign"),

  BAMBOO_MOSAIC("minecraft:bamboo_mosaic"),

  BAMBOO_MOSAIC_DOUBLE_SLAB("minecraft:bamboo_mosaic_double_slab"),

  BAMBOO_MOSAIC_SLAB("minecraft:bamboo_mosaic_slab"),

  BAMBOO_MOSAIC_STAIRS("minecraft:bamboo_mosaic_stairs"),

  BAMBOO_PLANKS("minecraft:bamboo_planks"),

  BAMBOO_PRESSURE_PLATE("minecraft:bamboo_pressure_plate"),

  BAMBOO_RAFT("minecraft:bamboo_raft"),

  BAMBOO_SAPLING("minecraft:bamboo_sapling"),

  BAMBOO_SIGN("minecraft:bamboo_sign"),

  BAMBOO_SLAB("minecraft:bamboo_slab"),

  BAMBOO_STAIRS("minecraft:bamboo_stairs"),

  BAMBOO_STANDING_SIGN("minecraft:bamboo_standing_sign"),

  BAMBOO_TRAPDOOR("minecraft:bamboo_trapdoor"),

  BAMBOO_WALL_SIGN("minecraft:bamboo_wall_sign"),

  BANNER("minecraft:banner"),

  BANNER_PATTERN("minecraft:banner_pattern"),

  BARREL("minecraft:barrel"),

  BARRIER("minecraft:barrier"),

  BASALT("minecraft:basalt"),

  BAT_SPAWN_EGG("minecraft:bat_spawn_egg"),

  BEACON("minecraft:beacon"),

  BED("minecraft:bed"),

  BEDROCK("minecraft:bedrock"),

  BEE_NEST("minecraft:bee_nest"),

  BEE_SPAWN_EGG("minecraft:bee_spawn_egg"),

  BEEF("minecraft:beef"),

  BEEHIVE("minecraft:beehive"),

  BEETROOT("minecraft:beetroot"),

  BEETROOT_SEEDS("minecraft:beetroot_seeds"),

  BEETROOT_SOUP("minecraft:beetroot_soup"),

  BELL("minecraft:bell"),

  BIG_DRIPLEAF("minecraft:big_dripleaf"),

  BIRCH_BOAT("minecraft:birch_boat"),

  BIRCH_BUTTON("minecraft:birch_button"),

  BIRCH_CHEST_BOAT("minecraft:birch_chest_boat"),

  BIRCH_DOOR("minecraft:birch_door"),

  BIRCH_FENCE("minecraft:birch_fence"),

  BIRCH_FENCE_GATE("minecraft:birch_fence_gate"),

  BIRCH_HANGING_SIGN("minecraft:birch_hanging_sign"),

  BIRCH_LOG("minecraft:birch_log"),

  BIRCH_PRESSURE_PLATE("minecraft:birch_pressure_plate"),

  BIRCH_SIGN("minecraft:birch_sign"),

  BIRCH_STAIRS("minecraft:birch_stairs"),

  BIRCH_STANDING_SIGN("minecraft:birch_standing_sign"),

  BIRCH_TRAPDOOR("minecraft:birch_trapdoor"),

  BIRCH_WALL_SIGN("minecraft:birch_wall_sign"),

  BLACK_CANDLE("minecraft:black_candle"),

  BLACK_CANDLE_CAKE("minecraft:black_candle_cake"),

  BLACK_DYE("minecraft:black_dye"),

  BLACK_GLAZED_TERRACOTTA("minecraft:black_glazed_terracotta"),

  BLACK_WOOL("minecraft:black_wool"),

  BLACKSTONE("minecraft:blackstone"),

  BLACKSTONE_DOUBLE_SLAB("minecraft:blackstone_double_slab"),

  BLACKSTONE_SLAB("minecraft:blackstone_slab"),

  BLACKSTONE_STAIRS("minecraft:blackstone_stairs"),

  BLACKSTONE_WALL("minecraft:blackstone_wall"),

  BLADE_POTTERY_SHARD("minecraft:blade_pottery_shard"),

  BLAST_FURNACE("minecraft:blast_furnace"),

  BLAZE_POWDER("minecraft:blaze_powder"),

  BLAZE_ROD("minecraft:blaze_rod"),

  BLAZE_SPAWN_EGG("minecraft:blaze_spawn_egg"),

  BLEACH("minecraft:bleach"),

  BLUE_CANDLE("minecraft:blue_candle"),

  BLUE_CANDLE_CAKE("minecraft:blue_candle_cake"),

  BLUE_DYE("minecraft:blue_dye"),

  BLUE_GLAZED_TERRACOTTA("minecraft:blue_glazed_terracotta"),

  BLUE_ICE("minecraft:blue_ice"),

  BLUE_WOOL("minecraft:blue_wool"),

  BOAT("minecraft:boat"),

  BONE("minecraft:bone"),

  BONE_BLOCK("minecraft:bone_block"),

  BONE_MEAL("minecraft:bone_meal"),

  BOOK("minecraft:book"),

  BOOKSHELF("minecraft:bookshelf"),

  BORDER_BLOCK("minecraft:border_block"),

  BORDURE_INDENTED_BANNER_PATTERN("minecraft:bordure_indented_banner_pattern"),

  BOW("minecraft:bow"),

  BOWL("minecraft:bowl"),

  BREAD("minecraft:bread"),

  BREWER_POTTERY_SHARD("minecraft:brewer_pottery_shard"),

  BREWING_STAND("minecraft:brewing_stand"),

  BRICK("minecraft:brick"),

  BRICK_BLOCK("minecraft:brick_block"),

  BRICK_STAIRS("minecraft:brick_stairs"),

  BROWN_CANDLE("minecraft:brown_candle"),

  BROWN_CANDLE_CAKE("minecraft:brown_candle_cake"),

  BROWN_DYE("minecraft:brown_dye"),

  BROWN_GLAZED_TERRACOTTA("minecraft:brown_glazed_terracotta"),

  BROWN_MUSHROOM("minecraft:brown_mushroom"),

  BROWN_MUSHROOM_BLOCK("minecraft:brown_mushroom_block"),

  BROWN_WOOL("minecraft:brown_wool"),

  BRUSH("minecraft:brush"),

  BUBBLE_COLUMN("minecraft:bubble_column"),

  BUCKET("minecraft:bucket"),

  BUDDING_AMETHYST("minecraft:budding_amethyst"),

  BURN_POTTERY_SHARD("minecraft:burn_pottery_shard"),

  CACTUS("minecraft:cactus"),

  CAKE("minecraft:cake"),

  CALCITE("minecraft:calcite"),

  CALIBRATED_SCULK_SENSOR("minecraft:calibrated_sculk_sensor"),

  CAMEL_SPAWN_EGG("minecraft:camel_spawn_egg"),

  CAMERA("minecraft:camera"),

  CAMPFIRE("minecraft:campfire"),

  CANDLE("minecraft:candle"),

  CANDLE_CAKE("minecraft:candle_cake"),

  CARPET("minecraft:carpet"),

  CARROT("minecraft:carrot"),

  CARROT_ON_A_STICK("minecraft:carrot_on_a_stick"),

  CARROTS("minecraft:carrots"),

  CARTOGRAPHY_TABLE("minecraft:cartography_table"),

  CARVED_PUMPKIN("minecraft:carved_pumpkin"),

  CAT_SPAWN_EGG("minecraft:cat_spawn_egg"),

  CAULDRON("minecraft:cauldron"),

  CAVE_SPIDER_SPAWN_EGG("minecraft:cave_spider_spawn_egg"),

  CAVE_VINES("minecraft:cave_vines"),

  CAVE_VINES_BODY_WITH_BERRIES("minecraft:cave_vines_body_with_berries"),

  CAVE_VINES_HEAD_WITH_BERRIES("minecraft:cave_vines_head_with_berries"),

  CHAIN("minecraft:chain"),

  CHAIN_COMMAND_BLOCK("minecraft:chain_command_block"),

  CHAINMAIL_BOOTS("minecraft:chainmail_boots"),

  CHAINMAIL_CHESTPLATE("minecraft:chainmail_chestplate"),

  CHAINMAIL_HELMET("minecraft:chainmail_helmet"),

  CHAINMAIL_LEGGINGS("minecraft:chainmail_leggings"),

  CHARCOAL("minecraft:charcoal"),

  CHEMICAL_HEAT("minecraft:chemical_heat"),

  CHEMISTRY_TABLE("minecraft:chemistry_table"),

  CHERRY_BOAT("minecraft:cherry_boat"),

  CHERRY_BUTTON("minecraft:cherry_button"),

  CHERRY_CHEST_BOAT("minecraft:cherry_chest_boat"),

  CHERRY_DOOR("minecraft:cherry_door"),

  CHERRY_DOUBLE_SLAB("minecraft:cherry_double_slab"),

  CHERRY_FENCE("minecraft:cherry_fence"),

  CHERRY_FENCE_GATE("minecraft:cherry_fence_gate"),

  CHERRY_HANGING_SIGN("minecraft:cherry_hanging_sign"),

  CHERRY_LEAVES("minecraft:cherry_leaves"),

  CHERRY_LOG("minecraft:cherry_log"),

  CHERRY_PLANKS("minecraft:cherry_planks"),

  CHERRY_PRESSURE_PLATE("minecraft:cherry_pressure_plate"),

  CHERRY_SAPLING("minecraft:cherry_sapling"),

  CHERRY_SIGN("minecraft:cherry_sign"),

  CHERRY_SLAB("minecraft:cherry_slab"),

  CHERRY_STAIRS("minecraft:cherry_stairs"),

  CHERRY_STANDING_SIGN("minecraft:cherry_standing_sign"),

  CHERRY_TRAPDOOR("minecraft:cherry_trapdoor"),

  CHERRY_WALL_SIGN("minecraft:cherry_wall_sign"),

  CHERRY_WOOD("minecraft:cherry_wood"),

  CHEST("minecraft:chest"),

  CHEST_BOAT("minecraft:chest_boat"),

  CHEST_MINECART("minecraft:chest_minecart"),

  CHICKEN("minecraft:chicken"),

  CHICKEN_SPAWN_EGG("minecraft:chicken_spawn_egg"),

  CHISELED_BOOKSHELF("minecraft:chiseled_bookshelf"),

  CHISELED_DEEPSLATE("minecraft:chiseled_deepslate"),

  CHISELED_NETHER_BRICKS("minecraft:chiseled_nether_bricks"),

  CHISELED_POLISHED_BLACKSTONE("minecraft:chiseled_polished_blackstone"),

  CHORUS_FLOWER("minecraft:chorus_flower"),

  CHORUS_FRUIT("minecraft:chorus_fruit"),

  CHORUS_PLANT("minecraft:chorus_plant"),

  CLAY("minecraft:clay"),

  CLAY_BALL("minecraft:clay_ball"),

  CLIENT_REQUEST_PLACEHOLDER_BLOCK("minecraft:client_request_placeholder_block"),

  CLOCK("minecraft:clock"),

  COAL("minecraft:coal"),

  COAL_BLOCK("minecraft:coal_block"),

  COAL_ORE("minecraft:coal_ore"),

  COAST_ARMOR_TRIM_SMITHING_TEMPLATE("minecraft:coast_armor_trim_smithing_template"),

  COBBLED_DEEPSLATE("minecraft:cobbled_deepslate"),

  COBBLED_DEEPSLATE_DOUBLE_SLAB("minecraft:cobbled_deepslate_double_slab"),

  COBBLED_DEEPSLATE_SLAB("minecraft:cobbled_deepslate_slab"),

  COBBLED_DEEPSLATE_STAIRS("minecraft:cobbled_deepslate_stairs"),

  COBBLED_DEEPSLATE_WALL("minecraft:cobbled_deepslate_wall"),

  COBBLESTONE("minecraft:cobblestone"),

  COBBLESTONE_WALL("minecraft:cobblestone_wall"),

  COCOA("minecraft:cocoa"),

  COCOA_BEANS("minecraft:cocoa_beans"),

  COD("minecraft:cod"),

  COD_BUCKET("minecraft:cod_bucket"),

  COD_SPAWN_EGG("minecraft:cod_spawn_egg"),

  COLORED_TORCH_BP("minecraft:colored_torch_bp"),

  COLORED_TORCH_RG("minecraft:colored_torch_rg"),

  COMMAND_BLOCK("minecraft:command_block"),

  COMMAND_BLOCK_MINECART("minecraft:command_block_minecart"),

  COMPARATOR("minecraft:comparator"),

  COMPASS("minecraft:compass"),

  COMPOSTER("minecraft:composter"),

  COMPOUND("minecraft:compound"),

  CONCRETE("minecraft:concrete"),

  CONCRETE_POWDER("minecraft:concrete_powder"),

  CONDUIT("minecraft:conduit"),

  COOKED_BEEF("minecraft:cooked_beef"),

  COOKED_CHICKEN("minecraft:cooked_chicken"),

  COOKED_COD("minecraft:cooked_cod"),

  COOKED_MUTTON("minecraft:cooked_mutton"),

  COOKED_PORKCHOP("minecraft:cooked_porkchop"),

  COOKED_RABBIT("minecraft:cooked_rabbit"),

  COOKED_SALMON("minecraft:cooked_salmon"),

  COOKIE("minecraft:cookie"),

  COPPER_BLOCK("minecraft:copper_block"),

  COPPER_INGOT("minecraft:copper_ingot"),

  COPPER_ORE("minecraft:copper_ore"),

  CORAL("minecraft:coral"),

  CORAL_BLOCK("minecraft:coral_block"),

  CORAL_FAN("minecraft:coral_fan"),

  CORAL_FAN_DEAD("minecraft:coral_fan_dead"),

  CORAL_FAN_HANG("minecraft:coral_fan_hang"),

  CORAL_FAN_HANG2("minecraft:coral_fan_hang2"),

  CORAL_FAN_HANG3("minecraft:coral_fan_hang3"),

  COW_SPAWN_EGG("minecraft:cow_spawn_egg"),

  CRACKED_DEEPSLATE_BRICKS("minecraft:cracked_deepslate_bricks"),

  CRACKED_DEEPSLATE_TILES("minecraft:cracked_deepslate_tiles"),

  CRACKED_NETHER_BRICKS("minecraft:cracked_nether_bricks"),

  CRACKED_POLISHED_BLACKSTONE_BRICKS("minecraft:cracked_polished_blackstone_bricks"),

  CRAFTING_TABLE("minecraft:crafting_table"),

  CREEPER_BANNER_PATTERN("minecraft:creeper_banner_pattern"),

  CREEPER_SPAWN_EGG("minecraft:creeper_spawn_egg"),

  CRIMSON_BUTTON("minecraft:crimson_button"),

  CRIMSON_DOOR("minecraft:crimson_door"),

  CRIMSON_DOUBLE_SLAB("minecraft:crimson_double_slab"),

  CRIMSON_FENCE("minecraft:crimson_fence"),

  CRIMSON_FENCE_GATE("minecraft:crimson_fence_gate"),

  CRIMSON_FUNGUS("minecraft:crimson_fungus"),

  CRIMSON_HANGING_SIGN("minecraft:crimson_hanging_sign"),

  CRIMSON_HYPHAE("minecraft:crimson_hyphae"),

  CRIMSON_NYLIUM("minecraft:crimson_nylium"),

  CRIMSON_PLANKS("minecraft:crimson_planks"),

  CRIMSON_PRESSURE_PLATE("minecraft:crimson_pressure_plate"),

  CRIMSON_ROOTS("minecraft:crimson_roots"),

  CRIMSON_SIGN("minecraft:crimson_sign"),

  CRIMSON_SLAB("minecraft:crimson_slab"),

  CRIMSON_STAIRS("minecraft:crimson_stairs"),

  CRIMSON_STANDING_SIGN("minecraft:crimson_standing_sign"),

  CRIMSON_STEM("minecraft:crimson_stem"),

  CRIMSON_TRAPDOOR("minecraft:crimson_trapdoor"),

  CRIMSON_WALL_SIGN("minecraft:crimson_wall_sign"),

  CROSSBOW("minecraft:crossbow"),

  CRYING_OBSIDIAN("minecraft:crying_obsidian"),

  CUT_COPPER("minecraft:cut_copper"),

  CUT_COPPER_SLAB("minecraft:cut_copper_slab"),

  CUT_COPPER_STAIRS("minecraft:cut_copper_stairs"),

  CYAN_CANDLE("minecraft:cyan_candle"),

  CYAN_CANDLE_CAKE("minecraft:cyan_candle_cake"),

  CYAN_DYE("minecraft:cyan_dye"),

  CYAN_GLAZED_TERRACOTTA("minecraft:cyan_glazed_terracotta"),

  CYAN_WOOL("minecraft:cyan_wool"),

  DANGER_POTTERY_SHARD("minecraft:danger_pottery_shard"),

  DARK_OAK_BOAT("minecraft:dark_oak_boat"),

  DARK_OAK_BUTTON("minecraft:dark_oak_button"),

  DARK_OAK_CHEST_BOAT("minecraft:dark_oak_chest_boat"),

  DARK_OAK_DOOR("minecraft:dark_oak_door"),

  DARK_OAK_FENCE("minecraft:dark_oak_fence"),

  DARK_OAK_FENCE_GATE("minecraft:dark_oak_fence_gate"),

  DARK_OAK_HANGING_SIGN("minecraft:dark_oak_hanging_sign"),

  DARK_OAK_LOG("minecraft:dark_oak_log"),

  DARK_OAK_PRESSURE_PLATE("minecraft:dark_oak_pressure_plate"),

  DARK_OAK_SIGN("minecraft:dark_oak_sign"),

  DARK_OAK_STAIRS("minecraft:dark_oak_stairs"),

  DARK_OAK_TRAPDOOR("minecraft:dark_oak_trapdoor"),

  DARK_PRISMARINE_STAIRS("minecraft:dark_prismarine_stairs"),

  DARKOAK_STANDING_SIGN("minecraft:darkoak_standing_sign"),

  DARKOAK_WALL_SIGN("minecraft:darkoak_wall_sign"),

  DAYLIGHT_DETECTOR("minecraft:daylight_detector"),

  DAYLIGHT_DETECTOR_INVERTED("minecraft:daylight_detector_inverted"),

  DEADBUSH("minecraft:deadbush"),

  DECORATED_POT("minecraft:decorated_pot"),

  DEEPSLATE("minecraft:deepslate"),

  DEEPSLATE_BRICK_DOUBLE_SLAB("minecraft:deepslate_brick_double_slab"),

  DEEPSLATE_BRICK_SLAB("minecraft:deepslate_brick_slab"),

  DEEPSLATE_BRICK_STAIRS("minecraft:deepslate_brick_stairs"),

  DEEPSLATE_BRICK_WALL("minecraft:deepslate_brick_wall"),

  DEEPSLATE_BRICKS("minecraft:deepslate_bricks"),

  DEEPSLATE_COAL_ORE("minecraft:deepslate_coal_ore"),

  DEEPSLATE_COPPER_ORE("minecraft:deepslate_copper_ore"),

  DEEPSLATE_DIAMOND_ORE("minecraft:deepslate_diamond_ore"),

  DEEPSLATE_EMERALD_ORE("minecraft:deepslate_emerald_ore"),

  DEEPSLATE_GOLD_ORE("minecraft:deepslate_gold_ore"),

  DEEPSLATE_IRON_ORE("minecraft:deepslate_iron_ore"),

  DEEPSLATE_LAPIS_ORE("minecraft:deepslate_lapis_ore"),

  DEEPSLATE_REDSTONE_ORE("minecraft:deepslate_redstone_ore"),

  DEEPSLATE_TILE_DOUBLE_SLAB("minecraft:deepslate_tile_double_slab"),

  DEEPSLATE_TILE_SLAB("minecraft:deepslate_tile_slab"),

  DEEPSLATE_TILE_STAIRS("minecraft:deepslate_tile_stairs"),

  DEEPSLATE_TILE_WALL("minecraft:deepslate_tile_wall"),

  DEEPSLATE_TILES("minecraft:deepslate_tiles"),

  DENY("minecraft:deny"),

  DETECTOR_RAIL("minecraft:detector_rail"),

  DIAMOND("minecraft:diamond"),

  DIAMOND_AXE("minecraft:diamond_axe"),

  DIAMOND_BLOCK("minecraft:diamond_block"),

  DIAMOND_BOOTS("minecraft:diamond_boots"),

  DIAMOND_CHESTPLATE("minecraft:diamond_chestplate"),

  DIAMOND_HELMET("minecraft:diamond_helmet"),

  DIAMOND_HOE("minecraft:diamond_hoe"),

  DIAMOND_HORSE_ARMOR("minecraft:diamond_horse_armor"),

  DIAMOND_LEGGINGS("minecraft:diamond_leggings"),

  DIAMOND_ORE("minecraft:diamond_ore"),

  DIAMOND_PICKAXE("minecraft:diamond_pickaxe"),

  DIAMOND_SHOVEL("minecraft:diamond_shovel"),

  DIAMOND_SWORD("minecraft:diamond_sword"),

  DIORITE_STAIRS("minecraft:diorite_stairs"),

  DIRT("minecraft:dirt"),

  DIRT_WITH_ROOTS("minecraft:dirt_with_roots"),

  DISC_FRAGMENT_5("minecraft:disc_fragment_5"),

  DISPENSER("minecraft:dispenser"),

  DOLPHIN_SPAWN_EGG("minecraft:dolphin_spawn_egg"),

  DONKEY_SPAWN_EGG("minecraft:donkey_spawn_egg"),

  DOUBLE_CUT_COPPER_SLAB("minecraft:double_cut_copper_slab"),

  DOUBLE_PLANT("minecraft:double_plant"),

  DOUBLE_STONE_BLOCK_SLAB("minecraft:double_stone_block_slab"),

  DOUBLE_STONE_BLOCK_SLAB2("minecraft:double_stone_block_slab2"),

  DOUBLE_STONE_BLOCK_SLAB3("minecraft:double_stone_block_slab3"),

  DOUBLE_STONE_BLOCK_SLAB4("minecraft:double_stone_block_slab4"),

  DOUBLE_WOODEN_SLAB("minecraft:double_wooden_slab"),

  DRAGON_BREATH("minecraft:dragon_breath"),

  DRAGON_EGG("minecraft:dragon_egg"),

  DRIED_KELP("minecraft:dried_kelp"),

  DRIED_KELP_BLOCK("minecraft:dried_kelp_block"),

  DRIPSTONE_BLOCK("minecraft:dripstone_block"),

  DROPPER("minecraft:dropper"),

  DROWNED_SPAWN_EGG("minecraft:drowned_spawn_egg"),

  DUNE_ARMOR_TRIM_SMITHING_TEMPLATE("minecraft:dune_armor_trim_smithing_template"),

  DYE("minecraft:dye"),

  ECHO_SHARD("minecraft:echo_shard"),

  EGG("minecraft:egg"),

  ELDER_GUARDIAN_SPAWN_EGG("minecraft:elder_guardian_spawn_egg"),

  ELEMENT_0("minecraft:element_0"),

  ELEMENT_1("minecraft:element_1"),

  ELEMENT_10("minecraft:element_10"),

  ELEMENT_100("minecraft:element_100"),

  ELEMENT_101("minecraft:element_101"),

  ELEMENT_102("minecraft:element_102"),

  ELEMENT_103("minecraft:element_103"),

  ELEMENT_104("minecraft:element_104"),

  ELEMENT_105("minecraft:element_105"),

  ELEMENT_106("minecraft:element_106"),

  ELEMENT_107("minecraft:element_107"),

  ELEMENT_108("minecraft:element_108"),

  ELEMENT_109("minecraft:element_109"),

  ELEMENT_11("minecraft:element_11"),

  ELEMENT_110("minecraft:element_110"),

  ELEMENT_111("minecraft:element_111"),

  ELEMENT_112("minecraft:element_112"),

  ELEMENT_113("minecraft:element_113"),

  ELEMENT_114("minecraft:element_114"),

  ELEMENT_115("minecraft:element_115"),

  ELEMENT_116("minecraft:element_116"),

  ELEMENT_117("minecraft:element_117"),

  ELEMENT_118("minecraft:element_118"),

  ELEMENT_12("minecraft:element_12"),

  ELEMENT_13("minecraft:element_13"),

  ELEMENT_14("minecraft:element_14"),

  ELEMENT_15("minecraft:element_15"),

  ELEMENT_16("minecraft:element_16"),

  ELEMENT_17("minecraft:element_17"),

  ELEMENT_18("minecraft:element_18"),

  ELEMENT_19("minecraft:element_19"),

  ELEMENT_2("minecraft:element_2"),

  ELEMENT_20("minecraft:element_20"),

  ELEMENT_21("minecraft:element_21"),

  ELEMENT_22("minecraft:element_22"),

  ELEMENT_23("minecraft:element_23"),

  ELEMENT_24("minecraft:element_24"),

  ELEMENT_25("minecraft:element_25"),

  ELEMENT_26("minecraft:element_26"),

  ELEMENT_27("minecraft:element_27"),

  ELEMENT_28("minecraft:element_28"),

  ELEMENT_29("minecraft:element_29"),

  ELEMENT_3("minecraft:element_3"),

  ELEMENT_30("minecraft:element_30"),

  ELEMENT_31("minecraft:element_31"),

  ELEMENT_32("minecraft:element_32"),

  ELEMENT_33("minecraft:element_33"),

  ELEMENT_34("minecraft:element_34"),

  ELEMENT_35("minecraft:element_35"),

  ELEMENT_36("minecraft:element_36"),

  ELEMENT_37("minecraft:element_37"),

  ELEMENT_38("minecraft:element_38"),

  ELEMENT_39("minecraft:element_39"),

  ELEMENT_4("minecraft:element_4"),

  ELEMENT_40("minecraft:element_40"),

  ELEMENT_41("minecraft:element_41"),

  ELEMENT_42("minecraft:element_42"),

  ELEMENT_43("minecraft:element_43"),

  ELEMENT_44("minecraft:element_44"),

  ELEMENT_45("minecraft:element_45"),

  ELEMENT_46("minecraft:element_46"),

  ELEMENT_47("minecraft:element_47"),

  ELEMENT_48("minecraft:element_48"),

  ELEMENT_49("minecraft:element_49"),

  ELEMENT_5("minecraft:element_5"),

  ELEMENT_50("minecraft:element_50"),

  ELEMENT_51("minecraft:element_51"),

  ELEMENT_52("minecraft:element_52"),

  ELEMENT_53("minecraft:element_53"),

  ELEMENT_54("minecraft:element_54"),

  ELEMENT_55("minecraft:element_55"),

  ELEMENT_56("minecraft:element_56"),

  ELEMENT_57("minecraft:element_57"),

  ELEMENT_58("minecraft:element_58"),

  ELEMENT_59("minecraft:element_59"),

  ELEMENT_6("minecraft:element_6"),

  ELEMENT_60("minecraft:element_60"),

  ELEMENT_61("minecraft:element_61"),

  ELEMENT_62("minecraft:element_62"),

  ELEMENT_63("minecraft:element_63"),

  ELEMENT_64("minecraft:element_64"),

  ELEMENT_65("minecraft:element_65"),

  ELEMENT_66("minecraft:element_66"),

  ELEMENT_67("minecraft:element_67"),

  ELEMENT_68("minecraft:element_68"),

  ELEMENT_69("minecraft:element_69"),

  ELEMENT_7("minecraft:element_7"),

  ELEMENT_70("minecraft:element_70"),

  ELEMENT_71("minecraft:element_71"),

  ELEMENT_72("minecraft:element_72"),

  ELEMENT_73("minecraft:element_73"),

  ELEMENT_74("minecraft:element_74"),

  ELEMENT_75("minecraft:element_75"),

  ELEMENT_76("minecraft:element_76"),

  ELEMENT_77("minecraft:element_77"),

  ELEMENT_78("minecraft:element_78"),

  ELEMENT_79("minecraft:element_79"),

  ELEMENT_8("minecraft:element_8"),

  ELEMENT_80("minecraft:element_80"),

  ELEMENT_81("minecraft:element_81"),

  ELEMENT_82("minecraft:element_82"),

  ELEMENT_83("minecraft:element_83"),

  ELEMENT_84("minecraft:element_84"),

  ELEMENT_85("minecraft:element_85"),

  ELEMENT_86("minecraft:element_86"),

  ELEMENT_87("minecraft:element_87"),

  ELEMENT_88("minecraft:element_88"),

  ELEMENT_89("minecraft:element_89"),

  ELEMENT_9("minecraft:element_9"),

  ELEMENT_90("minecraft:element_90"),

  ELEMENT_91("minecraft:element_91"),

  ELEMENT_92("minecraft:element_92"),

  ELEMENT_93("minecraft:element_93"),

  ELEMENT_94("minecraft:element_94"),

  ELEMENT_95("minecraft:element_95"),

  ELEMENT_96("minecraft:element_96"),

  ELEMENT_97("minecraft:element_97"),

  ELEMENT_98("minecraft:element_98"),

  ELEMENT_99("minecraft:element_99"),

  ELYTRA("minecraft:elytra"),

  EMERALD("minecraft:emerald"),

  EMERALD_BLOCK("minecraft:emerald_block"),

  EMERALD_ORE("minecraft:emerald_ore"),

  EMPTY_MAP("minecraft:empty_map"),

  ENCHANTED_BOOK("minecraft:enchanted_book"),

  ENCHANTED_GOLDEN_APPLE("minecraft:enchanted_golden_apple"),

  ENCHANTING_TABLE("minecraft:enchanting_table"),

  END_BRICK_STAIRS("minecraft:end_brick_stairs"),

  END_BRICKS("minecraft:end_bricks"),

  END_CRYSTAL("minecraft:end_crystal"),

  END_GATEWAY("minecraft:end_gateway"),

  END_PORTAL("minecraft:end_portal"),

  END_PORTAL_FRAME("minecraft:end_portal_frame"),

  END_ROD("minecraft:end_rod"),

  END_STONE("minecraft:end_stone"),

  ENDER_CHEST("minecraft:ender_chest"),

  ENDER_DRAGON_SPAWN_EGG("minecraft:ender_dragon_spawn_egg"),

  ENDER_EYE("minecraft:ender_eye"),

  ENDER_PEARL("minecraft:ender_pearl"),

  ENDERMAN_SPAWN_EGG("minecraft:enderman_spawn_egg"),

  ENDERMITE_SPAWN_EGG("minecraft:endermite_spawn_egg"),

  EVOKER_SPAWN_EGG("minecraft:evoker_spawn_egg"),

  EXPERIENCE_BOTTLE("minecraft:experience_bottle"),

  EXPLORER_POTTERY_SHARD("minecraft:explorer_pottery_shard"),

  EXPOSED_COPPER("minecraft:exposed_copper"),

  EXPOSED_CUT_COPPER("minecraft:exposed_cut_copper"),

  EXPOSED_CUT_COPPER_SLAB("minecraft:exposed_cut_copper_slab"),

  EXPOSED_CUT_COPPER_STAIRS("minecraft:exposed_cut_copper_stairs"),

  EXPOSED_DOUBLE_CUT_COPPER_SLAB("minecraft:exposed_double_cut_copper_slab"),

  EYE_ARMOR_TRIM_SMITHING_TEMPLATE("minecraft:eye_armor_trim_smithing_template"),

  FARMLAND("minecraft:farmland"),

  FEATHER("minecraft:feather"),

  FENCE("minecraft:fence"),

  FENCE_GATE("minecraft:fence_gate"),

  FERMENTED_SPIDER_EYE("minecraft:fermented_spider_eye"),

  FIELD_MASONED_BANNER_PATTERN("minecraft:field_masoned_banner_pattern"),

  FILLED_MAP("minecraft:filled_map"),

  FIRE("minecraft:fire"),

  FIRE_CHARGE("minecraft:fire_charge"),

  FIREWORK_ROCKET("minecraft:firework_rocket"),

  FIREWORK_STAR("minecraft:firework_star"),

  FISHING_ROD("minecraft:fishing_rod"),

  FLETCHING_TABLE("minecraft:fletching_table"),

  FLINT("minecraft:flint"),

  FLINT_AND_STEEL("minecraft:flint_and_steel"),

  FLOWER_BANNER_PATTERN("minecraft:flower_banner_pattern"),

  FLOWER_POT("minecraft:flower_pot"),

  FLOWERING_AZALEA("minecraft:flowering_azalea"),

  FLOWING_LAVA("minecraft:flowing_lava"),

  FLOWING_WATER("minecraft:flowing_water"),

  FOX_SPAWN_EGG("minecraft:fox_spawn_egg"),

  FRAME("minecraft:frame"),

  FRIEND_POTTERY_SHARD("minecraft:friend_pottery_shard"),

  FROG_SPAWN("minecraft:frog_spawn"),

  FROG_SPAWN_EGG("minecraft:frog_spawn_egg"),

  FROSTED_ICE("minecraft:frosted_ice"),

  FURNACE("minecraft:furnace"),

  GHAST_SPAWN_EGG("minecraft:ghast_spawn_egg"),

  GHAST_TEAR("minecraft:ghast_tear"),

  GILDED_BLACKSTONE("minecraft:gilded_blackstone"),

  GLASS("minecraft:glass"),

  GLASS_BOTTLE("minecraft:glass_bottle"),

  GLASS_PANE("minecraft:glass_pane"),

  GLISTERING_MELON_SLICE("minecraft:glistering_melon_slice"),

  GLOBE_BANNER_PATTERN("minecraft:globe_banner_pattern"),

  GLOW_BERRIES("minecraft:glow_berries"),

  GLOW_FRAME("minecraft:glow_frame"),

  GLOW_INK_SAC("minecraft:glow_ink_sac"),

  GLOW_LICHEN("minecraft:glow_lichen"),

  GLOW_SQUID_SPAWN_EGG("minecraft:glow_squid_spawn_egg"),

  GLOW_STICK("minecraft:glow_stick"),

  GLOWINGOBSIDIAN("minecraft:glowingobsidian"),

  GLOWSTONE("minecraft:glowstone"),

  GLOWSTONE_DUST("minecraft:glowstone_dust"),

  GOAT_HORN("minecraft:goat_horn"),

  GOAT_SPAWN_EGG("minecraft:goat_spawn_egg"),

  GOLD_BLOCK("minecraft:gold_block"),

  GOLD_INGOT("minecraft:gold_ingot"),

  GOLD_NUGGET("minecraft:gold_nugget"),

  GOLD_ORE("minecraft:gold_ore"),

  GOLDEN_APPLE("minecraft:golden_apple"),

  GOLDEN_AXE("minecraft:golden_axe"),

  GOLDEN_BOOTS("minecraft:golden_boots"),

  GOLDEN_CARROT("minecraft:golden_carrot"),

  GOLDEN_CHESTPLATE("minecraft:golden_chestplate"),

  GOLDEN_HELMET("minecraft:golden_helmet"),

  GOLDEN_HOE("minecraft:golden_hoe"),

  GOLDEN_HORSE_ARMOR("minecraft:golden_horse_armor"),

  GOLDEN_LEGGINGS("minecraft:golden_leggings"),

  GOLDEN_PICKAXE("minecraft:golden_pickaxe"),

  GOLDEN_RAIL("minecraft:golden_rail"),

  GOLDEN_SHOVEL("minecraft:golden_shovel"),

  GOLDEN_SWORD("minecraft:golden_sword"),

  GRANITE_STAIRS("minecraft:granite_stairs"),

  GRASS("minecraft:grass"),

  GRASS_PATH("minecraft:grass_path"),

  GRAVEL("minecraft:gravel"),

  GRAY_CANDLE("minecraft:gray_candle"),

  GRAY_CANDLE_CAKE("minecraft:gray_candle_cake"),

  GRAY_DYE("minecraft:gray_dye"),

  GRAY_GLAZED_TERRACOTTA("minecraft:gray_glazed_terracotta"),

  GRAY_WOOL("minecraft:gray_wool"),

  GREEN_CANDLE("minecraft:green_candle"),

  GREEN_CANDLE_CAKE("minecraft:green_candle_cake"),

  GREEN_DYE("minecraft:green_dye"),

  GREEN_GLAZED_TERRACOTTA("minecraft:green_glazed_terracotta"),

  GREEN_WOOL("minecraft:green_wool"),

  GRINDSTONE("minecraft:grindstone"),

  GUARDIAN_SPAWN_EGG("minecraft:guardian_spawn_egg"),

  GUNPOWDER("minecraft:gunpowder"),

  HANGING_ROOTS("minecraft:hanging_roots"),

  HARD_GLASS("minecraft:hard_glass"),

  HARD_GLASS_PANE("minecraft:hard_glass_pane"),

  HARD_STAINED_GLASS("minecraft:hard_stained_glass"),

  HARD_STAINED_GLASS_PANE("minecraft:hard_stained_glass_pane"),

  HARDENED_CLAY("minecraft:hardened_clay"),

  HAY_BLOCK("minecraft:hay_block"),

  HEART_OF_THE_SEA("minecraft:heart_of_the_sea"),

  HEART_POTTERY_SHARD("minecraft:heart_pottery_shard"),

  HEARTBREAK_POTTERY_SHARD("minecraft:heartbreak_pottery_shard"),

  HEAVY_WEIGHTED_PRESSURE_PLATE("minecraft:heavy_weighted_pressure_plate"),

  HOGLIN_SPAWN_EGG("minecraft:hoglin_spawn_egg"),

  HONEY_BLOCK("minecraft:honey_block"),

  HONEY_BOTTLE("minecraft:honey_bottle"),

  HONEYCOMB("minecraft:honeycomb"),

  HONEYCOMB_BLOCK("minecraft:honeycomb_block"),

  HOPPER("minecraft:hopper"),

  HOPPER_MINECART("minecraft:hopper_minecart"),

  HORSE_SPAWN_EGG("minecraft:horse_spawn_egg"),

  HOST_ARMOR_TRIM_SMITHING_TEMPLATE("minecraft:host_armor_trim_smithing_template"),

  HOWL_POTTERY_SHARD("minecraft:howl_pottery_shard"),

  HUSK_SPAWN_EGG("minecraft:husk_spawn_egg"),

  ICE("minecraft:ice"),

  ICE_BOMB("minecraft:ice_bomb"),

  INFESTED_DEEPSLATE("minecraft:infested_deepslate"),

  INFO_UPDATE("minecraft:info_update"),

  INFO_UPDATE2("minecraft:info_update2"),

  INK_SAC("minecraft:ink_sac"),

  INVISIBLE_BEDROCK("minecraft:invisible_bedrock"),

  IRON_AXE("minecraft:iron_axe"),

  IRON_BARS("minecraft:iron_bars"),

  IRON_BLOCK("minecraft:iron_block"),

  IRON_BOOTS("minecraft:iron_boots"),

  IRON_CHESTPLATE("minecraft:iron_chestplate"),

  IRON_DOOR("minecraft:iron_door"),

  IRON_GOLEM_SPAWN_EGG("minecraft:iron_golem_spawn_egg"),

  IRON_HELMET("minecraft:iron_helmet"),

  IRON_HOE("minecraft:iron_hoe"),

  IRON_HORSE_ARMOR("minecraft:iron_horse_armor"),

  IRON_INGOT("minecraft:iron_ingot"),

  IRON_LEGGINGS("minecraft:iron_leggings"),

  IRON_NUGGET("minecraft:iron_nugget"),

  IRON_ORE("minecraft:iron_ore"),

  IRON_PICKAXE("minecraft:iron_pickaxe"),

  IRON_SHOVEL("minecraft:iron_shovel"),

  IRON_SWORD("minecraft:iron_sword"),

  IRON_TRAPDOOR("minecraft:iron_trapdoor"),

  ITEM_ACACIA_DOOR("minecraft:item.acacia_door"),

  ITEM_BED("minecraft:item.bed"),

  ITEM_BEETROOT("minecraft:item.beetroot"),

  ITEM_BIRCH_DOOR("minecraft:item.birch_door"),

  ITEM_BREWING_STAND("minecraft:item.brewing_stand"),

  ITEM_CAKE("minecraft:item.cake"),

  ITEM_CAMERA("minecraft:item.camera"),

  ITEM_CAMPFIRE("minecraft:item.campfire"),

  ITEM_CAULDRON("minecraft:item.cauldron"),

  ITEM_CHAIN("minecraft:item.chain"),

  ITEM_CRIMSON_DOOR("minecraft:item.crimson_door"),

  ITEM_DARK_OAK_DOOR("minecraft:item.dark_oak_door"),

  ITEM_FLOWER_POT("minecraft:item.flower_pot"),

  ITEM_FRAME("minecraft:item.frame"),

  ITEM_GLOW_FRAME("minecraft:item.glow_frame"),

  ITEM_HOPPER("minecraft:item.hopper"),

  ITEM_IRON_DOOR("minecraft:item.iron_door"),

  ITEM_JUNGLE_DOOR("minecraft:item.jungle_door"),

  ITEM_KELP("minecraft:item.kelp"),

  ITEM_MANGROVE_DOOR("minecraft:item.mangrove_door"),

  ITEM_NETHER_SPROUTS("minecraft:item.nether_sprouts"),

  ITEM_NETHER_WART("minecraft:item.nether_wart"),

  ITEM_REEDS("minecraft:item.reeds"),

  ITEM_SKULL("minecraft:item.skull"),

  ITEM_SOUL_CAMPFIRE("minecraft:item.soul_campfire"),

  ITEM_SPRUCE_DOOR("minecraft:item.spruce_door"),

  ITEM_WARPED_DOOR("minecraft:item.warped_door"),

  ITEM_WHEAT("minecraft:item.wheat"),

  ITEM_WOODEN_DOOR("minecraft:item.wooden_door"),

  JIGSAW("minecraft:jigsaw"),

  JUKEBOX("minecraft:jukebox"),

  JUNGLE_BOAT("minecraft:jungle_boat"),

  JUNGLE_BUTTON("minecraft:jungle_button"),

  JUNGLE_CHEST_BOAT("minecraft:jungle_chest_boat"),

  JUNGLE_DOOR("minecraft:jungle_door"),

  JUNGLE_FENCE("minecraft:jungle_fence"),

  JUNGLE_FENCE_GATE("minecraft:jungle_fence_gate"),

  JUNGLE_HANGING_SIGN("minecraft:jungle_hanging_sign"),

  JUNGLE_LOG("minecraft:jungle_log"),

  JUNGLE_PRESSURE_PLATE("minecraft:jungle_pressure_plate"),

  JUNGLE_SIGN("minecraft:jungle_sign"),

  JUNGLE_STAIRS("minecraft:jungle_stairs"),

  JUNGLE_STANDING_SIGN("minecraft:jungle_standing_sign"),

  JUNGLE_TRAPDOOR("minecraft:jungle_trapdoor"),

  JUNGLE_WALL_SIGN("minecraft:jungle_wall_sign"),

  KELP("minecraft:kelp"),

  LADDER("minecraft:ladder"),

  LANTERN("minecraft:lantern"),

  LAPIS_BLOCK("minecraft:lapis_block"),

  LAPIS_LAZULI("minecraft:lapis_lazuli"),

  LAPIS_ORE("minecraft:lapis_ore"),

  LARGE_AMETHYST_BUD("minecraft:large_amethyst_bud"),

  LAVA("minecraft:lava"),

  LAVA_BUCKET("minecraft:lava_bucket"),

  LAVA_CAULDRON("minecraft:lava_cauldron"),

  LEAD("minecraft:lead"),

  LEATHER("minecraft:leather"),

  LEATHER_BOOTS("minecraft:leather_boots"),

  LEATHER_CHESTPLATE("minecraft:leather_chestplate"),

  LEATHER_HELMET("minecraft:leather_helmet"),

  LEATHER_HORSE_ARMOR("minecraft:leather_horse_armor"),

  LEATHER_LEGGINGS("minecraft:leather_leggings"),

  LEAVES("minecraft:leaves"),

  LEAVES2("minecraft:leaves2"),

  LECTERN("minecraft:lectern"),

  LEVER("minecraft:lever"),

  LIGHT_BLOCK("minecraft:light_block"),

  LIGHT_BLUE_CANDLE("minecraft:light_blue_candle"),

  LIGHT_BLUE_CANDLE_CAKE("minecraft:light_blue_candle_cake"),

  LIGHT_BLUE_DYE("minecraft:light_blue_dye"),

  LIGHT_BLUE_GLAZED_TERRACOTTA("minecraft:light_blue_glazed_terracotta"),

  LIGHT_BLUE_WOOL("minecraft:light_blue_wool"),

  LIGHT_GRAY_CANDLE("minecraft:light_gray_candle"),

  LIGHT_GRAY_CANDLE_CAKE("minecraft:light_gray_candle_cake"),

  LIGHT_GRAY_DYE("minecraft:light_gray_dye"),

  LIGHT_GRAY_WOOL("minecraft:light_gray_wool"),

  LIGHT_WEIGHTED_PRESSURE_PLATE("minecraft:light_weighted_pressure_plate"),

  LIGHTNING_ROD("minecraft:lightning_rod"),

  LIME_CANDLE("minecraft:lime_candle"),

  LIME_CANDLE_CAKE("minecraft:lime_candle_cake"),

  LIME_DYE("minecraft:lime_dye"),

  LIME_GLAZED_TERRACOTTA("minecraft:lime_glazed_terracotta"),

  LIME_WOOL("minecraft:lime_wool"),

  LINGERING_POTION("minecraft:lingering_potion"),

  LIT_BLAST_FURNACE("minecraft:lit_blast_furnace"),

  LIT_DEEPSLATE_REDSTONE_ORE("minecraft:lit_deepslate_redstone_ore"),

  LIT_FURNACE("minecraft:lit_furnace"),

  LIT_PUMPKIN("minecraft:lit_pumpkin"),

  LIT_REDSTONE_LAMP("minecraft:lit_redstone_lamp"),

  LIT_REDSTONE_ORE("minecraft:lit_redstone_ore"),

  LIT_SMOKER("minecraft:lit_smoker"),

  LLAMA_SPAWN_EGG("minecraft:llama_spawn_egg"),

  LODESTONE("minecraft:lodestone"),

  LODESTONE_COMPASS("minecraft:lodestone_compass"),

  LOG("minecraft:log"),

  LOG2("minecraft:log2"),

  LOOM("minecraft:loom"),

  MAGENTA_CANDLE("minecraft:magenta_candle"),

  MAGENTA_CANDLE_CAKE("minecraft:magenta_candle_cake"),

  MAGENTA_DYE("minecraft:magenta_dye"),

  MAGENTA_GLAZED_TERRACOTTA("minecraft:magenta_glazed_terracotta"),

  MAGENTA_WOOL("minecraft:magenta_wool"),

  MAGMA("minecraft:magma"),

  MAGMA_CREAM("minecraft:magma_cream"),

  MAGMA_CUBE_SPAWN_EGG("minecraft:magma_cube_spawn_egg"),

  MANGROVE_BOAT("minecraft:mangrove_boat"),

  MANGROVE_BUTTON("minecraft:mangrove_button"),

  MANGROVE_CHEST_BOAT("minecraft:mangrove_chest_boat"),

  MANGROVE_DOOR("minecraft:mangrove_door"),

  MANGROVE_DOUBLE_SLAB("minecraft:mangrove_double_slab"),

  MANGROVE_FENCE("minecraft:mangrove_fence"),

  MANGROVE_FENCE_GATE("minecraft:mangrove_fence_gate"),

  MANGROVE_HANGING_SIGN("minecraft:mangrove_hanging_sign"),

  MANGROVE_LEAVES("minecraft:mangrove_leaves"),

  MANGROVE_LOG("minecraft:mangrove_log"),

  MANGROVE_PLANKS("minecraft:mangrove_planks"),

  MANGROVE_PRESSURE_PLATE("minecraft:mangrove_pressure_plate"),

  MANGROVE_PROPAGULE("minecraft:mangrove_propagule"),

  MANGROVE_ROOTS("minecraft:mangrove_roots"),

  MANGROVE_SIGN("minecraft:mangrove_sign"),

  MANGROVE_SLAB("minecraft:mangrove_slab"),

  MANGROVE_STAIRS("minecraft:mangrove_stairs"),

  MANGROVE_STANDING_SIGN("minecraft:mangrove_standing_sign"),

  MANGROVE_TRAPDOOR("minecraft:mangrove_trapdoor"),

  MANGROVE_WALL_SIGN("minecraft:mangrove_wall_sign"),

  MANGROVE_WOOD("minecraft:mangrove_wood"),

  MEDICINE("minecraft:medicine"),

  MEDIUM_AMETHYST_BUD("minecraft:medium_amethyst_bud"),

  MELON_BLOCK("minecraft:melon_block"),

  MELON_SEEDS("minecraft:melon_seeds"),

  MELON_SLICE("minecraft:melon_slice"),

  MELON_STEM("minecraft:melon_stem"),

  MILK_BUCKET("minecraft:milk_bucket"),

  MINECART("minecraft:minecart"),

  MINER_POTTERY_SHARD("minecraft:miner_pottery_shard"),

  MOB_SPAWNER("minecraft:mob_spawner"),

  MOJANG_BANNER_PATTERN("minecraft:mojang_banner_pattern"),

  MONSTER_EGG("minecraft:monster_egg"),

  MOOSHROOM_SPAWN_EGG("minecraft:mooshroom_spawn_egg"),

  MOSS_BLOCK("minecraft:moss_block"),

  MOSS_CARPET("minecraft:moss_carpet"),

  MOSSY_COBBLESTONE("minecraft:mossy_cobblestone"),

  MOSSY_COBBLESTONE_STAIRS("minecraft:mossy_cobblestone_stairs"),

  MOSSY_STONE_BRICK_STAIRS("minecraft:mossy_stone_brick_stairs"),

  MOURNER_POTTERY_SHARD("minecraft:mourner_pottery_shard"),

  MOVING_BLOCK("minecraft:moving_block"),

  MUD("minecraft:mud"),

  MUD_BRICK_DOUBLE_SLAB("minecraft:mud_brick_double_slab"),

  MUD_BRICK_SLAB("minecraft:mud_brick_slab"),

  MUD_BRICK_STAIRS("minecraft:mud_brick_stairs"),

  MUD_BRICK_WALL("minecraft:mud_brick_wall"),

  MUD_BRICKS("minecraft:mud_bricks"),

  MUDDY_MANGROVE_ROOTS("minecraft:muddy_mangrove_roots"),

  MULE_SPAWN_EGG("minecraft:mule_spawn_egg"),

  MUSHROOM_STEW("minecraft:mushroom_stew"),

  MUSIC_DISC_11("minecraft:music_disc_11"),

  MUSIC_DISC_13("minecraft:music_disc_13"),

  MUSIC_DISC_5("minecraft:music_disc_5"),

  MUSIC_DISC_BLOCKS("minecraft:music_disc_blocks"),

  MUSIC_DISC_CAT("minecraft:music_disc_cat"),

  MUSIC_DISC_CHIRP("minecraft:music_disc_chirp"),

  MUSIC_DISC_FAR("minecraft:music_disc_far"),

  MUSIC_DISC_MALL("minecraft:music_disc_mall"),

  MUSIC_DISC_MELLOHI("minecraft:music_disc_mellohi"),

  MUSIC_DISC_OTHERSIDE("minecraft:music_disc_otherside"),

  MUSIC_DISC_PIGSTEP("minecraft:music_disc_pigstep"),

  MUSIC_DISC_STAL("minecraft:music_disc_stal"),

  MUSIC_DISC_STRAD("minecraft:music_disc_strad"),

  MUSIC_DISC_WAIT("minecraft:music_disc_wait"),

  MUSIC_DISC_WARD("minecraft:music_disc_ward"),

  MUTTON("minecraft:mutton"),

  MYCELIUM("minecraft:mycelium"),

  NAME_TAG("minecraft:name_tag"),

  NAUTILUS_SHELL("minecraft:nautilus_shell"),

  NETHER_BRICK("minecraft:nether_brick"),

  NETHER_BRICK_FENCE("minecraft:nether_brick_fence"),

  NETHER_BRICK_STAIRS("minecraft:nether_brick_stairs"),

  NETHER_GOLD_ORE("minecraft:nether_gold_ore"),

  NETHER_SPROUTS("minecraft:nether_sprouts"),

  NETHER_STAR("minecraft:nether_star"),

  NETHER_WART("minecraft:nether_wart"),

  NETHER_WART_BLOCK("minecraft:nether_wart_block"),

  NETHERBRICK("minecraft:netherbrick"),

  NETHERITE_AXE("minecraft:netherite_axe"),

  NETHERITE_BLOCK("minecraft:netherite_block"),

  NETHERITE_BOOTS("minecraft:netherite_boots"),

  NETHERITE_CHESTPLATE("minecraft:netherite_chestplate"),

  NETHERITE_HELMET("minecraft:netherite_helmet"),

  NETHERITE_HOE("minecraft:netherite_hoe"),

  NETHERITE_INGOT("minecraft:netherite_ingot"),

  NETHERITE_LEGGINGS("minecraft:netherite_leggings"),

  NETHERITE_PICKAXE("minecraft:netherite_pickaxe"),

  NETHERITE_SCRAP("minecraft:netherite_scrap"),

  NETHERITE_SHOVEL("minecraft:netherite_shovel"),

  NETHERITE_SWORD("minecraft:netherite_sword"),

  NETHERITE_UPGRADE_SMITHING_TEMPLATE("minecraft:netherite_upgrade_smithing_template"),

  NETHERRACK("minecraft:netherrack"),

  NETHERREACTOR("minecraft:netherreactor"),

  NORMAL_STONE_STAIRS("minecraft:normal_stone_stairs"),

  NOTEBLOCK("minecraft:noteblock"),

  NPC_SPAWN_EGG("minecraft:npc_spawn_egg"),

  OAK_BOAT("minecraft:oak_boat"),

  OAK_CHEST_BOAT("minecraft:oak_chest_boat"),

  OAK_FENCE("minecraft:oak_fence"),

  OAK_HANGING_SIGN("minecraft:oak_hanging_sign"),

  OAK_LOG("minecraft:oak_log"),

  OAK_SIGN("minecraft:oak_sign"),

  OAK_STAIRS("minecraft:oak_stairs"),

  OBSERVER("minecraft:observer"),

  OBSIDIAN("minecraft:obsidian"),

  OCELOT_SPAWN_EGG("minecraft:ocelot_spawn_egg"),

  OCHRE_FROGLIGHT("minecraft:ochre_froglight"),

  ORANGE_CANDLE("minecraft:orange_candle"),

  ORANGE_CANDLE_CAKE("minecraft:orange_candle_cake"),

  ORANGE_DYE("minecraft:orange_dye"),

  ORANGE_GLAZED_TERRACOTTA("minecraft:orange_glazed_terracotta"),

  ORANGE_WOOL("minecraft:orange_wool"),

  OXIDIZED_COPPER("minecraft:oxidized_copper"),

  OXIDIZED_CUT_COPPER("minecraft:oxidized_cut_copper"),

  OXIDIZED_CUT_COPPER_SLAB("minecraft:oxidized_cut_copper_slab"),

  OXIDIZED_CUT_COPPER_STAIRS("minecraft:oxidized_cut_copper_stairs"),

  OXIDIZED_DOUBLE_CUT_COPPER_SLAB("minecraft:oxidized_double_cut_copper_slab"),

  PACKED_ICE("minecraft:packed_ice"),

  PACKED_MUD("minecraft:packed_mud"),

  PAINTING("minecraft:painting"),

  PANDA_SPAWN_EGG("minecraft:panda_spawn_egg"),

  PAPER("minecraft:paper"),

  PARROT_SPAWN_EGG("minecraft:parrot_spawn_egg"),

  PEARLESCENT_FROGLIGHT("minecraft:pearlescent_froglight"),

  PHANTOM_MEMBRANE("minecraft:phantom_membrane"),

  PHANTOM_SPAWN_EGG("minecraft:phantom_spawn_egg"),

  PIG_SPAWN_EGG("minecraft:pig_spawn_egg"),

  PIGLIN_BANNER_PATTERN("minecraft:piglin_banner_pattern"),

  PIGLIN_BRUTE_SPAWN_EGG("minecraft:piglin_brute_spawn_egg"),

  PIGLIN_SPAWN_EGG("minecraft:piglin_spawn_egg"),

  PILLAGER_SPAWN_EGG("minecraft:pillager_spawn_egg"),

  PINK_CANDLE("minecraft:pink_candle"),

  PINK_CANDLE_CAKE("minecraft:pink_candle_cake"),

  PINK_DYE("minecraft:pink_dye"),

  PINK_GLAZED_TERRACOTTA("minecraft:pink_glazed_terracotta"),

  PINK_PETALS("minecraft:pink_petals"),

  PINK_WOOL("minecraft:pink_wool"),

  PISTON("minecraft:piston"),

  PISTON_ARM_COLLISION("minecraft:piston_arm_collision"),

  PLANKS("minecraft:planks"),

  PLENTY_POTTERY_SHARD("minecraft:plenty_pottery_shard"),

  PODZOL("minecraft:podzol"),

  POINTED_DRIPSTONE("minecraft:pointed_dripstone"),

  POISONOUS_POTATO("minecraft:poisonous_potato"),

  POLAR_BEAR_SPAWN_EGG("minecraft:polar_bear_spawn_egg"),

  POLISHED_ANDESITE_STAIRS("minecraft:polished_andesite_stairs"),

  POLISHED_BASALT("minecraft:polished_basalt"),

  POLISHED_BLACKSTONE("minecraft:polished_blackstone"),

  POLISHED_BLACKSTONE_BRICK_DOUBLE_SLAB("minecraft:polished_blackstone_brick_double_slab"),

  POLISHED_BLACKSTONE_BRICK_SLAB("minecraft:polished_blackstone_brick_slab"),

  POLISHED_BLACKSTONE_BRICK_STAIRS("minecraft:polished_blackstone_brick_stairs"),

  POLISHED_BLACKSTONE_BRICK_WALL("minecraft:polished_blackstone_brick_wall"),

  POLISHED_BLACKSTONE_BRICKS("minecraft:polished_blackstone_bricks"),

  POLISHED_BLACKSTONE_BUTTON("minecraft:polished_blackstone_button"),

  POLISHED_BLACKSTONE_DOUBLE_SLAB("minecraft:polished_blackstone_double_slab"),

  POLISHED_BLACKSTONE_PRESSURE_PLATE("minecraft:polished_blackstone_pressure_plate"),

  POLISHED_BLACKSTONE_SLAB("minecraft:polished_blackstone_slab"),

  POLISHED_BLACKSTONE_STAIRS("minecraft:polished_blackstone_stairs"),

  POLISHED_BLACKSTONE_WALL("minecraft:polished_blackstone_wall"),

  POLISHED_DEEPSLATE("minecraft:polished_deepslate"),

  POLISHED_DEEPSLATE_DOUBLE_SLAB("minecraft:polished_deepslate_double_slab"),

  POLISHED_DEEPSLATE_SLAB("minecraft:polished_deepslate_slab"),

  POLISHED_DEEPSLATE_STAIRS("minecraft:polished_deepslate_stairs"),

  POLISHED_DEEPSLATE_WALL("minecraft:polished_deepslate_wall"),

  POLISHED_DIORITE_STAIRS("minecraft:polished_diorite_stairs"),

  POLISHED_GRANITE_STAIRS("minecraft:polished_granite_stairs"),

  POPPED_CHORUS_FRUIT("minecraft:popped_chorus_fruit"),

  PORKCHOP("minecraft:porkchop"),

  PORTAL("minecraft:portal"),

  POTATO("minecraft:potato"),

  POTATOES("minecraft:potatoes"),

  POTION("minecraft:potion"),

  POWDER_SNOW("minecraft:powder_snow"),

  POWDER_SNOW_BUCKET("minecraft:powder_snow_bucket"),

  POWERED_COMPARATOR("minecraft:powered_comparator"),

  POWERED_REPEATER("minecraft:powered_repeater"),

  PRISMARINE("minecraft:prismarine"),

  PRISMARINE_BRICKS_STAIRS("minecraft:prismarine_bricks_stairs"),

  PRISMARINE_CRYSTALS("minecraft:prismarine_crystals"),

  PRISMARINE_SHARD("minecraft:prismarine_shard"),

  PRISMARINE_STAIRS("minecraft:prismarine_stairs"),

  PRIZE_POTTERY_SHARD("minecraft:prize_pottery_shard"),

  PUFFERFISH("minecraft:pufferfish"),

  PUFFERFISH_BUCKET("minecraft:pufferfish_bucket"),

  PUFFERFISH_SPAWN_EGG("minecraft:pufferfish_spawn_egg"),

  PUMPKIN("minecraft:pumpkin"),

  PUMPKIN_PIE("minecraft:pumpkin_pie"),

  PUMPKIN_SEEDS("minecraft:pumpkin_seeds"),

  PUMPKIN_STEM("minecraft:pumpkin_stem"),

  PURPLE_CANDLE("minecraft:purple_candle"),

  PURPLE_CANDLE_CAKE("minecraft:purple_candle_cake"),

  PURPLE_DYE("minecraft:purple_dye"),

  PURPLE_GLAZED_TERRACOTTA("minecraft:purple_glazed_terracotta"),

  PURPLE_WOOL("minecraft:purple_wool"),

  PURPUR_BLOCK("minecraft:purpur_block"),

  PURPUR_STAIRS("minecraft:purpur_stairs"),

  QUARTZ("minecraft:quartz"),

  QUARTZ_BLOCK("minecraft:quartz_block"),

  QUARTZ_BRICKS("minecraft:quartz_bricks"),

  QUARTZ_ORE("minecraft:quartz_ore"),

  QUARTZ_STAIRS("minecraft:quartz_stairs"),

  RABBIT("minecraft:rabbit"),

  RABBIT_FOOT("minecraft:rabbit_foot"),

  RABBIT_HIDE("minecraft:rabbit_hide"),

  RABBIT_SPAWN_EGG("minecraft:rabbit_spawn_egg"),

  RABBIT_STEW("minecraft:rabbit_stew"),

  RAIL("minecraft:rail"),

  RAISER_ARMOR_TRIM_SMITHING_TEMPLATE("minecraft:raiser_armor_trim_smithing_template"),

  RAPID_FERTILIZER("minecraft:rapid_fertilizer"),

  RAVAGER_SPAWN_EGG("minecraft:ravager_spawn_egg"),

  RAW_COPPER("minecraft:raw_copper"),

  RAW_COPPER_BLOCK("minecraft:raw_copper_block"),

  RAW_GOLD("minecraft:raw_gold"),

  RAW_GOLD_BLOCK("minecraft:raw_gold_block"),

  RAW_IRON("minecraft:raw_iron"),

  RAW_IRON_BLOCK("minecraft:raw_iron_block"),

  RECOVERY_COMPASS("minecraft:recovery_compass"),

  RED_CANDLE("minecraft:red_candle"),

  RED_CANDLE_CAKE("minecraft:red_candle_cake"),

  RED_DYE("minecraft:red_dye"),

  RED_FLOWER("minecraft:red_flower"),

  RED_GLAZED_TERRACOTTA("minecraft:red_glazed_terracotta"),

  RED_MUSHROOM("minecraft:red_mushroom"),

  RED_MUSHROOM_BLOCK("minecraft:red_mushroom_block"),

  RED_NETHER_BRICK("minecraft:red_nether_brick"),

  RED_NETHER_BRICK_STAIRS("minecraft:red_nether_brick_stairs"),

  RED_SANDSTONE("minecraft:red_sandstone"),

  RED_SANDSTONE_STAIRS("minecraft:red_sandstone_stairs"),

  RED_WOOL("minecraft:red_wool"),

  REDSTONE("minecraft:redstone"),

  REDSTONE_BLOCK("minecraft:redstone_block"),

  REDSTONE_LAMP("minecraft:redstone_lamp"),

  REDSTONE_ORE("minecraft:redstone_ore"),

  REDSTONE_TORCH("minecraft:redstone_torch"),

  REDSTONE_WIRE("minecraft:redstone_wire"),

  REINFORCED_DEEPSLATE("minecraft:reinforced_deepslate"),

  REPEATER("minecraft:repeater"),

  REPEATING_COMMAND_BLOCK("minecraft:repeating_command_block"),

  RESERVED6("minecraft:reserved6"),

  RESPAWN_ANCHOR("minecraft:respawn_anchor"),

  RIB_ARMOR_TRIM_SMITHING_TEMPLATE("minecraft:rib_armor_trim_smithing_template"),

  ROTTEN_FLESH("minecraft:rotten_flesh"),

  SADDLE("minecraft:saddle"),

  SALMON("minecraft:salmon"),

  SALMON_BUCKET("minecraft:salmon_bucket"),

  SALMON_SPAWN_EGG("minecraft:salmon_spawn_egg"),

  SAND("minecraft:sand"),

  SANDSTONE("minecraft:sandstone"),

  SANDSTONE_STAIRS("minecraft:sandstone_stairs"),

  SAPLING("minecraft:sapling"),

  SCAFFOLDING("minecraft:scaffolding"),

  SCULK("minecraft:sculk"),

  SCULK_CATALYST("minecraft:sculk_catalyst"),

  SCULK_SENSOR("minecraft:sculk_sensor"),

  SCULK_SHRIEKER("minecraft:sculk_shrieker"),

  SCULK_VEIN("minecraft:sculk_vein"),

  SCUTE("minecraft:scute"),

  SEA_LANTERN("minecraft:sea_lantern"),

  SEA_PICKLE("minecraft:sea_pickle"),

  SEAGRASS("minecraft:seagrass"),

  SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE("minecraft:sentry_armor_trim_smithing_template"),

  SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE("minecraft:shaper_armor_trim_smithing_template"),

  SHEAF_POTTERY_SHARD("minecraft:sheaf_pottery_shard"),

  SHEARS("minecraft:shears"),

  SHEEP_SPAWN_EGG("minecraft:sheep_spawn_egg"),

  SHELTER_POTTERY_SHARD("minecraft:shelter_pottery_shard"),

  SHIELD("minecraft:shield"),

  SHROOMLIGHT("minecraft:shroomlight"),

  SHULKER_BOX("minecraft:shulker_box"),

  SHULKER_SHELL("minecraft:shulker_shell"),

  SHULKER_SPAWN_EGG("minecraft:shulker_spawn_egg"),

  SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE("minecraft:silence_armor_trim_smithing_template"),

  SILVER_GLAZED_TERRACOTTA("minecraft:silver_glazed_terracotta"),

  SILVERFISH_SPAWN_EGG("minecraft:silverfish_spawn_egg"),

  SKELETON_HORSE_SPAWN_EGG("minecraft:skeleton_horse_spawn_egg"),

  SKELETON_SPAWN_EGG("minecraft:skeleton_spawn_egg"),

  SKULL("minecraft:skull"),

  SKULL_BANNER_PATTERN("minecraft:skull_banner_pattern"),

  SKULL_POTTERY_SHARD("minecraft:skull_pottery_shard"),

  SLIME("minecraft:slime"),

  SLIME_BALL("minecraft:slime_ball"),

  SLIME_SPAWN_EGG("minecraft:slime_spawn_egg"),

  SMALL_AMETHYST_BUD("minecraft:small_amethyst_bud"),

  SMALL_DRIPLEAF_BLOCK("minecraft:small_dripleaf_block"),

  SMITHING_TABLE("minecraft:smithing_table"),

  SMOKER("minecraft:smoker"),

  SMOOTH_BASALT("minecraft:smooth_basalt"),

  SMOOTH_QUARTZ_STAIRS("minecraft:smooth_quartz_stairs"),

  SMOOTH_RED_SANDSTONE_STAIRS("minecraft:smooth_red_sandstone_stairs"),

  SMOOTH_SANDSTONE_STAIRS("minecraft:smooth_sandstone_stairs"),

  SMOOTH_STONE("minecraft:smooth_stone"),

  SNIFFER_SPAWN_EGG("minecraft:sniffer_spawn_egg"),

  SNORT_POTTERY_SHARD("minecraft:snort_pottery_shard"),

  SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE("minecraft:snout_armor_trim_smithing_template"),

  SNOW("minecraft:snow"),

  SNOW_GOLEM_SPAWN_EGG("minecraft:snow_golem_spawn_egg"),

  SNOW_LAYER("minecraft:snow_layer"),

  SNOWBALL("minecraft:snowball"),

  SOUL_CAMPFIRE("minecraft:soul_campfire"),

  SOUL_FIRE("minecraft:soul_fire"),

  SOUL_LANTERN("minecraft:soul_lantern"),

  SOUL_SAND("minecraft:soul_sand"),

  SOUL_SOIL("minecraft:soul_soil"),

  SOUL_TORCH("minecraft:soul_torch"),

  SPARKLER("minecraft:sparkler"),

  SPAWN_EGG("minecraft:spawn_egg"),

  SPIDER_EYE("minecraft:spider_eye"),

  SPIDER_SPAWN_EGG("minecraft:spider_spawn_egg"),

  SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE("minecraft:spire_armor_trim_smithing_template"),

  SPLASH_POTION("minecraft:splash_potion"),

  SPONGE("minecraft:sponge"),

  SPORE_BLOSSOM("minecraft:spore_blossom"),

  SPRUCE_BOAT("minecraft:spruce_boat"),

  SPRUCE_BUTTON("minecraft:spruce_button"),

  SPRUCE_CHEST_BOAT("minecraft:spruce_chest_boat"),

  SPRUCE_DOOR("minecraft:spruce_door"),

  SPRUCE_FENCE("minecraft:spruce_fence"),

  SPRUCE_FENCE_GATE("minecraft:spruce_fence_gate"),

  SPRUCE_HANGING_SIGN("minecraft:spruce_hanging_sign"),

  SPRUCE_LOG("minecraft:spruce_log"),

  SPRUCE_PRESSURE_PLATE("minecraft:spruce_pressure_plate"),

  SPRUCE_SIGN("minecraft:spruce_sign"),

  SPRUCE_STAIRS("minecraft:spruce_stairs"),

  SPRUCE_STANDING_SIGN("minecraft:spruce_standing_sign"),

  SPRUCE_TRAPDOOR("minecraft:spruce_trapdoor"),

  SPRUCE_WALL_SIGN("minecraft:spruce_wall_sign"),

  SPYGLASS("minecraft:spyglass"),

  SQUID_SPAWN_EGG("minecraft:squid_spawn_egg"),

  STAINED_GLASS("minecraft:stained_glass"),

  STAINED_GLASS_PANE("minecraft:stained_glass_pane"),

  STAINED_HARDENED_CLAY("minecraft:stained_hardened_clay"),

  STANDING_BANNER("minecraft:standing_banner"),

  STANDING_SIGN("minecraft:standing_sign"),

  STICK("minecraft:stick"),

  STICKY_PISTON("minecraft:sticky_piston"),

  STICKY_PISTON_ARM_COLLISION("minecraft:sticky_piston_arm_collision"),

  STONE("minecraft:stone"),

  STONE_AXE("minecraft:stone_axe"),

  STONE_BLOCK_SLAB("minecraft:stone_block_slab"),

  STONE_BLOCK_SLAB2("minecraft:stone_block_slab2"),

  STONE_BLOCK_SLAB3("minecraft:stone_block_slab3"),

  STONE_BLOCK_SLAB4("minecraft:stone_block_slab4"),

  STONE_BRICK_STAIRS("minecraft:stone_brick_stairs"),

  STONE_BUTTON("minecraft:stone_button"),

  STONE_HOE("minecraft:stone_hoe"),

  STONE_PICKAXE("minecraft:stone_pickaxe"),

  STONE_PRESSURE_PLATE("minecraft:stone_pressure_plate"),

  STONE_SHOVEL("minecraft:stone_shovel"),

  STONE_STAIRS("minecraft:stone_stairs"),

  STONE_SWORD("minecraft:stone_sword"),

  STONEBRICK("minecraft:stonebrick"),

  STONECUTTER("minecraft:stonecutter"),

  STONECUTTER_BLOCK("minecraft:stonecutter_block"),

  STRAY_SPAWN_EGG("minecraft:stray_spawn_egg"),

  STRIDER_SPAWN_EGG("minecraft:strider_spawn_egg"),

  STRING("minecraft:string"),

  STRIPPED_ACACIA_LOG("minecraft:stripped_acacia_log"),

  STRIPPED_BAMBOO_BLOCK("minecraft:stripped_bamboo_block"),

  STRIPPED_BIRCH_LOG("minecraft:stripped_birch_log"),

  STRIPPED_CHERRY_LOG("minecraft:stripped_cherry_log"),

  STRIPPED_CHERRY_WOOD("minecraft:stripped_cherry_wood"),

  STRIPPED_CRIMSON_HYPHAE("minecraft:stripped_crimson_hyphae"),

  STRIPPED_CRIMSON_STEM("minecraft:stripped_crimson_stem"),

  STRIPPED_DARK_OAK_LOG("minecraft:stripped_dark_oak_log"),

  STRIPPED_JUNGLE_LOG("minecraft:stripped_jungle_log"),

  STRIPPED_MANGROVE_LOG("minecraft:stripped_mangrove_log"),

  STRIPPED_MANGROVE_WOOD("minecraft:stripped_mangrove_wood"),

  STRIPPED_OAK_LOG("minecraft:stripped_oak_log"),

  STRIPPED_SPRUCE_LOG("minecraft:stripped_spruce_log"),

  STRIPPED_WARPED_HYPHAE("minecraft:stripped_warped_hyphae"),

  STRIPPED_WARPED_STEM("minecraft:stripped_warped_stem"),

  STRUCTURE_BLOCK("minecraft:structure_block"),

  STRUCTURE_VOID("minecraft:structure_void"),

  SUGAR("minecraft:sugar"),

  SUGAR_CANE("minecraft:sugar_cane"),

  SUSPICIOUS_GRAVEL("minecraft:suspicious_gravel"),

  SUSPICIOUS_SAND("minecraft:suspicious_sand"),

  SUSPICIOUS_STEW("minecraft:suspicious_stew"),

  SWEET_BERRIES("minecraft:sweet_berries"),

  SWEET_BERRY_BUSH("minecraft:sweet_berry_bush"),

  TADPOLE_BUCKET("minecraft:tadpole_bucket"),

  TADPOLE_SPAWN_EGG("minecraft:tadpole_spawn_egg"),

  TALLGRASS("minecraft:tallgrass"),

  TARGET("minecraft:target"),

  TIDE_ARMOR_TRIM_SMITHING_TEMPLATE("minecraft:tide_armor_trim_smithing_template"),

  TINTED_GLASS("minecraft:tinted_glass"),

  TNT("minecraft:tnt"),

  TNT_MINECART("minecraft:tnt_minecart"),

  TORCH("minecraft:torch"),

  TORCHFLOWER("minecraft:torchflower"),

  TORCHFLOWER_CROP("minecraft:torchflower_crop"),

  TORCHFLOWER_SEEDS("minecraft:torchflower_seeds"),

  TOTEM_OF_UNDYING("minecraft:totem_of_undying"),

  TRADER_LLAMA_SPAWN_EGG("minecraft:trader_llama_spawn_egg"),

  TRAPDOOR("minecraft:trapdoor"),

  TRAPPED_CHEST("minecraft:trapped_chest"),

  TRIDENT("minecraft:trident"),

  TRIP_WIRE("minecraft:trip_wire"),

  TRIPWIRE_HOOK("minecraft:tripwire_hook"),

  TROPICAL_FISH("minecraft:tropical_fish"),

  TROPICAL_FISH_BUCKET("minecraft:tropical_fish_bucket"),

  TROPICAL_FISH_SPAWN_EGG("minecraft:tropical_fish_spawn_egg"),

  TUFF("minecraft:tuff"),

  TURTLE_EGG("minecraft:turtle_egg"),

  TURTLE_HELMET("minecraft:turtle_helmet"),

  TURTLE_SPAWN_EGG("minecraft:turtle_spawn_egg"),

  TWISTING_VINES("minecraft:twisting_vines"),

  UNDERWATER_TORCH("minecraft:underwater_torch"),

  UNDYED_SHULKER_BOX("minecraft:undyed_shulker_box"),

  UNKNOWN("minecraft:unknown"),

  UNLIT_REDSTONE_TORCH("minecraft:unlit_redstone_torch"),

  UNPOWERED_COMPARATOR("minecraft:unpowered_comparator"),

  UNPOWERED_REPEATER("minecraft:unpowered_repeater"),

  VERDANT_FROGLIGHT("minecraft:verdant_froglight"),

  VEX_ARMOR_TRIM_SMITHING_TEMPLATE("minecraft:vex_armor_trim_smithing_template"),

  VEX_SPAWN_EGG("minecraft:vex_spawn_egg"),

  VILLAGER_SPAWN_EGG("minecraft:villager_spawn_egg"),

  VINDICATOR_SPAWN_EGG("minecraft:vindicator_spawn_egg"),

  VINE("minecraft:vine"),

  WALL_BANNER("minecraft:wall_banner"),

  WALL_SIGN("minecraft:wall_sign"),

  WANDERING_TRADER_SPAWN_EGG("minecraft:wandering_trader_spawn_egg"),

  WARD_ARMOR_TRIM_SMITHING_TEMPLATE("minecraft:ward_armor_trim_smithing_template"),

  WARDEN_SPAWN_EGG("minecraft:warden_spawn_egg"),

  WARPED_BUTTON("minecraft:warped_button"),

  WARPED_DOOR("minecraft:warped_door"),

  WARPED_DOUBLE_SLAB("minecraft:warped_double_slab"),

  WARPED_FENCE("minecraft:warped_fence"),

  WARPED_FENCE_GATE("minecraft:warped_fence_gate"),

  WARPED_FUNGUS("minecraft:warped_fungus"),

  WARPED_FUNGUS_ON_A_STICK("minecraft:warped_fungus_on_a_stick"),

  WARPED_HANGING_SIGN("minecraft:warped_hanging_sign"),

  WARPED_HYPHAE("minecraft:warped_hyphae"),

  WARPED_NYLIUM("minecraft:warped_nylium"),

  WARPED_PLANKS("minecraft:warped_planks"),

  WARPED_PRESSURE_PLATE("minecraft:warped_pressure_plate"),

  WARPED_ROOTS("minecraft:warped_roots"),

  WARPED_SIGN("minecraft:warped_sign"),

  WARPED_SLAB("minecraft:warped_slab"),

  WARPED_STAIRS("minecraft:warped_stairs"),

  WARPED_STANDING_SIGN("minecraft:warped_standing_sign"),

  WARPED_STEM("minecraft:warped_stem"),

  WARPED_TRAPDOOR("minecraft:warped_trapdoor"),

  WARPED_WALL_SIGN("minecraft:warped_wall_sign"),

  WARPED_WART_BLOCK("minecraft:warped_wart_block"),

  WATER("minecraft:water"),

  WATER_BUCKET("minecraft:water_bucket"),

  WATERLILY("minecraft:waterlily"),

  WAXED_COPPER("minecraft:waxed_copper"),

  WAXED_CUT_COPPER("minecraft:waxed_cut_copper"),

  WAXED_CUT_COPPER_SLAB("minecraft:waxed_cut_copper_slab"),

  WAXED_CUT_COPPER_STAIRS("minecraft:waxed_cut_copper_stairs"),

  WAXED_DOUBLE_CUT_COPPER_SLAB("minecraft:waxed_double_cut_copper_slab"),

  WAXED_EXPOSED_COPPER("minecraft:waxed_exposed_copper"),

  WAXED_EXPOSED_CUT_COPPER("minecraft:waxed_exposed_cut_copper"),

  WAXED_EXPOSED_CUT_COPPER_SLAB("minecraft:waxed_exposed_cut_copper_slab"),

  WAXED_EXPOSED_CUT_COPPER_STAIRS("minecraft:waxed_exposed_cut_copper_stairs"),

  WAXED_EXPOSED_DOUBLE_CUT_COPPER_SLAB("minecraft:waxed_exposed_double_cut_copper_slab"),

  WAXED_OXIDIZED_COPPER("minecraft:waxed_oxidized_copper"),

  WAXED_OXIDIZED_CUT_COPPER("minecraft:waxed_oxidized_cut_copper"),

  WAXED_OXIDIZED_CUT_COPPER_SLAB("minecraft:waxed_oxidized_cut_copper_slab"),

  WAXED_OXIDIZED_CUT_COPPER_STAIRS("minecraft:waxed_oxidized_cut_copper_stairs"),

  WAXED_OXIDIZED_DOUBLE_CUT_COPPER_SLAB("minecraft:waxed_oxidized_double_cut_copper_slab"),

  WAXED_WEATHERED_COPPER("minecraft:waxed_weathered_copper"),

  WAXED_WEATHERED_CUT_COPPER("minecraft:waxed_weathered_cut_copper"),

  WAXED_WEATHERED_CUT_COPPER_SLAB("minecraft:waxed_weathered_cut_copper_slab"),

  WAXED_WEATHERED_CUT_COPPER_STAIRS("minecraft:waxed_weathered_cut_copper_stairs"),

  WAXED_WEATHERED_DOUBLE_CUT_COPPER_SLAB("minecraft:waxed_weathered_double_cut_copper_slab"),

  WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE("minecraft:wayfinder_armor_trim_smithing_template"),

  WEATHERED_COPPER("minecraft:weathered_copper"),

  WEATHERED_CUT_COPPER("minecraft:weathered_cut_copper"),

  WEATHERED_CUT_COPPER_SLAB("minecraft:weathered_cut_copper_slab"),

  WEATHERED_CUT_COPPER_STAIRS("minecraft:weathered_cut_copper_stairs"),

  WEATHERED_DOUBLE_CUT_COPPER_SLAB("minecraft:weathered_double_cut_copper_slab"),

  WEB("minecraft:web"),

  WEEPING_VINES("minecraft:weeping_vines"),

  WHEAT("minecraft:wheat"),

  WHEAT_SEEDS("minecraft:wheat_seeds"),

  WHITE_CANDLE("minecraft:white_candle"),

  WHITE_CANDLE_CAKE("minecraft:white_candle_cake"),

  WHITE_DYE("minecraft:white_dye"),

  WHITE_GLAZED_TERRACOTTA("minecraft:white_glazed_terracotta"),

  WHITE_WOOL("minecraft:white_wool"),

  WILD_ARMOR_TRIM_SMITHING_TEMPLATE("minecraft:wild_armor_trim_smithing_template"),

  WITCH_SPAWN_EGG("minecraft:witch_spawn_egg"),

  WITHER_ROSE("minecraft:wither_rose"),

  WITHER_SKELETON_SPAWN_EGG("minecraft:wither_skeleton_spawn_egg"),

  WITHER_SPAWN_EGG("minecraft:wither_spawn_egg"),

  WOLF_SPAWN_EGG("minecraft:wolf_spawn_egg"),

  WOOD("minecraft:wood"),

  WOODEN_AXE("minecraft:wooden_axe"),

  WOODEN_BUTTON("minecraft:wooden_button"),

  WOODEN_DOOR("minecraft:wooden_door"),

  WOODEN_HOE("minecraft:wooden_hoe"),

  WOODEN_PICKAXE("minecraft:wooden_pickaxe"),

  WOODEN_PRESSURE_PLATE("minecraft:wooden_pressure_plate"),

  WOODEN_SHOVEL("minecraft:wooden_shovel"),

  WOODEN_SLAB("minecraft:wooden_slab"),

  WOODEN_SWORD("minecraft:wooden_sword"),

  WOOL("minecraft:wool"),

  WRITABLE_BOOK("minecraft:writable_book"),

  WRITTEN_BOOK("minecraft:written_book"),

  YELLOW_CANDLE("minecraft:yellow_candle"),

  YELLOW_CANDLE_CAKE("minecraft:yellow_candle_cake"),

  YELLOW_DYE("minecraft:yellow_dye"),

  YELLOW_FLOWER("minecraft:yellow_flower"),

  YELLOW_GLAZED_TERRACOTTA("minecraft:yellow_glazed_terracotta"),

  YELLOW_WOOL("minecraft:yellow_wool"),

  ZOGLIN_SPAWN_EGG("minecraft:zoglin_spawn_egg"),

  ZOMBIE_HORSE_SPAWN_EGG("minecraft:zombie_horse_spawn_egg"),

  ZOMBIE_PIGMAN_SPAWN_EGG("minecraft:zombie_pigman_spawn_egg"),

  ZOMBIE_SPAWN_EGG("minecraft:zombie_spawn_egg"),

  ZOMBIE_VILLAGER_SPAWN_EGG("minecraft:zombie_villager_spawn_egg");

  @Getter
  private final Identifier namespaceId;

  VanillaItemId(String namespaceId) {
    this.namespaceId = new Identifier(namespaceId);
  }
}
