name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan All'
        uses: JetBrains/qodana-action@v2023.3
        if: ${{ github.event_name == 'workflow_dispatch'}}
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      - name: 'Qodana Scan PUSH'
        uses: JetBrains/qodana-action@v2023.3
        if: ${{ github.event_name != 'workflow_dispatch'}}
        with:
          pr-mode: true
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}